### ISSUE TITLE
CODECOPY before, inside and after CALL/ *CALLCODE* /CREATE

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/tests#100]
need some tests for that

**Comment by winsvega** [comment]
here is some test scenarios that I am currently doing fillers for:
 
Note: when callcode is working it using caller's storage.
Correct schemas (contract subcalls)
(x)<call> <call>
(x)<call> <callcode>
(x)<callcode> <call>
(x)<callcode> <callcode>  (4 correct tests)

(x)<call> <call> <call>
(x)<call> <call> <callcode>
(x)<call> <callcode> <call>
(x)<call> <callcode> <callcode>
(x)<callcode> <call> <call>
(x)<callcode> <call> <callcode>
(x)<callcode> <callcode> <call>
(x)<callcode> <callcode> <callcode>  (8 correct tests)					

(x)The same 12 tests but with OOG at the end  (24)
The same last 8 tests but with OOG at the middle after call (32) 
Mixing suicide in the middle calls/callcode in 8 tests (40)
Mixing suicide in at the end calls/callcode in 12 tests (52)

(Recusive calls)
A<callcodeB> B<callcodeC> C<callcodeB>  - recursive callcode call
A<callcodeB> B<callcodeC> C<callB>  - recursive callcode/call call
A<callcodeB> B<callC> C<callcodeB>  - recursive call/callcode call
A<callB> B<callcodeC> C<callcodeB>  - recursive callcode call
A<callB> B<callcodeC> C<callB>  - recursive callcode/call call
A<callB> B<callC> C<callcodeB>  - recursive call/callcode call
A<callB> B<callC> C<callB>  - recursive calls
A<callcodeB> B<callC> C<callB>  - recursive calls

(60 tests total)
The same last 8 tests but with OOG at the middle before call
