### ISSUE TITLE
Illformed value in GeneralStateTests/stTransactionTest/ValueOverflow.json

### ISSUE THREAD

**Issue by yperbasis** [ethereum/tests#1001]
In GeneralStateTests/stTransactionTest/ValueOverflow.json:
```
            "value" : [
                "0x:bigint 0x10000000000000000000000000000000000000000000000000000000000000001"
            ]
```
For comparison, in GeneralStateTests/stTransactionTest/CreateMessageReverted.json:
```
            "value" : [
                "0x64"
            ]
```

**Comment by winsvega** [comment]
thats a new feature 
this way it is possible to create rlps with transaction values more than 256bits

if you parse or read transaction in filled tests, read `txbytes`
it does not require for you to build vrs from secret and indexes, and it is exactly the data that being tested. 
`transaction` section is to be used to human read the values inside transaction.
