### ISSUE TITLE
Invalid difficulty in blockchain tests

### ISSUE THREAD

**Issue by wanderer** [ethereum/tests#103]
the difficulty looks wrong here https://github.com/ethereum/tests/blob/develop/BlockchainTests/bcBlockGasLimitTest.json#L8
since its the same as the genesis; here 
https://github.com/ethereum/tests/blob/develop/BlockchainTests/bcBlockGasLimitTest.json#L110

**Comment by CJentzsch** [comment]
the difficulty would go down, if there would not be the minimal difficulty: https://github.com/ethereum/common/blob/master/params.json#L6
