### ISSUE TITLE
Test name wrong

### ISSUE THREAD

**Issue by shemnon** [ethereum/tests#1032]
Test name for `maxPriorityFeePerGas00prefix` in the file `maxPriorityFeePerGass32BytesValue` but it should match the file name.

https://github.com/ethereum/tests/blob/develop/TransactionTests/ttEIP1559/maxPriorityFeePerGas00prefix.json#L2

This is something the filler generator should catch?  At least duplicates?

**Comment by winsvega** [comment]
I think no. Because one ttTest file can have many test cases inside. 
@MarcusWentz

**Comment by MarcusWentz** [comment]
Corrected in this PR: https://github.com/ethereum/tests/pull/1035

**Comment by MarcusWentz** [comment]
@shemnon YAML generated tests can detect inconsistent Filler test names with their file names. JSON generated tests don't seem to detect test/file naming differences.

**Comment by shemnon** [comment]
Thanks for fixing it.  It lead to a very confusing debug session. ;)
