### ISSUE TITLE
Some `InvalidBlocks` tests for Istanbul have a completely valid chain

### ISSUE THREAD

**Issue by gurukamath** [ethereum/tests#1037]
The following tests which are under `BlockchainTests/InvalidBlocks` seem to contain completely valid chains at least for Istanbul.

    `timestampTooLow_Istanbul`
    `timestampTooHigh_Istanbul`
    `wrongStateRoot_Istanbul` (from bcUncleHeaderValidity)
    `incorrectUncleTimestamp4_Istanbul`
    `incorrectUncleTimestamp5_Istanbul`
    `futureUncleTimestamp3_Istanbul`

These tests pass without raising any exceptions when running through the `retesteth` [tool](http://retesteth.ethdevops.io/web/index.php)

Edit:- I think the `bcUncleHeaderValidity/correct.json` file also does not belong among the `InvalidBlocks` tests. (Also see [legacy tests issue](https://github.com/ethereum/legacytests/issues/2))

**Comment by winsvega** [comment]
InvalidBlocks assume there might be an invalid block, but not guaranteed.

**Comment by qbzzt** [comment]
It is necessary to have tests in InvalidBlocks if they are invalid for *any* fork. They could be valid for earlier or later forks.

**Comment by gurukamath** [comment]
In that case, could only those forks be included where the the tests are invalid? i.e. where the blocks provided in the tests fail to process. Eg - Could we just skip `Istanbul` for the above mentioned tests

**Comment by winsvega** [comment]
the point is actually that you should pass all tests with blocks being rejected and ideally reject it for the same reason, because if you accept an invalid block thats not good.

**Comment by gurukamath** [comment]
Thanks for the details.
