### ISSUE TITLE
Add tests for upcoming difficulty bomb push fork

### ISSUE THREAD

**Issue by marioevz** [ethereum/tests#1042]
As the title says, the following bomb push will happen in the upcoming weeks and will likely be a 700,000 block push.
Appropriate tests will be added to this repository.

**Comment by jochem-brouwer** [comment]
Is there an EIP or spec somewhere? And a fork name?

**Comment by marioevz** [comment]
None that I know of yet, but will keep this issue updated once I have all the final values and the EIP number.
@timbeiko do you know if we have an EIP yet ? Thanks.

**Comment by timbeiko** [comment]
See the spec for the fork here: https://github.com/ethereum/execution-specs/pull/537

I think unless someone has an objection, it's unlikely to change, but want to wait until wednesday to merge.

**Comment by marioevz** [comment]
Added PR #1043 for this.
