### ISSUE TITLE
Incorrect JSON: BasicTests/difficulty*.json

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/tests#105]
Guys, could you please fix the JSON files so parsers don't fail on them: 
`BasicTests/difficultyXXX.json` has an extra comma at the end of the testcases list.

**Comment by Nashatyrev** [comment]
Thanks!

**Comment by Nashatyrev** [comment]
The same issue with at least `difficultyFrontier.json` and `difficultyHomestead.json`
Guess some script needs to be fixed

**Comment by winsvega** [comment]
updated and fixed

**Comment by konradkonrad** [comment]
> who tests the tests?

Here's my minimal test-script for the tests:
- for humans
  
  ```
  find . -name "*.json" -exec echo {} \; -exec python -mjson.tool {} /dev/null \; 2>&1 |grep --before 1 "Expecting"
  ```
- for machines/travis
  
  ```
  find . -name "*.json" -print0 | xargs -I file -n1 -0 python -mjson.tool file /dev/null
  ```

**Comment by winsvega** [comment]
tests are executed by  libethereum/testeth via json_spirit lib.
