### ISSUE TITLE
Block numbers in the Homestead tests are less than 1150000

### ISSUE THREAD

**Issue by RomanZacharia** [ethereum/tests#109]
Block numbers in the Homestead difficulty tests are less than 1150000
https://github.com/ethereum/tests/blob/develop/BasicTests/difficultyHomestead.json

**Comment by winsvega** [comment]
http://ethdocs.org/en/latest/contracts-and-transactions/ethereum-tests/difficulty_tests/index.html?highlight=difficultyHomestead

Tests for homestead difficulty (regardless of the block number)
