### ISSUE TITLE
Eliptic curve param validations

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#110]
Guys , 

Can you please add testing for that one: 

https://github.com/ethereum/ethereumj/issues/353

**Comment by winsvega** [comment]
There are tests that check v,r,s conditions for precompiled contract ECRecover
http://gavwood.com/paper.pdf (212)

Here it is 
https://github.com/ethereum/tests/blob/develop/StateTests/stPreCompiledContracts.json
https://github.com/ethereum/tests/blob/develop/StateTests/Homestead/stPreCompiledContracts.json

As well as transaction signature validation tests 
https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json

https://github.com/ethereum/tests/blob/develop/TransactionTests/Homestead/ttTransactionTest.json

More info for Tests on ethdocs.org
http://ethdocs.org/en/latest/contracts-and-transactions/ethereum-tests/index.html
