### ISSUE TITLE
new field in generated tests:  txtrace

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#1104]
**Suggestion:** 

add optional field `txtrace`
```
"Berlin" : [
                {
                    "hash" : "0x5dc53b4abee831ead995ad46451d3692f102d1f6bae2744dc596c112b8bdba2d",
                    "indexes" : ---
                    "logs" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
                    "txbytes" : ---
                    "txtrace" : "0x60356035606060606086620186f16160205060555050"
                },
```

`txtrace` that represents vm instructions log. 

**why**

with this field information we can query all existing tests if they ever executed an opcode1 folloved by opcode2 and so on. 

**downside**

this process takes a long time to generate the test, gathering vmtrace information from geth t8n
increase overall tests size with this debug information that can be obtained on the fly by regenerating the test

**Comment by qbzzt** [comment]
I expect very often what people care about isn't "opcode1 followed by opcode2", but "opcode 1 followed by opcode2, under condition-set 3". That would require a much longer trace.

Did any execution client team ask for this? Or for something this will enable?

**Comment by winsvega** [comment]
under condition set  we implement in a search engine. what we need is this opcode trace history. so it is possible to analyze if condition has happened. 

`like regex.    CALLCODE->CREATE2->SUICIDE    =   is there a tests where inside callcode happens create2 and inside create2 init code suicide is executed`

no, no team request. just a research work

**Comment by qbzzt** [comment]
Then it makes sense. Maybe have it only generate if you have a special command line flag after `--filltests`. That way it doesn't make the test repository bigger, you'll just do a second generation for the search engine.

**Comment by hmijail** [comment]
I can see how this would have been useful for a past project (code merklization). But we additionally needed the PC for each opcode...
A suggestion: the "txtrace" name would be confusing, because there is already something called a trace and is different to this. Maybe "opcodeSequence" or some such?

**Comment by winsvega** [comment]
There is a way to have pc log too
