### ISSUE TITLE
EIP folder naming

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#1106]
**Option 1:**   
  Put all dependent eips as subfolders into each other

```
stEIP3670 
.     |- test1
.     |- test2
.     |-  stEIP4200
.            |- test1
.            |- test2
```

Option 2: 
  Merge eip names into folder name `stEIP3670+4200+xxxx`, hoping that there wont be 50 eips around the same topic. 
  this is because you can clearly see what eips are covered in this folder. compared to option1, there it still kind of hidden, but better organized. 

```
stEIP3670+4200 
.     |- testEIP3670_1
.     |- testEIP3670_2
.     |- testEIP4200_1
.     |- testEIP4200_2
```

Option 3:
Group the test into folders. 
```
stEOF
.     |- stEIP3670
.     ..... testEIP3670_1
.     ..... testEIP3670_2
.     |- stEIP4200
.    .....  testEIP4200_1
.    .....  testEIP4200_2
.     |- stEIP3670_JAN23
.     ..... testEIP3670_1
.     ..... testEIP3670_2
```

@gumb0, @hugo-dc, @marioevz, @holiman

**Comment by gumb0** [comment]
Option 1 seems too complicated, what if EIP depends on two others (like 4200 does), which folder to put it...

One folder is convenient, but we would name it `stEOF`, we don't know which set of EIPs will be included in the end. It's not going to be 50 of them, but it can be `st3540+3670+4200+4750` or it can be `st3540+3670+4200+4750+5450`...

Also note that EOF related EIPs currently all have prefix "EIP - " in the title, so easily searchable.

(Also there's EIP-663 which depends on EOF, but we don't consider it part of core EOF package, so tests would probably go into different folder)

**Comment by qbzzt** [comment]
I'm with @gumb0 . Multi-EIP changes should probably be named `st<functionality>`.  When it's one or two EIPs, `stEIP<n>+<m>` makes more sense.

**Comment by winsvega** [comment]
So stEOF  and then inside testEIPxxxx

**Comment by holgerd77** [comment]
Suggestion from @gumb0 also makes sense to me, also from a practical perspective

**Comment by winsvega** [comment]
subfolders yes or no?

**Comment by qbzzt** [comment]
For my money, no. The concern about EIP a depending on both EIP b and EIP c
is valid.

**Comment by winsvega** [comment]
then it is like this
```
stEOF
.     |- testCREATE_EIP3670_1
.     |- testCREATE2_EIP3670_2
.     |- testTransaction_EIP4200_1
.     |- testTransaction_EIP4200_2
.     |- testEIP3670+4200_1
.     |- testEIP3670+4200_2
```

**Comment by winsvega** [comment]
Suggest: 
```
stEOF
....|- stEIP3540 
....|- stEIP3670
```

**Comment by gumb0** [comment]
Subfolders seem to be convenient when we work on the tests for one EIP and want to regenrate tests for it.

**Comment by winsvega** [comment]
also since I have now 2 contributions around the same topic. 
gumb0 did 3540 folder. but now there is another 3670. so for you not to mess with each other tests. 
and then if you want even more tests. you can add stEIP3540_jan2023 or smth. 
because if it all stays in one folder we will get lost

**Comment by winsvega** [comment]
Even more. Can make a general subfolder:
`src/GeneralStateTestsFiller/Shanghai`
And inside of it tests 

```
stEOF
....|- stEIP3540 
....|- stEIP3670
stEIP4200
....
```
and so on. this way we know ok. all the tests for upcoming Shanghai eips are in Shanghai folder. 
so you go there and run it without picking up folders from GeneralStateTestFiller
then once EIPS are settled. we rename networks in tests to just Shanghai 
and for unsettled it will remain Merge+xxxx

otherwise tests for eips are spreading and get lost in general folders like stCreate
there we have all the tests we can think of aroun stCreate bugs since the very begining (all forks).

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/1109

**Comment by holgerd77** [comment]
It is not decided that the EOF EIPs will make it into Shanghai (actually at the moment it is rather more likely that they will not than that they will, just some personal estimate though), so I think this is misleading to put all this in a `shanghai` folder, there is always also the danger that others (worst case: media) pick these things up.

I would very much think here that an `stEOF` folder is already giving enough structure and at the same time this aviods potential confusion.

**Comment by winsvega** [comment]
stEOF is not the only possible eip series that comes with tests. if Shanghai is misleading, can rename it or 
to keep it even more clear.  

there is `GeneralStateTests`  for all the state tests. 
how about `EIPStateTests` separate folder for eips tests. completely separated from state tests folder so no confusion then. and once it accepted we move it to Shanghai folder with fork name Shanghai.

**Comment by winsvega** [comment]
Here an example: https://github.com/ethereum/tests/pull/1110
@holgerd77

**Comment by winsvega** [comment]
any objections?
https://github.com/ethereum/tests/pull/1110/files

**Comment by hugo-dc** [comment]
> any objections? https://github.com/ethereum/tests/pull/1110/files

I don't have any objection for this way organizing the tests.

After this change, should we expect `src/GeneralStateTests` to not be updated (adding more tests)?, as new EIPs will be in EIPStateTests (?)

**Comment by winsvega** [comment]
we found a new consensus about this 
`src/GeneralStateTests/EIPTests`

so no new folders. only subfolders. it is better as some runners might check all the subfolders of GStateTests
