### ISSUE TITLE
Invalid test data

### ISSUE THREAD

**Issue by RomanZacharia** [ethereum/tests#112]
[The compiled contract code](https://github.com/ethereum/rpc-tests/blob/master/lib/config.js#L19)

does not contain the receipt log topic ('0000000000000000000000000000000000000000000000000000000000000001') which is [encoded in the rlp](https://github.com/ethereum/tests/blob/25912e023e7cf25c33ed6dff078df0c941f2c7d6/BlockchainTests/bcRPC_API_Test.json#L948).

The topic value '0000000000000000000000000000000000000000000000000000000000000001' must be contained within the compiled contract code as it is encoded in the test data in https://github.com/ethereum/tests/blob/25912e023e7cf25c33ed6dff078df0c941f2c7d6/BlockchainTests/bcRPC_API_Test.json#L948 (Commit 25912e0)

**Comment by winsvega** [comment]
Wait. Why this contract should contain the receipt log topic?
Those RLP in json represent block.
