### ISSUE TITLE
baseFeePerGas or gasPrice incorrect in creationTxInitCodeSizeLimit_d0g0v0_Shanghai

### ISSUE THREAD

**Issue by jangko** [ethereum/tests#1139]
maybe related to #1133.

baseFeePerGas in block 1 is 0x0b, but gasPrice is 0x0a. 

https://github.com/ethereum/tests/blob/e279c3d0a53e2f3055c7d7f72f993b62dde18e36/BlockchainTests/GeneralStateTests/EIPTests/stEIP3860/creationTxInitCodeSizeLimit.json#L116

https://github.com/ethereum/tests/blob/e279c3d0a53e2f3055c7d7f72f993b62dde18e36/BlockchainTests/GeneralStateTests/EIPTests/stEIP3860/creationTxInitCodeSizeLimit.json#L140

it will violate EIP1559 rule after tx normalization:
```
# ensure that the user was willing to at least pay the base fee
assert transaction.max_fee_per_gas >= block.base_fee_per_gas
```

invalid tx will not be included in the block, but the test vector include the tx in the block.
looks like either baseFeePerGas or gasPrice is incorrect.

**Comment by jangko** [comment]
looks like many of test cases in BlockchainTests\GeneralStateTests\EIPTests\stEOF also suffer from the same problem.
especially "Shanghai" test cases.

**Comment by winsvega** [comment]
Yes looks like it was generated with the bug.

**Comment by winsvega** [comment]
fixed https://github.com/ethereum/tests/pull/1141
