### ISSUE TITLE
Erroneous withdrawalsroot in shanghai tests

### ISSUE THREAD

**Issue by holiman** [ethereum/tests#1157]
https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/EIPTests/stEOF/ori/CreateEOF1.json#L33

```
                    "uncleHash" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
                    "withdrawalsRoot" : "0x0000000000000000000000000000000000000000000000000000000000000000"
                },
```
The withdrawalsroot looks wrong, and it's being rejected by geth in hive-tests: https://hivetests.ethdevops.io/suite.html?suiteid=1675224715-f273ed66dcee01023162b764a3e30373.json&suitename=consensus#test-47 .

**Comment by winsvega** [comment]
Looks like it was generated on geth version that didn't return withdrawals root. Need to update on newest version

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/1158
