### ISSUE TITLE
Split EIPTests into a different branch so not to confuse

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#1171]
tests in EIPTests are experimental and often not refer to updated specs. this leads to confusion. 
I prefer to keep develop branch updated to the latest specs of all accepted EIPs. 

I Suggest to move EIPTests folder to a separate test branch. and merge experimental tests there

@holiman @marioevz

**Comment by holgerd77** [comment]
Totally see the problem. I wonder if these are a bit (too) hidden though if in a separate branch? 🤔 With some risk that people are not using? Maybe there are also other options to explore? Not have the one brilliant idea though yet.

**Comment by winsvega** [comment]
Another option was to make it be in a separate folder like ExperimentalTests next to GeneralStateTests and BlockchainTests folder

**Comment by jangko** [comment]
> Another option was to make it be in a separate folder like ExperimentalTests next to GeneralStateTests and BlockchainTests folder

I vote for this one

**Comment by winsvega** [comment]
Here is the suggestion:

```
src/EIPTestsFiller   ==>   EIPTests (state test format)
src/EIPTestsFiller   ==>   BlockchainTests/EIPTests/GeneralStateTests (blockchain test format)
src/BlockchainTestsFiller/EIPTests  ==>  BlockchainTests/EIPtests
```

@jangko @holgerd77 

this way EIPTests remain separate from normal tests. explicitly and never are in subfolder of normal tests.

**Comment by winsvega** [comment]
here all EIP tests are living in a separate EIPTests folder. both bc and state versions 
https://github.com/ethereum/tests/pull/1192
