### ISSUE TITLE
Extend the contract ABI test suite

### ISSUE THREAD

**Issue by axic** [ethereum/tests#118]
It consists currently only of [3 tests](https://github.com/ethereum/tests/blob/develop/ABITests/basic_abi_tests.json).

It could be extended with the tests from web3.js, ethereumjs-abi and go-ethereum/abigen. Perhaps there are other implementations which have additional tests which could be imported.

**Comment by winsvega** [comment]
I think its related to solidity. 
https://github.com/ethereum/solidity/tree/develop/test

which now has it separate test suite.

**Comment by axic** [comment]
Solidity doesn't have a dedicated ABI encoding/decoding test suite (which could be useful though).

However it is not only Solidity which uses the ABI, but all the tools interacting with contracts.

**Comment by winsvega** [comment]
@axic is this the topic for solidity tests?

**Comment by axic** [comment]
No, it is not related to Solidity. It is about a test suite for the ABI specification.

All ABI implementers have their own test suite (Solidity, web3.js, ethereumjs-abi, ethjs-abi, etc.), but there is no common base all these implementations test for.

**Comment by fubuloubu** [comment]
Moving ABI specification and test suite to this org: https://github.com/ethabi
