### ISSUE TITLE
RPC Tests?

### ISSUE THREAD

**Issue by danfinlay** [ethereum/tests#119]
Would it be possible to extend this suite to also test the RPC API responses for the different clients?

Ideally I could submit a blockchain state, and a query, and compare the responses of every client.

**Comment by chriseth** [comment]
We are planning to do this inside http://github.com/ethreum/interfaces or as part of the hive project. The reason is that this repository requires the test runner to be implemented in the clients themselves, while hive provides a generic interface to run the clients.

**Comment by frozeman** [comment]
The rpc test currently require the client to load a BC state and it teste against those. It should also already work with at least cpp and geth.

But if we can do that better in hive, im all for it :P

**Comment by winsvega** [comment]
@cdetrio @holiman @karalabe 
does this implemented on hive? 

I have some work done in this direction for cpp client RPC tests:
https://github.com/ethereum/tests/tree/develop/RPCTests

**Comment by karalabe** [comment]
The old suite is on hive, but that's not maintained. Bas wrote a new suite that I think is a pending PR on hi e.

**Comment by winsvega** [comment]
A topic is to be implemented with retesteth.
