### ISSUE TITLE
Invalid timestamps in BasicTests/difficultyMainNetwork.json since Shanghai

### ISSUE THREAD

**Issue by siladu** [ethereum/tests#1207]
Since shanghaiTime is part of the mainnet genesis now, the Shanghai rules kick in on timestamps above `1681338455` as per https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md#upgrade-schedule

The following file is failing in the besu reference tests because we're assigning Shanghai rules to what was previously supposed to be Frontier in the following case for example:
https://github.com/ethereum/tests/blob/develop/BasicTests/difficultyMainNetwork.json#L3-L10

It looks like multiple timestamps in that file are far into the future, which means they now are treated as Shanghai blocks and therefore fail the difficulty tests.

e.g. `0x036d2f0c29` is `14716701737` which is `Friday, 9 May 2436 04:42:17`

**Comment by shemnon** [comment]
I would argue the reference tests are now wrong.  There is no genesis specified by the tests and the file names imply mainnet, which includes all configurations at the time the test is run.

I would generate a patch for the tests repo with values that Besu would pass and submit it as the new "shanghai" values.

In the interim we can effetively disable shanghai time

```
        Arguments.of(
            "/BasicTests/difficultyMainNetwork.json",
            MainnetProtocolSchedule.fromConfig(
                GenesisConfigFile.mainnet()
                    .getConfigOptions(Map.of("shanghaiTime", "999999999999")),
                EvmConfiguration.DEFAULT)),
```

**Comment by siladu** [comment]
> I would generate a patch for the tests repo with values that Besu would pass and submit it as the new "shanghai" values.

Happy to do this - are there any docs available for how to create the patch?

**Comment by shemnon** [comment]
nope.

**Comment by winsvega** [comment]
looks like those tests are very outdated. what was main network back then is Frontier. 

here are the new tests https://github.com/ethereum/tests/tree/develop/DifficultyTests
