### ISSUE TITLE
t8n --allow invalid fixture generation

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#1244]
Add a flag to t8n `--alowinvalid` that will disable sanity checks for transactions and instead of being rejected with error code, tx are accepted and post state is calculated (if it is possible) to be able to produce invalid fixtures deliberatly.

Like in example with blob transactions: 

```
createBlobhashTx, that create transaction is not allowed. 
emptyBlobhashList, that tx with empty blobs list is not allowed. 
```

with new flag --allowinvalid  that t8n will print a warning that the fixture is invalid and like in here, tx are not rejected and accepted. (0 blobhashes, create blob tx and so on, so we can generate invalid tests) but this is a big question because there are many checks to consider.

**Comment by holiman** [comment]
Not sure what you are missing. You can supply an invalid tx, e.g. empty blobs, and t8n will reject it, and thus the output state root will not be modified by the tx. 

Later on, you can put this invalid tx into a statetest, and expect a well-behaving client to also reject it, and arrive at correct stateroot. 

The t8n tool is not the one who decides what to include into a test, your test gen tool does that. T8n provides state awareness and evm execution: state transition.

**Comment by winsvega** [comment]
that is how currently I do
just that when I discovered this issue, an opinion was made to keep this behavior to be able to make invalid states. 
but I am afraid it will get too messy with what is valid and invalid so it must be a special kind of t8n

**Comment by winsvega** [comment]
The discussion is a research topic for pyspecs and python t8n
