### ISSUE TITLE
Another suicide testcase to cover

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/tests#127]
When a contract is suicided in a call which is then failed refund for this suicide should be reverted. 
This case led to the conflict of EthereumJ impl when executing Tx https://etherscan.io/tx/0xdaa8cbac16a3e92fb3206c8f3e06815d8fc51da714184ec6ed8e957a32beb2b3 while all TCK tests are passed. 
Here is reference Solidity code: 
```
contract B {
  function f(){
    suicide(msg.sender);
  }
}
contract A {
  function f(){
    this.call(bytes4(sha3('bad()')));
  }
  function bad() {
    B b = new B();
    b.call(bytes4(sha3('f()')));
    throw;
  }
}
```

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stRevertTest/NashatyrevSuicideRevertFiller.json
