### ISSUE TITLE
Add some state tests with transaction from non-existing account

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#1286]
This is untested territory in state tests. A transaction's sender may be non-existing account. Surely, such transaction will be invalid if base fee is non-zero. But we still want to make sure such transaction is properly validated.

**Comment by winsvega** [comment]
hm, we have bc tests for this. since t8n is used it will test the same logic. 
you need such case for a custom test runner?

**Comment by chfast** [comment]
No, I need this for my statetest runner.
