### ISSUE TITLE
Add opcodes to gas measurement

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#1296]
looks like the gas measure algo fails for sha3 and mload in this test on latest solc 21
```
info: (GeneralStateTests/stBadOpcode/measureGas, fork: Cancun, TrInfo: d: 0, g: 0, v: 0, TrData: `:label CREATE       :abi f(uint) 0xF0..`)
info: (GeneralStateTests/stBadOpcode/operationDiffGas, fork: Cancun, TrInfo: d: 6, g: 0, v: 0, TrData: `:label MLOAD        :abi f(uint,uint,uint) ..`)

```

work branch https://github.com/ethereum/tests/pull/1297

**Comment by qbzzt** [comment]
I think this is because the test creates a value that is not used, and Yul is now smart enough to figure that. I'll add an `SSTORE` there, but probably tomorrow. Right now I'm testing the #1298 solution.

**Comment by qbzzt** [comment]
Need to also add measurements for:

1. TLOAD
2. TSTORE
3. BLOBHASH
4. BEACONROOT

**Comment by winsvega** [comment]
this tests fixed by solc optimisation fix. 
but now you mentioned new opcodes so I leave this issue open
and we got new issues: https://github.com/ethereum/tests/issues/1309

**Comment by qbzzt** [comment]
I reconsidered this, and I think the tests we have in this issue (`stBadOpcde/measureGas` and `measureGas/operationDiffGas`) are simple enough they won't benefit from being measured here. The only reason we do these measurements with memory is that memory has two gas costs: the cost of the operation and the cost of memory expansion.
