### ISSUE TITLE
VM test missing for CODECOPY on STOP instruction

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#130]
In `VMTest`, there are no test that performs `CODECOPY` that copies `STOP` (in the code) into the memory (I tried only those tests that run only one account).

Also, `RETURN`, `DELEGATECALL` and `SUICIDE` are never `CODECOPY`ed.

**Comment by winsvega** [comment]
@pirapira  status?

**Comment by pirapira** [comment]
Open.
