### ISSUE TITLE
More tests for EIP-7516: BLOBBASEFEE opcode

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#1300]
https://eips.ethereum.org/EIPS/eip-7516

**Comment by qbzzt** [comment]
@winsvega , how do I set the `BLOBBASEFEE` value? Do I put it in the env section for state tests, and block header for block tests?

**Comment by winsvega** [comment]
Looks like it is this one

```
def get_blob_gasprice(header: Header) -> int: return fake_exponential( MIN_BLOB_GASPRICE, header.excess_blob_gas, BLOB_GASPRICE_UPDATE_FRACTION )
```

Should be affected by blob hashes included in this and previous blocks

**Comment by winsvega** [comment]
more tests in pyspecs
