### ISSUE TITLE
Invalid JSON filler files from `GeneralStateTestsFiller`

### ISSUE THREAD

**Issue by rodibozman** [ethereum/tests#1305]
While parsing some of the filler files from `GeneralStateTestsFiller`, I've found some that are invalid JSON files:

* `src/GeneralStateTestsFiller/stMemoryTest/callDataCopyOffsetFiller.json` - missing comma
* `src/GeneralStateTestsFiller/stMemoryTest/calldatacopy_dejavu2Filler.json`  - missing comma

**Comment by winsvega** [comment]
can you please commit a fix?

**Comment by rodibozman** [comment]
Sure I opened an MR [here](https://github.com/ethereum/tests/pull/1310).

**Comment by winsvega** [comment]
the fillers are more of a pseudo json format. it has double keys. (//comments) 
do you try read it as json. 
also for what perpuse you read the filler file?

**Comment by rodibozman** [comment]
We need it internally to check the outcome of a scenario by looking at what is expected after each scenario ends.
For internal reasons we can not rely on the `hash` in the `post` section of the test cases: this is why we need to look out for the `expect` section of filler files.

The double keys are not a problem. 99% of the JSON filler files from `GeneralStateTestsFiller` are valid JSON, to be exhaustive we need those two as well.

Could you please have a look at [!1310](https://github.com/ethereum/tests/pull/1310)? Thanks.

**Comment by winsvega** [comment]
that would be a weak check, since expec section validate logical part of the test
the final test post state still can have fork related changes that you might miss. 
all state tests has bc version which is identical. you can find the full post state there. 

I added a fix to json parser, such invalid formats will be errored out in the future.

**Comment by rodibozman** [comment]
> that would be a weak check, since expec section validate logical part of the test
the final test post state still can have fork related changes that you might miss.

We are aware of it. Don't have a workaround for now.

> I added a fix to json parser, such invalid formats will be errored out in the future.

Thanks.
