### ISSUE TITLE
VM tests missing for block numbers after Spurious Dragon

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#131]
The test cases in `VMTests` assume small block numbers.  No tests try the gas calculation after the Spurious Dragon changes.

This means only the older gas calculation is tested especially for EXTCODE, BALANCE and SLOAD.

**Comment by winsvega** [comment]
VMTests does not run on other forks other then the Homestead, right?

**Comment by holiman** [comment]
That's my interpretation aswell.

**Comment by winsvega** [comment]
@pirapira removes ethereum related tests from VMTests. 
So that VM only test the basic logic without (SLOAD, CREATE, CALL, BLOCKHASH) and so on. 
So it seems that blocknumber is not needed.
