### ISSUE TITLE
Incorrect post state for `doubleSelfdestructTest_d5g0v0_Cancun`

### ISSUE THREAD

**Issue by hratoanina** [ethereum/tests#1318]
https://github.com/ethereum/tests/blob/428f218d7d6f4a52544e12684afbfe6e2882ffbf/BlockchainTests/GeneralStateTests/stSystemOperationsTest/doubleSelfdestructTest.json#L3472
Is the post state correct here? From what I understand from the bytecode, the recipient of the selfdestruct call is supposed to be the `c0de` account itself (which seems to match the post state of the other fork variants), but for Cancun the balance seems to have been sent to the `1001` account instead.

**Comment by winsvega** [comment]
@hratoanina 
is this resolved now?

**Comment by winsvega** [comment]
@hratoanina

**Comment by hratoanina** [comment]
Sorry, I can't run the test myself at the moment, but my concerns are the same. The bytecode and the data of the transaction is the same as the other variants, but the funds seem to be transferred to account `1001` (instead of doing nothing according to EIP-6780.

**Comment by Nashtare** [comment]
@winsvega It seems fixed since the test regeneration! (working with @hratoanina)
Thanks!
