### ISSUE TITLE
VM tests missing for insufficient stack height for ADDMOD or MULMOD

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#132]
No VM tests try `ADDMOD` or `MULMOD` with insufficient stack heights.

(I haven't checked the 24 test cases that run multiple contracts.)

**Comment by pirapira** [comment]
<del>I checked the number of stack elements before entering these funcitons. That's why the coverage seems low.</del> That was not the case.

**Comment by winsvega** [comment]
@pirapira status?

**Comment by pirapira** [comment]
Open.

**Comment by qbzzt** [comment]
Solved by #786
