### ISSUE TITLE
VM tests missing for JUMPI with insufficient stack height

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#133]
No VM test tries `JUMPI` with stack height less than two.

(I haven't checked the 24 VM tests that run multiple contracts.)

**Comment by pirapira** [comment]
<del>I checked the number of stack elements before entering these funcitons. That's why the coverage seems low.</del>  That was not the case.

**Comment by winsvega** [comment]
@pirapira  status?

**Comment by pirapira** [comment]
Open.

**Comment by qbzzt** [comment]
Solved by #786

**Comment by winsvega** [comment]
this was about VMTests not state tests. since we transfer VMTests into state tests it kind of solved, but as a part of more complex state test in 786
