### ISSUE TITLE
Unify zero/non-existent storage slots

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#1330]
Storage slots of zero values are interpreter as non-existent / deleted and these are not included in the Merke-Patricia Trie.
It is incorrect for the tests to contain a pre-state with explicit zero storage values.

**Comment by winsvega** [comment]
Is there a difference then?
Zero slots can be interpreted as non existent. Or is it causing wrong post state results?

**Comment by chfast** [comment]
It requires the special handling of the test state because zero values are never in the trie. E.g. you need to specifically filter zeros when loading JSON.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/1347

**Comment by winsvega** [comment]
a few in pyspecs to fix as well

**Comment by winsvega** [comment]
done
