### ISSUE TITLE
Apply EIP-7523: no empty accounts since Paris (Merge)

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#1331]
Since the Paris revision there should be no empty accounts in test pre-states.

https://eips.ethereum.org/EIPS/eip-7523

**Comment by winsvega** [comment]
ok, will adjust. currently a big update is coming upgrading many tests

**Comment by chfast** [comment]
See https://github.com/ethereum/tests/pull/1329.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/1336
