### ISSUE TITLE
Consider renaming EOFTests -> EOFValidationTests

### ISSUE THREAD

**Issue by gumb0** [ethereum/tests#1340]
Currently there is some confusion between these two very different areas of tests:
https://github.com/ethereum/tests/tree/develop/EIPTests/StateTests/stEOF (state tests for EOF)
https://github.com/ethereum/tests/tree/develop/EOFTests (EOF validation tests)

Because both can be referred to as "EOF tests" coloquially.

**Comment by winsvega** [comment]
EOF tests are migrating into pyspecs
