### ISSUE TITLE
Cancun tests without Beacon Roots Contract

### ISSUE THREAD

**Issue by gurukamath** [ethereum/tests#1341]
For some of the tests in `cancun`, the beacon roots contract is not a part of the pre-state, signifying that the contract has not been deployed yet. This is not a valid test for cancun since there is an assumption that the contract is deployed already.

An example test would be the following (`develop` branch at commit ID `853b1e0`)

```
{
    'test_file': 'BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/gasLimitLTGasUsageUncle.json',
    'test_key': 'gasLimitLTGasUsageUncle_Cancun'
}
```

**Comment by winsvega** [comment]
@gurukamath 
does this branch fixes the issue ? 

https://github.com/ethereum/tests/pull/1344

**Comment by chfast** [comment]
It does not make sense to add this code to every test case. I think you should drop the assumption the code exists.

**Comment by winsvega** [comment]
https://github.com/ethereum/execution-spec-tests/issues/446

**Comment by winsvega** [comment]
for state tests for sure yes.
but what about blockchain tests. Mario's argument is that since on mainnet this contract exists we should put it in all blockchain tests as well in case to catch some beacon contract interaction

**Comment by winsvega** [comment]
all bc tests has it 
https://github.com/ethereum/tests/pull/1351
