### ISSUE TITLE
VM tests missing for CALL, CREATE, RETURN and CALLCODE with insufficient number of stack elements

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#135]
No VM tests try `CALL`, `CREATE`, `RETURN` or `CALLCODE` with insufficient number of stack elements.

(I haven't checked the 24 test cases that run multiple contracts.)

**Comment by pirapira** [comment]
<del>I checked the number of stack elements before entering these funcitons. That's why the coverage seems low.</del> That was not the case.

**Comment by winsvega** [comment]
@pirapira  status?

**Comment by winsvega** [comment]
No such opcodes in VM tests anymore?

**Comment by pirapira** [comment]
Right. This is not planned anymore.
