### ISSUE TITLE
[BlockchainTests/Cancun] Invalid post-state for Beacons root contract

### ISSUE THREAD

**Issue by Nashtare** [ethereum/tests#1352]
PR #1351 introduced the beacons root contract defined in [https://eips.ethereum.org/EIPS/eip-4788](https://eips.ethereum.org/EIPS/eip-4788) in the pre-state of each `BlockchainTests`. However, its storage update is not properly done.

Indeed, as per EIP-4788:
<img width="1049" alt="EIP-4788" src="https://github.com/ethereum/tests/assets/30937548/51da22b1-dcee-443d-8c7b-d5f84348cd45">

Especially, at the start of a new block, two storage slots should be updated:
- `timestamp_idx` (as named in the pseudocode), corresponding to `timestamp % HISTORY_BUFFER_LENGTH` -> this is done in the tests
- `root_idx` (as named in the pseudocode), corresponding to `timestamp % HISTORY_BUFFER_LENGTH + HISTORY_BUFFER_LENGTH` to be `calldata[0:32]`, i.e. the parent's beacon root. This is currently missing from post states, causing all Cancun tests to fail unexpectedly.

See for instance the post-state of [here](https://github.com/ethereum/tests/blob/af904b83c625c145adce9bbf91d95898fb0372a1/BlockchainTests/GeneralStateTests/Shanghai/stEIP3651-warmcoinbase/coinbaseWarmAccountCallGas.json#L206) or [there](https://github.com/ethereum/tests/blob/af904b83c625c145adce9bbf91d95898fb0372a1/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/01_tloadBeginningTxn.json#L91).

**Comment by winsvega** [comment]
why? the parentBeaconBlockRoot  is 0x00 as defined in the block header.

**Comment by Nashtare** [comment]
Ah nevermind, hadn't picked up that all parent block roots were 0. Will close this then. Thanks!
