### ISSUE TITLE
VM tests missing for DELEGATECALL

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#136]
No VM tests execute `DELEGATECALL`.

(On the 24 test cases that run multiple contracts, I only checked the original message call up to the point it makes a call.)

**Comment by winsvega** [comment]
@pirapira 
so the VM tests. maybe we should switch it from Hometstead rules to the latest fork available so the VM tests would always represent a set of thest for the most recent EVM changes?

**Comment by pirapira** [comment]
I think the least disruptive path is the following:

1. add `"network" : "Homestead"` in each test.
2. add one test with `"network" : "EIP158"`
3. clients start parsing `"network"` field
4. change more tests into `"network" : "EIP158"`.

**Comment by winsvega** [comment]
isnt it better to implement VMTests General?

**Comment by winsvega** [comment]
and actually @pirapira as I remember VM tests does not  perform call execution. 
what is expected behaviour with delegatecall in VMTests ?

**Comment by pirapira** [comment]
@winsvega you're right.
