### ISSUE TITLE
Question about checkGasLimit

### ISSUE THREAD

**Issue by jewei1997** [ethereum/tests#1361]
Hi, @winsvega, I'm trying to figure out what this [checkGasLimit](https://github.com/ethereum/tests/blob/80612d6ff4a06943b903eb9e8be9589b78502bea/BlockchainTests/InvalidBlocks/bcEIP1559/checkGasLimit.json#L2) test is trying to test. Would very much appreciate any insight here. Thanks!

**Comment by winsvega** [comment]
Always check the filler source to get the test logic.

https://github.com/ethereum/tests/blob/develop/src/BlockchainTestsFiller/InvalidBlocks/bcEIP1559/checkGasLimitFiller.yml

This one is checking that gaslimit rules apply to basefee transactions
