### ISSUE TITLE
dev: bump address range used in tests

### ISSUE THREAD

**Issue by enitrat** [ethereum/tests#1371]
In many test cases, we use addresses such as 0x100, 0x101, etc.
However, new improvement proposals aimed specifically for rollups (RIPs) are starting to introduce new precompiles, such as [RIP-7212](https://github.com/ethereum/RIPs/blob/master/RIPS/rip-7212.md). These precompiles will use addresses starting from 0x100.

As such, it would be good to refactor the existing tests, and modify the addresses close to 0x100 to something else, like 0x1000.

**Comment by winsvega** [comment]
so you even recalculated create addresses in some of thests expect sections? 
and no issues setting up lllc and retesteth ?

**Comment by enitrat** [comment]
@winsvega yes, I recalculated CREATE and CREATE2 addresses for some of these tests. I setup retesteth by building the Dockerfile in a Linux machine, which I used to refill the tests

**Comment by winsvega** [comment]
There is also dretesteth.sh script for docker.

Wow, you are one of the few who went through this process so smoothly

**Comment by enitrat** [comment]
> Wow, you are one of the few who went through this process so smoothly

Not very smooth 😆 it took me a first, failed try to run it locally on MacOS for ~half a day, then I gave up and SSHed into a EC2 instance running linux, tried to use the docker image specified in the docs but somehow I could not get it to work, eventually I managed to get it to work but it took like 1.5 days 😅 

Also, for CREATE/CREATE2 addresses, I don't know if there's a specific way to compute them and add them in tests, so I was  manually fixing them one by one,after each test run

**Comment by winsvega** [comment]
should have contact me for support. the docker image must work smoothly ./dretesteth.sh build. 
I check every day that it works. 

the create/create2 addresses issue we fixed in .py tests.
