### ISSUE TITLE
List KEVM as using this test suite

### ISSUE THREAD

**Issue by ehildenb** [ethereum/tests#1374]
KEVM has been using this test suite for a very long time, but isn't listed: 
![image](https://github.com/ethereum/tests/assets/12721972/e5e17692-8826-45f6-8a1d-4fa79032cc57)

- Repo: https://github.com/runtimeverification/evm-semantics/
- Path: tests/ethereum-tests
- CI Job running them: https://github.com/runtimeverification/evm-semantics/blob/7b8e3b0c1c65cb3a297bde457bb1ae0ff2740547/.github/workflows/test-pr.yml#L82
- Example CI run: https://github.com/runtimeverification/evm-semantics/actions/runs/9119190935/job/25078302837

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/1376
