### ISSUE TITLE
VM tests missing for MLOAD and MSTORE8 with insufficient number of stack elements

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#138]
No VM tests try MLOAD or MSTORE8 with insufficient number of stack elements.

(I haven't checked the 24 test cases that run multiple contracts.)

**Comment by pirapira** [comment]
<del>I checked the number of stack elements before entering these funcitons.  That's why the coverage seems low.</del> That was not the case.

**Comment by winsvega** [comment]
@pirapira  status?

**Comment by pirapira** [comment]
Open.

**Comment by qbzzt** [comment]
Solved by https://github.com/ethereum/tests/pull/786
