### ISSUE TITLE
Questionable EOF validity test case

### ISSUE THREAD

**Issue by wavefnx** [ethereum/tests#1386]
### Issue
This issue questions the validity of the EOF test [Valid Invalid 1](https://github.com/ethereum/tests/blob/ebbaa54c7a90e74313b846369fe87e9bd3a58369/EOFTests/efExample/validInvalid.json#L23C27-L23C77).

We see the code `0xef0001010004020001000304000400008000013050000bad` marked as passing for Prague, which can have undesirable effects. 

Following deconstruction we see that the data section of the header expects the body to have four (4) instead of two (2) bytes.
```evm
### header
magic  : ef00         ; eof prefix
version: 01           ; eof version
types  : 01 0004      ; 4 bytes assigned to the types section
code   : 02 0001 0003 ; 1 code section, 3 bytes
data   : 04 0004      ; 4 bytes assigned to the data section  <-- important
term   : 00           ; terminator

### body 
types  : 00 80 0001   ; 0 outputs, non-returning(0x80), 1 max stack height  
code   : 30 50 00     ; ADDRESS, POP, STOP
data   : 0b ad        ; found 2 bytes, expected 4             <-- important
```

Are there any reasons why the above should be valid? 

If not, I'm providing alternative replacements below.

### Remediation
It should be straight-forward. I can gladly open a PR or you're free to do so.

Either by replacing the affected data header to expect two (2) bytes:
```evm
0xef0001010004020001000304000200008000013050000bad
```
Or add two (2) additional bytes on the data body:
```evm
0xef0001010004020001000304000400008000013050000badbeef
```

**Comment by pdobacz** [comment]
The top-level container validation changed recently, [this PR](https://github.com/ethereum/tests/pull/1381) should adapt to it.

**Comment by wavefnx** [comment]
Sounds good, closing
