### ISSUE TITLE
Missing CHAIN_ID > 127 tests for EIP155 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/tests#142]
It seems Geth and Parity implementations support `CHAIN_ID` > 127. EthereumJ didn't support and we caught the corresponding bug. Please check my comment for details: https://github.com/ethereum/EIPs/issues/155#issuecomment-276075645
Whether or not `V` value in transaction could be > 8bit we need corresponding tests on that (positive or negative)

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/321
