### ISSUE TITLE
The case wanted when the SUICIDE refund > spent gas / 2 during contract creation

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/tests#143]
EthereumJ hit the consensus issue with that transaction: https://testnet.etherscan.io/tx/0x8ec445380649f6c75a042a438ea9256c2fab2a6a3437904c9e5a712fcbf8a54a
Check here for some more details: https://github.com/ethereum/ethereumj/issues/724
The transaction creates a contract which creates a lot of small contracts which suicide in their constructor. The final `SUICIDE refund > spent gas / 2`. For the contract creation case there is the possibility for a client implementation to miss the contract return value cost from the `spent gas` in the formula above.
It would be good to have a test for such case

**Comment by winsvega** [comment]
@Nashatyrev is this the transaction ? 
https://ropsten.etherscan.io/tx/0x8ec445380649f6c75a042a438ea9256c2fab2a6a3437904c9e5a712fcbf8a54a

**Comment by Nashatyrev** [comment]
@winsvega Yep

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/322

**Comment by winsvega** [comment]
@Nashatyrev  please check if the test reproduce the same behavior on your client
