### ISSUE TITLE
Include VM test for every invalid opcode

### ISSUE THREAD

**Issue by axic** [ethereum/tests#160]
All of them should result in exceptional halt. This is to ensure that no compliant VM implement a random opcode for other purposes.

cc @chfast

**Comment by chfast** [comment]
I think they should be in form of `PUSH(0) PUSH(0) ... INVALID_OPCODE_X` to provide some fake arguments in case they require them.

**Comment by pirapira** [comment]
I think I can start this roughly in seven weeks.

**Comment by axic** [comment]
cc @cdetrio @jwasinger

**Comment by jwasinger** [comment]
@axic I'm not very familiar with VM tests.  We have state tests for all bad opcodes: https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stBadOpcode/badOpcodes.json

Would there be a reason to add VM tests for these as well?

**Comment by chfast** [comment]
I'm not sure this is needed in case we have state tests. Are they in form of `PUSH(0) PUSH(0) ... INVALID_OPCODE_X`?

**Comment by jwasinger** [comment]
Yes. They are in this form:

```
[1] PUSH1 0x01 
[3] PUSH1 0x01 
[5] PUSH1 0x01 
[7] PUSH1 0x01 
[8] 'XX' (Unknown Opcode) 
[10] PUSH1 0x00 
[12] PUSH1 0x00 
[13] RETURN 
```

**Comment by chfast** [comment]
I would push more before `XX`, but let it be.
