### ISSUE TITLE
Duplicated tests in BlockchainTests/GeneralStateTests/stWalletTest

### ISSUE THREAD

**Issue by gsalgado** [ethereum/tests#164]
All test files in [BlockchainTests/GeneralStateTests/stWalletTest](https://github.com/ethereum/tests/tree/develop/BlockchainTests/GeneralStateTests/stWalletTest) seem to be duplicated; for every .json file, there's a copy (although not identical) with the same name but containing a space before the .json extension.

**Comment by winsvega** [comment]
resolved
