### ISSUE TITLE
The bounty website has a broken link to this repo.

### ISSUE THREAD

**Issue by kitsunde** [ethereum/tests#166]
On: https://bounty.ethereum.org/
Links to: https://github.com/ethereum/tests/blob/develop/StateTests/stExample.json
Doesn't exist.

I couldn't tell which repo is the is the bounty website, so maybe someone here can fix it.

**Comment by holiman** [comment]
Fixed, check bounty again.

**Comment by holiman** [comment]
Actually, I only fixed the wiki-link, not example. What should I point it to?

**Comment by winsvega** [comment]
https://ethereum-tests.readthedocs.io/en/latest/
and there is a link to missing test file.

**Comment by holiman** [comment]
Ok, I've removed the dead link, and pointed to the official correct documentation. LMK if you want it some other way.
