### ISSUE TITLE
Travis CI seems to be failing for all PRs

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#169]
Currently, Travis CI seems to fail on all PRs like this: https://travis-ci.org/ethereum/tests/builds/233281939?utm_source=github_status&utm_medium=notification

@winsvega agreed that the test script should check the grammar of the final tests (without `Filler.json` suffix), but not necessarily on the fillers.

**Comment by winsvega** [comment]
should be working now

**Comment by pirapira** [comment]
I noticed this started working a while ago.
