### ISSUE TITLE
More information in tests

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#183]
Lets add a new section in the result test files with more information about the test. So each test case inside result .json file would have a section like: 
```
        "_info" : {
            "comment" : "Simple test",
            "filledwith" : "cpp-1.3.0+commit.6be76b64.Linux.g++",
            "source" : "/src/GeneralStateTestsFiller/stExample/add11Filler.json"
        },
```

**Comment by pirapira** [comment]
I agree with adding the "filledwith" information.

Why is the "comment" section inside the "clientinfo"?

**Comment by winsvega** [comment]
so clientinfo is because it should be on top of the .json file.  (letter c) 
comment is because many people requested more comments to the tests

**Comment by pirapira** [comment]
So, "simple test for CREATE2 opcode" is not about the client, but it's about the test case.  I think this comment should be somewhere out of "clientinfo".

**Comment by winsvega** [comment]
perhaps the section should be named. 
"_info":

**Comment by pirapira** [comment]
OK!

**Comment by winsvega** [comment]
https://github.com/ethereum/cpp-ethereum/pull/4152

**Comment by pirapira** [comment]
@winsvega what about adding the git revision hash of `tests` repository, where the source is taken from.

**Comment by winsvega** [comment]
this is not what testeth could reliably get from the system. that would require tests to be in a git repository and system to have a git installed

**Comment by pirapira** [comment]
OK, then what about the keccak hash of the filler file?
