### ISSUE TITLE
Benchmark modexp precompiled contract in different clients

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#185]
There is [an opinion](https://github.com/ethereum/EIPs/pull/198#issuecomment-305906876) that the gas cost formula of modexp precompiled contract can be improved.  To find out the reasonal gas cost formula we need to benchmark modexp contract of different clients up to blockgaslimit.

**Comment by timxor** [comment]
@pirapira i can take that, looks fun. will work on it tonight

**Comment by pirapira** [comment]
Great.  You can choose

* to prepare and run a BlockchainTest on each client

or

* to call a routine in each client
    * https://github.com/obscuren/go-ethereum/blob/f0f23fc1739fbef5759802faad564e3e65b79395/core/vm/contracts.go#L180
    * https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/Precompiled.cpp#L123
    * https://github.com/paritytech/parity/pull/4926/files#diff-f01cea79b5ea6391c260249a4cf801a5R234

or

* to join efforts with https://github.com/ethereum/go-ethereum/pull/14641 and facilitate something similar for other clients

**Comment by timxor** [comment]
@pirapira what option do you think would be better? Go it solo or join forces....maybe solo because then it goes horizontal not vertical :)

**Comment by pirapira** [comment]
That's what I thought.  The second option will be the quickest.

**Comment by timxor** [comment]
agreed. on it.

**Comment by holiman** [comment]
I have a geth-benchmark implementation for modexp at https://github.com/holiman/go-ethereum/tree/benchmark_metro , the only thing I'm missing now are some proper values to use in testing. And I guess the other clients ought to use the same. Have either of you located any good inputs? I've found a few from the EIP examples, but I don't think they're very representative.

**Comment by timxor** [comment]
This is awesome thanks for sharing, can we make a generator for testing all ranges or what do you think the best way to test it? Are there already tests in the [test repo](https://github.com/tcsiwula/tests) that we can use? @holiman

**Comment by holiman** [comment]
I've added some inputs to my branch the other day

**Comment by holiman** [comment]
https://gist.github.com/holiman/d2a59ebc9353baffaf21389e296987c1#gistcomment-2128792

**Comment by gumb0** [comment]
@tcsiwula Hi, is there any update from you on this?

**Comment by timxor** [comment]
Hey @gumb0, I should have the parity one done by friday this week. I was interviewing for jobs the last two weeks. Is the c++ client still in active development? cc: @pirapira

**Comment by pirapira** [comment]
@tcsiwula I sent you an email.

**Comment by winsvega** [comment]
to test benchmark we have to run a scenario with calling a function/opcode on different range of input parameters and eventually build up a graph   "exec time / input parameters value"
I think making a static contract in state test is not a best option for determining the reasonable gas cost formula

**Comment by timxor** [comment]
Hello everyone, here is an update from me. Let me know where I should focus my attention/efforts next. =)

My most recent (August 9th) parity [benchmark results](https://gist.github.com/tcsiwula/cc3501ede410bcaaf7fe39fd55a65cfc) for {bn_128_add, bn_128_mul, ...}.

Here are [the steps](https://gist.github.com/tcsiwula/5f292c9c4efb978cc2a0502f0b0225b2) to recreate and run it locally on your computer (linux/ubuntu).

cc: @pirapira @holiman @arkpar @Souptacular

**Comment by pirapira** [comment]
On my machine, I get 6 times different numbers for ecadd from
[go-ethereum](https://gist.github.com/pirapira/423d5e8478e16695338962db02b0005d)
```
BenchmarkPrecompiledBn256Add/chfast1-Gas=0-4                       20000             90297 ns/op
```
and [Parity](https://gist.github.com/pirapira/fa4b4a41a600bf463b2449f7b124e4a3)
```
test bn_128_add          ... bench:      14,527 ns/iter (+/- 413)
```
(will edit with links to steps)

**Comment by pirapira** [comment]
The original purpose of this issue has been accomplished, as `modexp` gas formula has been determined.

Since we are here, maybe we can open issues for remaining problems and paste links here.

**Comment by timxor** [comment]
@pirapira wonderful, yeah that sounds good to me. What other precompile benchmarks would be useful to have that would give us a complete and accurate picture?

**Comment by pirapira** [comment]
@tcsiwula since `ecadd` and `ecmul` are supposed to be of constant gas costs, it would be great if we can come up with some numbers already.

**Comment by gcolvin** [comment]
@tcsiwula just pointed me at this issue.  I've been working with @s-matthew-english on improving the test suite at https://github.com/ethereum/cpp-ethereum/tree/develop/test/unittests/performance so that more opcodes and precompiles and more clients can be easily added to the suite.  The more the merrier.  The advantage of this suite is that it will work with any client with a command-line program that can interpret EVM binaries.

**Comment by winsvega** [comment]
@pirapira  status?

**Comment by pirapira** [comment]
No idea.

**Comment by winsvega** [comment]
I thought we came to the final gas price for this contract. @holiman

**Comment by holiman** [comment]
Yes, for all precompiles. I think we can close this ticket.. (?)

**Comment by pirapira** [comment]
OK.
