### ISSUE TITLE
Describe new fields in the Transaction Tests page in the wiki

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#189]
@winsvega told me that there should be some new fields added in the wiki page https://github.com/ethereum/tests/wiki/Transaction-Tests

**Comment by winsvega** [comment]
that is a pretty old wiki page. actually where is the latest ethereum cpp docs ?

**Comment by pirapira** [comment]
Here https://github.com/ethereum/cpp-ethereum/tree/develop/doc

**Comment by winsvega** [comment]
transaction tests are pretty described 
https://ethereum-tests.readthedocs.io/en/latest/test_types/transaction_tests.html
