### ISSUE TITLE
general blockchain tests

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#197]
Split blockchain test file with many test cases into separate files. 
1 test **source** file = 1 test case 
add expect section into bc source file as it is in general state tests (checking different results depending on a network) 

a blockchain test format is the same
add network field to the blockchain test defining which network it should be run on
the finale test file might have many tests. (contains test case on different networks)

TransitionNetwork tests not affected

**Comment by pirapira** [comment]
I think this issue describes multiple changes.  Please split them into different issues.

* splitting blockchaintest filler files
* adding expect section into blockchaintest fillers
* adding network field to blcokchaintest fillers

**Comment by cdetrio** [comment]
@winsvega before pushing this new format to the repo, can we resume [tagging release versions](https://github.com/ethereum/tests/releases)? A changelog for each release would be helpful too.

**Comment by pirapira** [comment]
I thought these changes are only on the filler files but not on the test files that other clients use.  @winsvega is this correct?

**Comment by winsvega** [comment]
technically yes. but some tests moved to a different folders.
