### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by guaka** [ethereum/tests#2]
MIT makes most sense

**Comment by axic** [comment]
Can anyone put in the license file? 😉

**Comment by winsvega** [comment]
@axic how this should be done?

**Comment by axic** [comment]
All (major) contributors (https://github.com/ethereum/tests/graphs/contributors) should be asked here to acknowledge. Just tag everyone here.  Seems like MIT is a good choice since there is already some agreement above.

**Comment by winsvega** [comment]
@chriseth @chfast  @gumb0 @pirapira

**Comment by chriseth** [comment]
I'm fine with MIT for my contribution.

**Comment by pirapira** [comment]
:+1: for MIT.

**Comment by chfast** [comment]
I don't care (I will agree with any decision).

**Comment by gumb0** [comment]
I'm fine with MIT

**Comment by winsvega** [comment]
ok, what now?

**Comment by chfast** [comment]
1. Decide who the "copyright holder" is.
2. Copy the template https://opensource.org/licenses/MIT to LICENSE file.
3. Fill up the placeholders in the LICENSE file.
4. Commit & push.

**Comment by chriseth** [comment]
I think we should also get a confirmation from @CJentzsch

**Comment by CJentzsch** [comment]
I am fine with MIT

**Comment by winsvega** [comment]
hm.. I don't like this point 
`and/or sell copies of the Software`

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/323
