### ISSUE TITLE
General State Tests contain transactions with invalid encoding

### ISSUE THREAD

**Issue by fjl** [ethereum/tests#203]
The transaction value field should use RPC quantity encoding.

Specifically, 

* `0x` should not be used to encode numeric values. Please use `0x0` to encode tx value zero.
* For non-zero value, the field should not contain leading zero digits after `0x`.

Other fields should use RPC data encoding. Hex data should have `0x` prefix, it's missing for transaction input data in `stRevertTest/RevertDepthCreateAddressCollision.json` and a few other files.

**Comment by winsvega** [comment]
We must come to a standart describing  hashes, hex encodings of bytes and integers in the .json tests. 
as well as the length and leading zeroes. (0x0 vs 0x00 and   0x00000001   values)

**Comment by winsvega** [comment]
@pirapira  what is the current state of .json encoding.
I was trying to keep an EIP but we end up in a state we are currently are. 

So it looks like this 
```
every field value is starting with `0x` prefix except information comment fields.
if address is a key in json it is also prefixed with `0x`
if address is in transaction `to`  it is also prefixed with `0x`
"extraData" : ""   code and data fields might be empty
zero value is  "0x00"
```

**Comment by pirapira** [comment]
I think we can make @jwasinger 's syntax checker stricter and stricter.  Then we'll hear opinions.

**Comment by winsvega** [comment]
Current state: 

All fields in tests are 0x prefixed hex. (with exception of blocknumber field in bc tests and srcHash in _info section)
code/data/input/extraData fields are "0x" if empty, 0xbytes if not. 
0 values are 0x00
no leading 00 seen.
