### ISSUE TITLE
Test files should contain chainParams

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#205]
Currently, the chain params information is not included in the test files.  However, since different directories use different chain params, this information should be present in the test files.

By chain params, I mean this kind of parameters:
```
{
		"accountStartNonce": "0x00",
		"homsteadForkBlock": "0x00",
		"EIP150ForkBlock": "0x00",
		"EIP158ForkBlock": "0x0a",
		"metropolisForkBlock": "0xfffffffffffffff",
		"chainID": "0x03",
		"maximumExtraDataSize": "0x20",
		"tieBreakingGas": false,
		"minGasLimit": "0x1388",
		"maxGasLimit": "7fffffffffffffff",
		"gasLimitBoundDivisor": "0x0400",
		"minimumDifficulty": "0x020000",
		"difficultyBoundDivisor": "0x0800",
		"durationLimit": "0x0d",
		"blockReward": "0x4563918244F40000",
		"networkID" : "0x03"
}
```

@fjl pointed this out to me.

**Comment by pirapira** [comment]
Currently go-ethereum hard-codes these numbers.  https://github.com/ethereum/go-ethereum/blob/225de7ca0a9e861696a5a43b666090b574c4c769/tests/block_test.go#L41

**Comment by winsvega** [comment]
we have network identificators for that. we just have to agree which params correspond to 
Frontier, Homestead, EIP150, EIP158, Metropolis   and so on network names from the tests.
(BlockchainTests and GeneralStateTests)

Transaction tests by default use mainnetwork params and have a blocknumber.

**Comment by pirapira** [comment]
@winsvega are you suggesting that it should be possible to erase the hard-coded block numbers from the go-ethereum codebase?

**Comment by winsvega** [comment]
I mean we could like add a chainParams.json file somewhere in the test repo
and clone cpp configs into it. then each test should have like a "network" field

**Comment by winsvega** [comment]
well tests could contain chain params. 
the issue is that every client has it's own chain params scheme

**Comment by winsvega** [comment]
Chain params are configurable by retesteth and I am looking foward to implement more flexibility in its configuration
