### ISSUE TITLE
Unused field "previousHash"

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#206]
Many GeneralStateTest filler files and VMTest filler files contain `previousHash` field.  However, this field is never used in the cpp-client.  The unused field should be removed.

@fjl pointed this out to me.

@winsvega do you have an idea why `previousHash` exists in the fillers?

**Comment by pirapira** [comment]
@winsvega also told me this field is not used anymore.

**Comment by winsvega** [comment]
need to check if it is still present in some tests or not and remove it if it does

**Comment by winsvega** [comment]
@pirapira  I guess there are no such fields anymore

**Comment by pirapira** [comment]
That's right.
