### ISSUE TITLE
GeneralStateTest `RevertDepthCreateAddressCollision` fails in Hive with go-ethereum

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#223]
See https://github.com/ethereum/go-ethereum/issues/14756 for the phenomenon.

**Comment by pirapira** [comment]
Now `ethereum/tests` should have been fixed.

The next step is to try to un-skip this test in go-ethereum.

**Comment by winsvega** [comment]
I am  updating the tests now.

**Comment by winsvega** [comment]
@holiman  does this test still fails on hive?

**Comment by holiman** [comment]
This does not fail in hive for geth.
