### ISSUE TITLE
codesizeOOGInvalidSize_d0g0v0_Frontier fails for go-ethereum in hive

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#224]
http://hivetests.ethstats.net/#displayLog=artefacts/20170705_054621-go-ethereum%3Amaster/client-598b70b7.log

**Comment by pirapira** [comment]
In go-ethereum, the balance of the transaction sender does not even decrease.  Maybe the transaction is signed using EIP155 style replay protection.

**Comment by pirapira** [comment]
No, that cannot be, because it works fine for EIP150 and EIP158.

**Comment by pirapira** [comment]
It turns out go-ethereum applies the max code size rule for all blocks.

**Comment by winsvega** [comment]
@holiman  I guess this one is fixed on go. cpp and geth are on consensus on this one.

**Comment by holiman** [comment]
Yeah, can be closed due to https://github.com/ethereum/go-ethereum/pull/15072
