### ISSUE TITLE
Test cases (or fillers) can contain the related EIPs as metadata

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#225]
Senthil asked me how to look up the test cases related to a particular EIP, but I could not answer.  Is it a good idea to include the related EIPs as metadata in the test cases?

**Comment by holgerd77** [comment]
At least this is a question which comes up again and again (``ethereumjs-vm``development perspective).

**Comment by winsvega** [comment]
we should fill this form in the test fillers to resolve such question.
https://github.com/ethereum/tests/issues/183

the issue is that usually we don't bother filling up the description field for a test case...

**Comment by winsvega** [comment]
moved to https://github.com/ethereum/tests/issues/332
