### ISSUE TITLE
stTransactionTest/OverflowGasRequire\.json` // gasLimit > 256 bits

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#227]
go-ethereum:master   tests/state_test.go has the following line
```
	st.skipLoad(`^stTransactionTest/OverflowGasRequire\.json`) // gasLimit > 256 bits
```

This issue keeps track of fixing the test or anything until this line can be removed.

**Comment by pirapira** [comment]
#240 has to be fixed first.

**Comment by pirapira** [comment]
Formatwise, gasLimit can be of arbitrary length.  However, if there is an upper limit for the gasLimit's value, maybe limiting the length altogether is not a bad idea.

**Comment by pirapira** [comment]
OK, the block's gasLimit sets the upper limit.  What is the largest possible value of the block's `gasLimit`?

**Comment by pirapira** [comment]
There is not limit either on a block's gas limit.  So this theoretically remains a problem.

**Comment by winsvega** [comment]
the max block gasLimit is set to 2^63-1
any other blocks are considered to be invalid. thus any state test with block gas limit > 2**63-1  is invalid state test and should be corrected.

blockchain tests however could have a larger block gas limit for testing purposes. such tests should represent such block as invalid and only print its rlp.  (if only rlp of a block is printed in the .json the block is considered to have an error)

**Comment by winsvega** [comment]
ok. so that test
`st.skipLoad(`^stTransactionTest/OverflowGasRequire\.json`) `

assumes that transaction will be invalid and this wont be executed. so the post state should stay the same. it is kind of a transaction test that is being implemented as a blockchain test

**Comment by winsvega** [comment]
should be fixed with retesteth as every transaction is being send via rpc.

**Comment by winsvega** [comment]
moved to https://github.com/ethereum/tests/blob/develop/src/BlockchainTestsFiller/ValidBlocks/bcStateTests/OverflowGasRequireFiller.json

should be changed to check that the transaction is actually rejected with an error code.
