### ISSUE TITLE
stCallCreateCallCodeTest/createJS_ExampleContract\.json`, "bug in test"

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#229]
go-ethereum:master   tests/state_test.go contains a line
```
	st.fails(`^stCallCreateCallCodeTest/createJS_ExampleContract\.json`, "bug in test")
```

This PR keeps track of fixing the test and anything until this line is removed.

**Comment by fjl** [comment]
It seems to be fixed now.

**Comment by pirapira** [comment]
Thank you.
