### ISSUE TITLE
codesizeOOGInvalidSize_d0g0v0_EIP158 fails on hive on Parity:master

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#234]
As seen in Log permalink: http://hivetests.ethstats.net/#displayLog=artefacts/20170704_212723-parity%3Amaster/client-c9099087.log, the codesizeOOGInvalidSize_d0g0v0_EIP158 test fails on hive on `Parity:master`.

**Comment by winsvega** [comment]
updating the tests now. last time hive tests were updated was like a month ago.
I think it is good to run  --filltests --fillchain  each time we update a state test. so it will be updated both for develop and hive. adding a blockchain tests check for a tests generated from state tests would force this approach. 

it might add 10 minutes to the test run on hive though

**Comment by pirapira** [comment]
The failure is still visible as of now.

**Comment by winsvega** [comment]
I saw Parity provided 0 errors on Hive

**Comment by pirapira** [comment]
OK.
