### ISSUE TITLE
Wrong EXTCODECOPY test

### ISSUE THREAD

**Issue by feliam** [ethereum/tests#235]
The following test checks for a new fffffffffffffffff account created at the end but no CREATE instruction in it. Right? (vmInputLimitsLight.json) 

    "12a1f52c36a8dae436b0d2d354614b5c30deb77a7d104cbf22f6b8ef8c42429c" : {
        "callcreates" : [
        ],
        "env" : {
            "currentCoinbase" : "2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
            "currentDifficulty" : "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
            "currentGasLimit" : "0xe8d4a51000",
            "currentNumber" : "0x012c",
            "currentTimestamp" : "0x02",
            "previousHash" : "5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6"
        },
        "exec" : {
            "address" : "0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6",
            "caller" : "cd1722f3947def4cf144679da39c4c32bdc35681",
            "code" : "0x6000740100000000000000000000000000000000000000007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff73ffffffffffffffffffffffffffffffffffffffff3c",
            "data" : "0x",
            "gas" : "0xe8d4a51000",
            "gasPrice" : "0x01",
            "origin" : "cd1722f3947def4cf144679da39c4c32bdc35681",
            "value" : "0xe8d4a51000"
        },
        "gas" : "0xe8d4a50fe0",
        "logs" : [
        ],
        "out" : "0x",
        "post" : {
            "0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6" : {
                "balance" : "0x0de0b6b3a7640000",
                "code" : "0x6000740100000000000000000000000000000000000000007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff73ffffffffffffffffffffffffffffffffffffffff3c",
                "nonce" : "0x00",
                "storage" : {
                }
            },
            "ffffffffffffffffffffffffffffffffffffffff" : {
                "balance" : "0x00",
                "code" : "0x",
                "nonce" : "0x00",
                "storage" : {
                }
            }
        },
        "pre" : {
            "0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6" : {
                "balance" : "0x0de0b6b3a7640000",
                "code" : "0x6000740100000000000000000000000000000000000000007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff73ffffffffffffffffffffffffffffffffffffffff3c",
                "nonce" : "0x00",
                "storage" : {
                }
            }
        }
    },

**Comment by pirapira** [comment]
Which file is this from?

**Comment by feliam** [comment]
$ grep 12a1f52c36a8dae436b0d2d354614b5c30deb77a7d104cbf22f6b8ef8c42429c . -Rn
./vmInputLimitsLight.json:27344:    "12a1f52c36a8dae436b0d2d354614b5c30deb77a7d104cbf22f6b8ef8c42429c" : {
./vmInputLimits.json:104523:    "12a1f52c36a8dae436b0d2d354614b5c30deb77a7d104cbf22f6b8ef8c42429c" : {

**Comment by pirapira** [comment]
I think `testeth` should detect this https://github.com/ethereum/cpp-ethereum/issues/4281.  And then we will need to fix the violating tests including this one.

**Comment by rtkaczyk** [comment]
EXTCODECOPY may create new accounts in these tests. [More details here](https://github.com/ethereum/cpp-ethereum/issues/4281#issuecomment-319312644).

**Comment by winsvega** [comment]
added some tests around it https://github.com/ethereum/tests/pull/329
the related issue is probably about VMTests only.
