### ISSUE TITLE
LOGS are too huge

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#239]
revently revived logs for the state tests produce test files with over 50MB size 
unable to commit such files to github and it is too much for a test file.

**Comment by pirapira** [comment]
By logs, do you mean logged events by `LOG0, LOG1, LOG2, LOG3, LOG4` instructions, or something else?

**Comment by winsvega** [comment]
by logs I mean this section
https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stLogTests/log3_MaxTopic.json#L26

**Comment by pirapira** [comment]
@fjl  is it OK if we make the `logs` field optional in the GeneralStateTest?

@winsvega So, in this bigger-than-50MB, how much bytes are spent for `logs`?  More than half?

**Comment by winsvega** [comment]
48mb in some cases. (in random state tests)

**Comment by fjl** [comment]
Sorry ;)

We can also include hash of logs.

**Comment by pirapira** [comment]
This can be closed now.
