### ISSUE TITLE
go-ethereum fails walletReorganizeOwners_EIP158 test

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#240]
When I update `ethereum/tests` in `go-ethereum:master`, I [get](https://travis-ci.org/pirapira/go-ethereum/jobs/260625267) the following error (among many others):

```
        --- FAIL: TestBlockchain/bcWalletTest/walletReorganizeOwners.json/walletReorganizeOwners_EIP158 (0.01s)

        	block_test.go:78: Block #1 insertion into chain failed: invalid gas used (remote: 1225063 local: 1193023)
```

**Comment by winsvega** [comment]
this wallet test is a tricky one. it has a solidity contract and 200+ blocks. did it failed to insert the first block? 
need to check that geth uses the latest update.  however on EIP158 there should be no change.

**Comment by pirapira** [comment]
Thank you for pointing that out it's a difficult one.  In that case, I move on to the next error.  There are many easier bugs and when I fix them, this one might disappear.

**Comment by pirapira** [comment]
Now I cannot reproduce this anymore.
