### ISSUE TITLE
There should be a GeneralStateTest where a contract's init code does SSTORE

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#242]
When I made [a mistake](https://github.com/ethereum/cpp-ethereum/commit/14a42be5f025ccfe4b03ab19eea3097642ccf0ec) clearing the storage after the init code execution, only those test cases about address collision cases failed.

There should be more test cases performing SSTORE in the contract init code.

**Comment by winsvega** [comment]
there is indirect sstore in init code:

https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stCreateTest/CREATE_ContractSuicideDuringInitFiller.json#L72

it calls to a contract in init code so it to make a SSTORE operation.

**Comment by pirapira** [comment]
Thank you.  Let me investigate why my mistake (linked above) didn't cause a failure there.

**Comment by pirapira** [comment]
Ah, the SSTORE must be in the account where the init code runs.
