### ISSUE TITLE
filled tests should note lllc version

### ISSUE THREAD

**Issue by cdetrio** [ethereum/tests#257]
Filled tests have some metadata noting which cpp-ethereum version was used to fill them, for [example](https://github.com/ethereum/tests/blob/74431cab7b8e8a0ccf457ad2fbc4b25f6c3e1f7f/GeneralStateTests/stReturnDataTest/returndatacopy_following_revert.json#L5):
```
{
    "returndatacopy_following_revert" : {
        "_info" : {
            "comment" : "",
            "filledwith" : "cpp-1.3.0+commit.3289fb73.Linux.g++",
            "source" : "/src/GeneralStateTestsFiller/stReturnDataTest/returndatacopy_following_revertFiller.json"
        },
```

However, the [filler file](https://github.com/ethereum/tests/blob/74431cab7b8e8a0ccf457ad2fbc4b25f6c3e1f7f/src/GeneralStateTestsFiller/stReturnDataTest/returndatacopy_following_revertFiller.json#L51) contains LLL code, and the code is compiled with some installed version of `lllc`. The test metadata should note which version of `lllc` was used to compile the LLL code.

**Comment by winsvega** [comment]
https://github.com/ethereum/cpp-ethereum/pull/4490
