### ISSUE TITLE
Remove expectExceptions from futureUncleTimestampDifficultyDrop2Filler.json 

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#270]
If we specify the correct state roots, `expectException` fields in `futureUncleTimestampDifficultyDrop2Filler.json ` should not be necessary.

See https://github.com/ethereum/tests/pull/269#discussion_r134722457

**Comment by pirapira** [comment]
Also
* [x] uncleBloomNot0_2Filler.json 
* [x] uncleHeaderAtBlock2MetropolisFiller.json

**Comment by winsvega** [comment]
the thing is that state root might be different on different forks.  (before and after metropolis)
tho fix that I created a copy. 1 copy passes the block before metropolis and fails on metropolis. 2 copy only on metropolis but fails on other forks.

**Comment by pirapira** [comment]
This has been done on `eip649` branch.
