### ISSUE TITLE
Move test documentation files to this repo / own hosting (ReadTheDocs)

### ISSUE THREAD

**Issue by holgerd77** [ethereum/tests#272]
The [test documentation](http://www.ethdocs.org/en/latest/contracts-and-transactions/ethereum-tests/index.html) feels somewhat misplaced in the generic Homestead docs being too detailed for the end user/dapp dev and also being too hidden in the tree structure there.

Placing the documentation files directly here in a ``docs`` folder and hosting it separately (probably also on ReadTheDocs) from the Homestead docs would greatly encourage pull requests for documentation updates and enhancements and - that would be my hope - significantly improve documentation quality. Atm this "feels" too far away and very few people find the way over to make a pull for a subfolder file in the homestead docs repo.

If there is interest/support for this change, I could do the preparations for it.

**Comment by pirapira** [comment]
I think it's a good idea to equip `ethereum/tests` with its own documentation.

**Comment by holgerd77** [comment]
@pirapira What I stumbled upon when experimenting with it: do you guys accept non-rebased PRs?

Background: I'm just cloning the repo and realized just how big it is. If people have to actually clone it locally to do a rebase on a previously made PR on doc changes, then not much is actually won since this is taking too much time. Without the need for rebase doc changes can just be done with the GitHub markdown editor directly online in ones fork, so this would be a practical solution.

**Comment by pirapira** [comment]
We don't strictly require rebases.  You can see many branches running parallel in the hisotry. Still, when there are conflicts I say "please rebase" instead of "please merge develop".  It helps `git bisect` easier.

Regarding the size of the repo, [git clone --depth 1](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt) might help.

**Comment by holgerd77** [comment]
@pirapira Yes, that helped, thank you.
