### ISSUE TITLE
Doesn't mention using lllc or running with a docker file

### ISSUE THREAD

**Issue by jamesray1** [ethereum/tests#298]
So searching for lll or docker on https://ethereum-tests.readthedocs.io/en/latest/index.html yields no results. So it seems that the documentation doesn't mention using lllc, testrpc, or running with a docker file. Is this something that should be added?

**Comment by pirapira** [comment]
* `lllc`: yes, when we document the filler files.  The filled tests do not contain LLL.
* docker: maybe not because that's about a specific client
* testrpc: maybe not because that's about a specific client
