### ISSUE TITLE
 test/testeth -t BlockchainTests -- --singletest BadStateRootTxBC --filltests errors

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#305]
On `cpp-ethereum:0b2b4ec20a96a9b476e5a09c870f9eaeb36b7cb9` and `tests:c4f7cb47a01f4be98ec4685b97380b0a4c54f7ec`, I see an error
```
$ ETHEREUM_TEST_PATH='../../tests' test/testeth -t BlockchainTests -- --singletest BadStateRootTxBC --filltests 
Running 14 test cases...
Test Case "bcStateTests":
14%...
.
.
.
.
.
.
.
.
.
/home/yh/src/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(475): error: in "BlockchainTests/bcStateTests": BadStateRootTxBC_Byzantium Check State: a94f5374fce5edbc8e2a8697c15331677e6ebf0b: incorrect balance 1976363, expected 1975583
BadStateRootTxBC_Byzantium
.
```

**Comment by pirapira** [comment]
Similar errors appear for
* `blockhashTests_Byzantium`
* `OOGStateCopyContainingDeletedContract_Byzantium`
* `multimpleBalanceInstruction_Byzantium`
* ... (still running testeth)

**Comment by pirapira** [comment]
cpp-ethereum:84b2e6404862657b5c73f8a7b245042e0f0e4730 is the first commit with the error on BadStateRootTxBC.  It makes sense, so the filler should be modified.

**Comment by winsvega** [comment]
so is this gas change expected ? 
if so then we could change expect section in the filler and this error will disappear. 
otherwise we should investigate the cause

**Comment by pirapira** [comment]
Yes, expected.

**Comment by winsvega** [comment]
@pirapira  is this issue resolved?

**Comment by pirapira** [comment]
I will try the command again to see if the error has disappeared.

**Comment by pirapira** [comment]
I don't see this problem anymore.
