### ISSUE TITLE
Replace LLL/Solidity source code with Yul

### ISSUE THREAD

**Issue by axic** [ethereum/tests#306]
Benefit:
- lower level code than LLL/Solidity, but still more readable than LLL
- as a result it should be more easy to audit

**Comment by winsvega** [comment]
I suggest to keep lllc support and implement julia as an option

**Comment by axic** [comment]
What is the main benefit having LLL and Solidity?

Apart from the potential that it has less bugs than Julia, but the main point of Julia is to be small and auditable and the output easily verifiable (when compared to the other two).

**Comment by winsvega** [comment]
It is not about the benefits. It is about that we already have a lot of tests in LLL

**Comment by axic** [comment]
It still can be a goal to eventually replace those old ones.

**Comment by pirapira** [comment]
I find a subset of LLL much more intuitive than Julia or any language with variables. I don't like lllc because writing a compiler in C++ sounds weird.

**Comment by axic** [comment]
One doesn't need to use variables are higher level features of Julia (or not even Julia, just plain Solidity assembly).

The main reason compared to a new language for Solidity assembly/Julia is that a compiler exists for it.

**Comment by veox** [comment]
FTR (from https://github.com/ethereum/solidity/issues/1230#issuecomment-559116361):

> From call: @axic is working on standardizing some assembler language for tests, and after that remove LLL.

**Comment by winsvega** [comment]
Is yul a good option now?

**Comment by axic** [comment]
Depends. Yul doesn't give you access to some low-level opcodes (e.g `JUMP`, `PC`) but provides other constructors to achieve them (such as functions).

**Comment by winsvega** [comment]
added solidity support. as I understand solc has yul parser ?

**Comment by qbzzt** [comment]
> Depends. Yul doesn't give you access to some low-level opcodes (e.g `JUMP`, `PC`) but provides other constructors to achieve them (such as functions).

Neither does LLL. In those cases we just write `code: :raw 0x<whatever>` and put the assembler version in comments.

**Comment by winsvega** [comment]
actually if YUL is supported by solc  then it is already implemented

**Comment by qbzzt** [comment]
> actually if YUL is supported by solc then it is already implemented

It is implemented, but it isn't user friendly. Lets say I want to check `sstore(1,1)`. I need to put this code in the `solidity:` section:

```

  solidity: |
      contract Yul {
        function val2Storage() public
        {
          assembly {
            sstore(1,1)
          }
        }   // function val2Storage
      }     // contract Yul
```

Four lines of prefix and three lines of postfix to be able to use Yul. If we want to encourage people to use it, it needs to be easy. For example, imagine this structure:

```
    cccccccccccccccccccccccccccccccccccccccc:
      balance: '0x0ba1a9ce0ba1a9ce'
      code: |            
        yul(uint256 a, uint256 b) {
           sstore(a, b)
        }
      nonce: '0'
      storage: {}
```

Then retesteth can add all the necessary syntax to create the actual Solidity code, with the address in the contract name:
```
  solidity: |
      contract addr_ccc...ccc {
        function yul(uint256 a, uint256 b) public
        {
          assembly {
            sstore(a, b)
          }
        }   // function yul
      }     // contract addr_ccc...ccc
```

The contract name is irrelevant, because we connect it to the address in retesteth. The name of the function and its parameters are specified by the test author, so they'll know to use `data: :abi yul(uint256,uint256) 5 6` in the transaction.

**Comment by axic** [comment]
You do not need to use inline assembly to access Yul in the compiler. I'm not sure what you are using, the CLI or standard json, but there are options to invoke the assembler and pass Yul code directly.

**Comment by axic** [comment]
(Julia was renamed Yul years ago. Changed title to reflect that.)

**Comment by winsvega** [comment]
> You do not need to use inline assembly to access Yul in the compiler. I'm not sure what you are using, the CLI or standard json, but there are options to invoke the assembler and pass Yul code directly.

We use solc.

**Comment by axic** [comment]
You can use `solc --assemble <file.yul>` where `file.yul` is a simple block (can also use functions):
```
{
  function f(a, b) -> c {
    c := add(a, b)
  }

  mstore(0, f(1, 2))
  return(0, 32)
}
```

**Comment by qbzzt** [comment]
I vote we add Yul support. The reason is LLL is no longer updated, and eventually we'll have new opcodes. It isn't a problem with EIP 2315 (https://eips.ethereum.org/EIPS/eip-2315) because flow control isn't something we test in lll anyway, we test it in machine language. But when a new calculation opcode comes around we'll want Yul. Might as well get used to it already.

**Comment by qbzzt** [comment]
BTW, this is a retesteth issue really. Shall I open an issue there?

**Comment by axic** [comment]
![Screenshot](https://user-images.githubusercontent.com/20340/112179121-4de2fc80-8bf2-11eb-8283-b76efe7b3fcd.png)

You can also click on `transfer issue` if you think it belongs there, but I think it actually belongs to both, as the testing format may require a change, such as a language field?

**Comment by qbzzt** [comment]
> You can also click on `transfer issue` if you think it belongs there, but I think it actually belongs to both, as the testing format may require a change, such as a language field?

I don't think we need a breaking change, any more than we needed one for Solidity (https://ethereum-tests.readthedocs.io/en/latest/state-transition-tutorial.html#solidity-tests). We might want to do something like:

```
ccc...ccccc:
        nonce: 1
        code: |
            :yul
             <Yul code goes here>
        storage: {}
```


With LLL code it always looks like this:
```
ccc...ccccc:
        nonce: 1
        code: |
            {
                 <LLL code goes here, {} are required even if it is just one command>
            }
        storage: {}
```

**Comment by winsvega** [comment]
A yul would actually be a downside as we don't know how to add new opcode to it.

**Comment by qbzzt** [comment]
> A yul would actually be a downside as we don't know how to add new opcode to it.

1. Do you know how to add opcodes to LLL?
2. Yul is still in active development, so I assume we won't have to add opcodes to it.

**Comment by winsvega** [comment]
Yes. We have custom repo of solidity whete we add any required opcode to lll.

**Comment by winsvega** [comment]
added YUL support: 

https://github.com/ethereum/tests/pull/819/commits/dd6b122dddf07f5f0372bd3a7935da0f106a6665#diff-b66d7b0a699eddd78aaf5f8b2d9e35ee24b71aa255f14d7c6d3f80a37ff7d9e8R34
