### ISSUE TITLE
TESTS. Caller account does not exists in pre/posts

### ISSUE THREAD

**Issue by feliam** [ethereum/tests#317]
As this is a transaction. Should not it have the caller account in both pre/post to show that the balance of both the accounts change?
https://github.com/ethereum/tests/blob/develop/VMTests/vmArithmeticTest/add0.json

**Comment by pirapira** [comment]
I doubt VM tests contain transactions.  I can have a look how it is in a few weeks.

**Comment by winsvega** [comment]
btw we have a test for caller transaction from an account that does not exist in a state. 
https://github.com/ethereum/tests/blob/develop/src/BlockchainTestsFiller/bcStateTests/transactionFromNotExistingAccountFiller.json

such thing could occur with gasPrice = 0.
