### ISSUE TITLE
Introduce BlockchainTests without mining

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#325]
https://github.com/ethereum/tests/issues/318#issuecomment-330183221

> yes. so lets say if blockchaintest.json has "sealEngine" : "NoProof" then difficulty should not be calculated.
> if .json has "sealEngine" : "Ethash" then it works as usual.
> if .json has no "sealEngine" field then it should fail as the test is outdated

**Comment by winsvega** [comment]
so @holiman  said that having such a blockchain tests will require other clients to disable consensus critical  part of the code. and Hive is designed to be a black box tester providing tests as if it was on a real network. 
it was agreed to optimize cpp blockchain tests generation instead and keep blockchain tests mining on the lowest allowed difficulty.
