### ISSUE TITLE
Hi all, how can I use the .json file or this project to test a go-ethereum client, need help!

### ISSUE THREAD

**Issue by Max-Pano** [ethereum/tests#351]
I have read the docs of this project and I can't figure out how to use it to test a go-ethereum.
Maybe because I'm not familiar with .json or something, but I really appreciate some information or a little guide.
Thanks a lot, guys!!.
I really want to know and try out this, beyond this I only know a test framework called "[blockbench](https://github.com/ooibc88/blockbench)", which has some problem when testing a eth client 😄😄😄😄😄😄

**Comment by winsvega** [comment]
so recently geth team added an option to evm binary which allows to execute a custom GeneralStateTest.json file. 

``` evm statetest <file> ```

You could generate state test .json files using testeth
