### ISSUE TITLE
Some improvements on call_ecrec_success_empty_then_returndatasize

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#364]
The test call_ecrec_success_empty_then-returndatasize has some possible improvements.

* the prestate can contain non-zero values in the storage.  This way, it's clear that zero is written to the storage.
* the expectations can be writtten in the filler.

https://github.com/ethereum/tests/pull/362/files#diff-14fa7f288ed243634d91b202f38c67df

**Comment by winsvega** [comment]
could this issue be resolved and closed now?

**Comment by winsvega** [comment]
@qbzzt ori need to review the test and possibly extend the cases
