### ISSUE TITLE
Consider using YAML for the test sources

### ISSUE THREAD

**Issue by axic** [ethereum/tests#369]
As discussed at Devcon with @winsvega this would eliminate the problem of new lines for test source codes (i.e. for LLL and Solidity) and likely would make the sources way more readable than now.

The generated test cases would still be in JSON not to break compatibility for the clients, but that part must be machine readable, while the YAML would be for humans writing the test cases.

**Comment by winsvega** [comment]
This one?

http://yaml.org/
https://github.com/jbeder/yaml-cpp/
https://github.com/jbeder/yaml-cpp/wiki/How-To-Parse-A-Document-(Old-API)

**Comment by winsvega** [comment]
So this is entangled with converting LLL into Julia. 
One thing to keep in mind is that we already have a dependency on two different Json packages in cpp.
And now adding a third one on Yaml...
@chfast I guess would recommend against it.
@pirapira ?

**Comment by chfast** [comment]
I'm not against it. I like YAML.

yaml-cpp is in transition from Boost based one (v0.5.x) to C++11 based one not depending on Boost. I would like to go to the newer API straight away. Can you contact the author @jbeder ask when they are planning to release a new version?

Hunter package: https://docs.hunter.sh/en/latest/packages/pkg/yaml-cpp.html.

**Comment by winsvega** [comment]
we can't remove existing jsonspirit, though. other clients depend on tests to be .json

**Comment by pirapira** [comment]
LLL is my favorite language on EVM.

**Comment by pirapira** [comment]
YAML vs JSON.  KEVM team has already invested efforts to parse and print JSON.  They cannot parse YAML at all.  Isn't it the case more languages have JSON libraries?

**Comment by pirapira** [comment]
I believe there should be many tools that can convert test sources into final test cases.  So, the format should be accessible in more programming languages.

**Comment by axic** [comment]
The test outputs should remain unchanged and in JSON. This issue is about the sources used for test generation, which could be YAML to improve the ability to source test case sources (LLL, Solidity, Julia, .etc) intact with new lines and formatting.

**Comment by pirapira** [comment]
@axic yes, I understand this.  I think we should try to generate test cases not by C++ but by KEVM.

**Comment by winsvega** [comment]
no comments in yaml multiline string (
https://stackoverflow.com/questions/20890445/yaml-comments-in-multi-line-strings
however if julya code itself could have comments I think this is not an issue
the issue is that yaml does not use tab.

**Comment by jwasinger** [comment]
So the idea is that we would try to support yaml as an option for writing test fillers?  Or are we intending to migrate existing test fillers to yaml as well?

**Comment by jwasinger** [comment]
I assume that because yaml is a superset of json (and we are probably not using yaml specific features?), we can still use json schema to lint the yaml fillers by converting fillers to json before running them through the linter.

**Comment by ehildenb** [comment]
Is YAML format indentation sensitive? If it's not, we probably can make KEVM parse YAML directly. If it is indentation sensitive, the current K parser probably can't handle it.

**Comment by pirapira** [comment]
It is indentation sensitive.  http://yaml.org/spec/1.2/spec.html See "Example 2.16.  Indentation determines scope"

**Comment by pirapira** [comment]
But I guess YAML->JSON conversion is reliable enough.

**Comment by axic** [comment]
Note: YAML is a superset of JSON. If we don't use YAML specific features it will be bidirectionally convertible without loss though.

Also here's an interactive tool: https://www.json2yaml.com

**Comment by winsvega** [comment]
the easiest way from the code perspective would be to just convert yaml source into json before running testeth logic on it. 
eventually when we disable LLLC most test sources would be rewritten anyway. so why not to rewrite it in yaml. we just have to devide which yaml structure to use in test files. 

hmm. let me try the tool
ok. it's a bit different from my format. we still have to change the code string field.

@axic  is there a way to read the node  name in yaml? 
if could only get a node by name. like  node['nodename']
but if I only get the reference of a node. there are no methods to get it's name.
thats why I use 
```name: testname```

**Comment by axic** [comment]
> is there a way to read the node name in yaml?

That should be up entirely to the YAML library you are using.

**Comment by pirapira** [comment]
@axic Is YAML really a superset of JSON?   In JSON you can distinguish `gas: -1` (an integer) and `gas: "-1"` (a string).  Can you do that in YAML?

**Comment by axic** [comment]
@pirapira you can make it a quoted string, `'-1'` or `"-1"`.

**Comment by pirapira** [comment]
@axic that should solve the problem here https://github.com/ethereum/cpp-ethereum/pull/4698#discussion_r157506109

**Comment by chfast** [comment]
@pirapira YAML has types. `hello` is string, `"hello"` is string, `123423544256436534` is integer, `"123423544256436534"` is string.

This is the reason we have to write `xcode: "9.0"` not `xcode: 9.0` in https://github.com/ethereum/cpp-ethereum/blob/develop/circle.yml#L160.

**Comment by pirapira** [comment]
@chfast I see. So there should be no good reason to accept strings for integer fields suddenly in  https://github.com/ethereum/cpp-ethereum/pull/4698#discussion_r157470718

**Comment by chfast** [comment]
I'm not sure it helps @pirapira, but YAML supports arbitrary precision integers so we can also get rid of hexing numbers there. However, I'm not sure if and how implementations supports this.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/issues/385
