### ISSUE TITLE
RPC Test fails

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#377]
With cpp-ethereum 8f8cdc8b1a33b6b2ef1947ef4bab7c9b241269fe, and tests 262da2df5f4038790aa857ce61b9694a647de4d5, I get the following errors during RPC test

```
[12:03] yh@sri: ~/src/tests/RPCTests(document-rpc-test|…)$ node ./main.js ~/src/cpp-ethereum/build/eth/eth
TEST_newAccount OK
TEST_addPeerOnNode2 OK
TEST_getPeerCountOnNode1 OK
TEST_mineBlockOnNode1 FAILED
TEST_mineBlockOnNode1 FAILED
TEST_getBlockHashOnNode2 OK
TEST_mineBlockOnNode2 FAILED
TEST_mineBlockOnNode2 FAILED
TEST_getBlockHashOnNode1 OK
```

A relevant conversation https://github.com/ethereum/tests/pull/376#issuecomment-349799774

**Comment by winsvega** [comment]
This tests show OK if author is magically set. 
But if you run it on a fresh system then a script alone is not enough to set author. even though all flags are set for client init command.

**Comment by pirapira** [comment]
@winsvega do you know how to invoke the magic to set an author?

**Comment by winsvega** [comment]
no. it's like always being reset with 00000. 
I did event insert a commit into .cpp file about that issue.

**Comment by winsvega** [comment]
shoul be fixed now. although we don't have nightly test runs anymore...

**Comment by winsvega** [comment]
this is the issue for a script to execute tests using js test runners. 
test runners outdated and removed.
