### ISSUE TITLE
Use randomStatetest647 as basis for more RETURNDATACOPY tests

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#380]
```js
"randomStatetest647" : {
        "_info" : {
            "comment" : "Malicious bytecode found by fuzztest tool: returndatacopy(0,-1)"
        },
```

This is the only test that detects problems with RETURNDATACOPY in EVMJIT. We should have more tests like that and they should not be in "random" suite.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/761

**Comment by qbzzt** [comment]
Also https://github.com/ethereum/tests/pull/765
