### ISSUE TITLE
Test uses an invalid block gasLimit < 125000

### ISSUE THREAD

**Issue by carver** [ethereum/tests#383]
The minimum allowed `gasLimit` on a block is 125000 (according to the yellow paper):
![gas limit](https://files.gitter.im/ethereum/py-evm/7NV3/image.png)

But this test uses a `gasLimit` of `0xba96` == `47766` and expects the block to be valid: https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/stStaticCall/static_InternalCallHittingGasLimit2_d0g0v0.json#L17

The possible options are apparently:
1. The yellow paper is wrong
2. The test is wrong
3. I'm interpreting one of them incorrectly

Can anyone clarify which of these is true and why?

**Comment by hwwhww** [comment]
This PR may be related: 
Fix minGasLimit to 5000 https://github.com/ethereum/yellowpaper/pull/393

**Comment by pirapira** [comment]
I think the yellow paper is wrong just because all others say 5000.
