### ISSUE TITLE
Rename "develop" branch to "master"

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#408]

**Comment by axic** [comment]
@winsvega @pirapira any reason not to?

**Comment by pirapira** [comment]
None except laziness on my part, and those who have to change the urls to pull.

**Comment by axic** [comment]
> and those who have to change the urls to pull

You mean users as submodules? That actually refers to commit hashes - the branch name is only for convenience when running a manual pull to update the revisions.

**Comment by pirapira** [comment]
I was referring to those manual pulls.

**Comment by winsvega** [comment]
why we need to rename?

**Comment by axic** [comment]
> I was referring to those manual pulls.

Who is doing a manual pull? And if they do, wouldn't they notice that the branch has changed?

**Comment by axic** [comment]
> why we need to rename?

There is no git workflow (see http://nvie.com/posts/a-successful-git-branching-model/) used here which would require a `develop`, `release` and `master`, since there are no release made here :(

**Comment by pirapira** [comment]
@axic
> Who is doing a manual pull?

I do `git pull` on `develop` when I start a new branch on `ethereum/tests`.

**Comment by pirapira** [comment]
@axic I've never seen this workflow thing.

**Comment by pirapira** [comment]
@axic I also type `git rebase -i develop`  So branch names are part of the interface.  It's not like people never see the names of branches.

**Comment by winsvega** [comment]
also I am afraid that some scripts are configured to use develop.

**Comment by winsvega** [comment]
the develop branch is like that because we constantly develop new tests. 
now have occasional releases but it does not make sense. you must always stay update with recent develop branch.
