### ISSUE TITLE
create validation rule for expect section indices

### ISSUE THREAD

**Issue by cdetrio** [ethereum/tests#417]
Some test cases are filled to empty because their filler files are missing expect section indexes. For instance, [TransactionCollisionToEmptyButCode_d0g0v0.json](https://github.com/ethereum/tests/blob/53b5d386fa2bceeceacafa2915d5beb374794039/BlockchainTests/GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButCode_d0g0v0.json) is filled, but [TransactionCollisionToEmptyButCode_d0g0v1.json](https://github.com/ethereum/tests/blob/53b5d386fa2bceeceacafa2915d5beb374794039/BlockchainTests/GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButCode_d0g0v1.json), [TransactionCollisionToEmptyButCode_d0g1v0.json](https://github.com/ethereum/tests/blob/53b5d386fa2bceeceacafa2915d5beb374794039/BlockchainTests/GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButCode_d0g1v0.json) and [TransactionCollisionToEmptyButCode_d0g1v1.json](https://github.com/ethereum/tests/blob/53b5d386fa2bceeceacafa2915d5beb374794039/BlockchainTests/GeneralStateTests/stCreateTest/TransactionCollisionToEmptyButCode_d0g1v1.json) are all empty. This is because of missing expect section indexes in the filler file [TransactionCollisionToEmptyButCodeFiller.json](https://github.com/ethereum/tests/blob/53b5d386fa2bceeceacafa2915d5beb374794039/src/GeneralStateTestsFiller/stCreateTest/TransactionCollisionToEmptyButCodeFiller.json#L34-L36).

In the transaction section of the filler file, there are two values for `gasLimit` and two for `value`:
```
        "transaction" : {
            "data" : [
                "0x6001600155"
            ],
            "gasLimit" : [
                "600000", "54000"
            ],
            "gasPrice" : "1",
            "nonce" : "0",
            "secretKey" : "45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8",
            "to" : "",
            "value" : [
                "0", "1"
            ]
        }
```

But in the expect section:
```
        "expect" : [
	    {
                "indexes" : {
                    "data" : -1,
                    "gas" : 0,
                    "value" : 0
                },
```
Only the 0th index is specified for `gas` and `value` (in `"data" : -1`, the `-1` is a wildcard to cover all data indexes). This means that only the 0th elements of the `gasLimit` and `value` arrays in the transaction section have a matching expect section.

Test filler validation should be improved to check for matching expect section indexes, as JSON schemas if possible https://github.com/ethereum/tests/issues/204.

**Comment by winsvega** [comment]
so the testeth could do it on a filling stage. no particular need to implement in as a scheme check.

**Comment by winsvega** [comment]
fixed with latest testeth and retesteth
