### ISSUE TITLE
Max length of test file names?

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#426]
@winsvega says test names should be at most 50 characters.  I want longer names because I want to put EVM machine words in names.

**Comment by pirapira** [comment]
https://github.com/ethereum/tests/pull/421#issuecomment-370714606

> we haven't decided about the characters. As I implemented test name length restriction I found out that there are plenty of tests with long names > 60 chars.
We wanted it to be at least < 50. or even shorter.

> Long test names are inconvinient when you use --singletest option in console to select such a test for execution. And it might be that if you clone the repo git will complain about long file paths.

**Comment by pirapira** [comment]
https://github.com/ethereum/tests/pull/421#discussion_r172452712

> Anyway, the comments don't appear in the output of ls. It's easier to find a descriptive file name.

**Comment by pirapira** [comment]
I should look at the current lengths of file names, and ask if anybody is complaining about it.

**Comment by winsvega** [comment]
I guess Python client had complains about it. would it be a good idea to build a test database where we address a unique identificator for a test. like testA0012D43  and if you ask the database where are SHL case implemented it will tell you test identificators with such cases.

**Comment by pirapira** [comment]
I don't like meaningless IDs.

**Comment by pirapira** [comment]
You can keep the test names meaningful and still use the database.  That combination is better than the combination of meaningless IDs and the database.  So the database thing is another unrelated issue.  Please create another GitHub issue for the database thing.

**Comment by pirapira** [comment]
@winsvega how can I test the python client?

**Comment by winsvega** [comment]
not sure if they still have custom test tool supported. (smth like testeth for python)
well it should not really matter because we ask the clients to implement test rpc and retesteth will run the tests.

**Comment by pirapira** [comment]
Is there a shorter way to say 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff?

**Comment by pirapira** [comment]
Maybe `negative1`.  Then the test names become like `shl_negative1_1`.

**Comment by winsvega** [comment]
u256m1

**Comment by pirapira** [comment]
`u256 - 1` does not make sense because `u256` is not a number.

**Comment by winsvega** [comment]
u256maxM1 ?

**Comment by winsvega** [comment]
there are tests with similar names already

**Comment by pirapira** [comment]
@winsvega we should rename them to less cryptic names.

**Comment by pirapira** [comment]
@winsvega I cannot find any test files with 'u256' in its name.

**Comment by pirapira** [comment]
If `shl_2^256-1_1Filler.json` is fine, I can live within 50 characters.

**Comment by winsvega** [comment]
```
Transaction64Rule_d64m1Filler.json
stackOverflowM1PUSHFiller.json
Transaction64Rule_d64p1Filler.json
```

I am scared to use '^' '-' always have a feeling that at some CL or shell it wouldn't be parsed correctly.
https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

**Comment by pirapira** [comment]
https://en.wikipedia.org/wiki/Filename

`-` should be fine if it is not the first character.

`^` is not usual.

Then I go with `shl_-1_1Filler.json`

**Comment by winsvega** [comment]
I think Python team was complaining about filename length. But it was a long time ago. 
Now tests are run by Hive and testeth.
