### ISSUE TITLE
Add selfdestruct test cases

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#431]
Add these 3 test cases. They are HF independent, except for pricing. Use optimized runtime code from solidity.

```solidity
pragma solidity ^0.4.21;

contract DoubleSelfdestructTest {

    address constant B1 = 0x1;
    address constant B2 = 0x2;

    function remoteSelfdestruct() external {
        selfdestruct(B2);
    }

    function() external payable {
        this.remoteSelfdestruct();
        selfdestruct(B1);
    }
}

contract DoubleSelfdestructTest2 {

    address constant B = 0x3;

    function remoteSelfdestruct() external {
        selfdestruct(this);
    }

    function() external payable {
        this.remoteSelfdestruct();
        selfdestruct(B);
    }
}

contract DoubleSelfdestructTest3 {

    function remoteSelfdestruct() external {
        selfdestruct(this);
    }

    function() external payable {
        this.remoteSelfdestruct();
        selfdestruct(this);
    }
}
```

**Comment by pirapira** [comment]
`DoubleSelfdestructTest` seems to behave differently in {Frontier, Homestead} from in {EIP 150, etc}.

**Comment by pirapira** [comment]
Ah, maybe because `SELFDESTRUCT` got more expensive there.

**Comment by pirapira** [comment]
Solidity assumes the output is used after EIP150, so its output does not work for Homestead and Frontier.

**Comment by pirapira** [comment]
`DoubleSelfdestructTest2` behaves differently in `EIP150` only, in `testeth`.  Investigating.

**Comment by pirapira** [comment]
That was just because Solidity's output doesn't work before EIP150, adn EIP158 changed the behavior of zero-transfer.

**Comment by qbzzt** [comment]
Added in PR https://github.com/ethereum/tests/pull/764
