### ISSUE TITLE
Turn the LLL code in comments into actual use

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#433]
Currently, some test cases contain LLL code as comments, followed by bytecode.

```
"// code" : "<LLL code>"
"code" : "<bytecode>"
```

However, this should simply be
```
"code" : "<LLL code>"
```

**edit**

Sometimes, the LLL code only describes a part of the bytecode, so the result should be
```
"code" : "<bytecode (lll <LLL code>)>"
```

**Comment by winsvega** [comment]
Some tests contain lll code of bytecode that is put into lll code.

**Comment by pirapira** [comment]
@winsvega  What do you mean when you say "bytecode that is put into lll code"?  Does anybody translate bytecode into LLL?

**Comment by winsvega** [comment]
in some tests I did it like this
```
//data: "{(SSTORE 0 1)}",
data: "{(MSTORE 0 0x6001600055) CREATE (27 5 0)}"
```

**Comment by pirapira** [comment]
I see.  So the comments might be outdated.  Then, we should duplicate the test cases.  One as it is now, and the other puts the comment into actual use.

**Comment by winsvega** [comment]
what you mean?

**Comment by pirapira** [comment]
If we have a test like
```
//data: "{(SSTORE 0 1)}",
data: "{(MSTORE 0 0x6001600055) CREATE (27 5 0)}"
```

we should clone the test into two: one with
```
data: "{(SSTORE 0 1)}"
```
and the other with
```
data: "{(MSTORE 0 0x6001600055) CREATE (27 5 0)}"
```

**Comment by winsvega** [comment]
no. why? 
it was not meant to be that way.

the 
`//data: "{(SSTORE 0 1)}",`
is a source of 
`(MSTORE 0 0x6001600055)`

**Comment by pirapira** [comment]
Hmm. Isn't there an LLL feature like `(MSTORE 0 (lll (SSTORE 0 1)))`?

**Comment by winsvega** [comment]
that was before I knew about that feature

**Comment by pirapira** [comment]
So I edited the first comment of this issue.

**Comment by axic** [comment]
Were any of these old LLL cases converted?

**Comment by winsvega** [comment]
Not really. And id it would it supposed not to change anything. Right now lllc is not supported so perhaps better find a new way of writing simple bytecode instructions

**Comment by qbzzt** [comment]
> Not really. And id it would it supposed not to change anything. Right now lllc is not supported so perhaps better find a new way of writing simple bytecode instructions

Using Yul (#306) might be better for future tests, or at least some of them.

But changing the existing tests, or moving lll in comments to the code, is probably too much work to be worth doing. I think we should close this.

**Comment by winsvega** [comment]
ok. the original issue was about having some raw bytes in lll code backed up as coments in json. 
is not critical, and such cases are a few and the code is not too big to decompile anyway.
 
now we learned to write lll code inside lll code and it should be fine and nice in yml files.
