### ISSUE TITLE
Travis run in this repository should run cpp-ethereum on the test cases

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#436]
Currently, people sometimes file PRs to cpp-ethereum or testeth repository, just to see we are not breaking tests.  This is not the correct workflow.  Travis run in this repository should take care of that.

**Comment by winsvega** [comment]
A PR here running cpp build ?

**Comment by pirapira** [comment]
Yes, that's not too bad.  It doesn't take more than 20 minutes for pirapira/bamboo.

**Comment by winsvega** [comment]
like reverse test run? 
how do you set a branch

**Comment by pirapira** [comment]
In pirapira/bamboo it's always `develop`.  Here, people need to change the Travis script so `whomever/cpp-ethereum` is checked out.

**Comment by winsvega** [comment]
and if it works they merge to develop?

**Comment by pirapira** [comment]
ethereum/cpp-ethereum is like any other clients.  They can choose to update the test and implement the changes.

**Comment by winsvega** [comment]
I mean the test develop branch contains actual tests. (the most updated ones) 
if someone running testeth travis job on his own client and get is green. it does not mean it is ok to merge it into develop.

**Comment by pirapira** [comment]
Right. We'll be also reading this somebody's client.

**Comment by winsvega** [comment]
is it that you want to remove travis job from cpp repository then?

**Comment by pirapira** [comment]
No.

**Comment by winsvega** [comment]
outdated
