### ISSUE TITLE
EXTCODECOPY edge case

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#438]
Please make a separate state test out of stRandom2/randomStatetest571. This is the only test covering some edge case of EXTCODECOPY (code index is big, but truncated to size_t is 0).

**Comment by winsvega** [comment]
so as I understand the case is covered. You just want it to be more explicit and to have more tests around the same field?

**Comment by chfast** [comment]
Yes.

**Comment by winsvega** [comment]
will ``` (EXTCODECOPY  0x0945304eb96065b2a98b57a48a06ae28d285a71b5 1 0x010000000000000000000000000000000000000000 5000) ```  cover this case? 
@chfast

**Comment by chfast** [comment]
Yes, thank you.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/567/commits/f427fd33fd42234c09ffcbdffbfe2ff56cb51cf2

**Comment by qbzzt** [comment]
Solved by https://github.com/ethereum/tests/pull/761 and https://github.com/ethereum/tests/pull/765

**Comment by chfast** [comment]
Many thanks.
