### ISSUE TITLE
Make a test for contract with code size > 0x6000

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#439]
Ref: https://github.com/ethereum/evmjit/pull/172#discussion_r177112916

**Comment by axic** [comment]
It should be enabled for every hard fork before Spurious Dragon.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stCodeSizeLimit/codesizeOOGInvalidSizeFiller.json
