### ISSUE TITLE
Compare `CODESIZE` and `ADDRESS; EXTCODESIZE` in init code

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#446]
In the contract creation code, the first should return (usually) zero, and the second should return the size of the init code.  These behaviors should be tested.

**Comment by jwasinger** [comment]
@pirapira @winsvega I'll write these two cases.

**Comment by jwasinger** [comment]
My test case indicates that for cpp-ethereum `codesize` returns the size of the init code and `address extcodesize` returns 0.  https://github.com/ethereum/tests/pull/451
