### ISSUE TITLE
Remove 'callcreates' field from VM tests

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#449]
Now that VM tests should not access the world state, the field 'callcreates' should be always empty.  So we should remove the field.

Original idea: https://github.com/ethereum/tests/pull/444#issuecomment-380975726

**Comment by feliam** [comment]
Just came here to file the same thing. Remember to remove it also from the docs. (https://github.com/ethereum/tests/blob/develop/docs/test_types/vm_tests.)

**Comment by winsvega** [comment]
VMtests are moved to Legacy
cases migrated to GeneralStateTests
