### ISSUE TITLE
VMTests "logs" field not correctly documented

### ISSUE THREAD

**Issue by ldct** [ethereum/tests#452]
In the documentation at http://ethereum-tests.readthedocs.io/en/latest/test_types/vm_tests.html#the-logs-section, it is claimed that

> The logs sections is a mapping between the blooms and their corresponding logentries

However, it seems like in the actual JSON files, the logs section are just hex strings.

https://github.com/ethereum/tests/blob/develop/VMTests/vmArithmeticTest/add0.json#L30
https://github.com/ethereum/tests/blob/develop/VMTests/vmArithmeticTest/sdiv6.json#L30
https://github.com/ethereum/tests/blob/develop/VMTests/vmPerformance/loop-divadd-10M.json#L30
https://github.com/ethereum/tests/blob/develop/VMTests/vmSystemOperations/ABAcallsSuicide0.json#L36

**Comment by ldct** [comment]
@pirapira do you happen to know the cause of these? I was trying to make pyethereum run the VMTests again (it used to, but the format seems to have changed since). Similarly for #453.

**Comment by pirapira** [comment]
I don't remember any changes to the format of VM tests, so probably the document has been wrong all along.

**Comment by jjyr** [comment]
Seems related to this PR https://github.com/ethereum/cpp-ethereum/pull/4376
But I don't know how to calculate log series hash.

**Comment by holgerd77** [comment]
Closed by https://github.com/ethereum/tests/pull/516.
