### ISSUE TITLE
Some VMTests have missing `post` sections

### ISSUE THREAD

**Issue by ldct** [ethereum/tests#453]
The documentation suggests that the VMTests should have a mandatory `posts` section:

> Similarly, a set of accounts are detailed in the post portion to specify the end world state.

However, a few tests lack this section, eg https://github.com/ethereum/tests/blob/develop/VMTests/vmTests/mktx.json. I can't quite tell what the testfiller is meant to test in this case, but it doesn't look like any accounts are deleted.

**Comment by winsvega** [comment]
Vm tests are being updated to state test format
