### ISSUE TITLE
Missing div/mod by zero in state tests

### ISSUE THREAD

**Issue by axic** [ethereum/tests#459]
According to code coverage in ethereumjs-vm (https://coveralls.io/builds/16676962/source?filename=lib%2FopFns.js) the state tests are missing cases for div-by-zero, mod-by-zero and mulmod-by-zero. Apparently sdiv, smod and addmod are covered.

**Comment by winsvega** [comment]
Add test with mulmod a,b,0
https://github.com/ethereum/tests/pull/647

**Comment by winsvega** [comment]
@qbzzt check if we need more tests around this (with better commenting) 
but basically it is a vm test for opcode (x,y,z)   with different values of x,y,z  
can be done by generator script
