### ISSUE TITLE
Better knowledge of which tests need to be re-filled

### ISSUE THREAD

**Issue by ehildenb** [ethereum/tests#463]
Currently re-filling test cases takes quite a while, so they are re-filled manually instead.

It would be better if we could detect when they need to be refilled automatically, and even better if this was done by the CI server for us automatically on every PR. I would settle for a way to automatically only refill tests that need to be refilled though.

A simple solution: include (in the filled output) a hash of the original file. Check that hash before filling, and if it hasn't changed, then refill.

Another potential solution: track filled -> filler dependencies using a Makefile or the like. Have a CI server which does not wipe out the repository between test runs, so is able to track dependencies properly using timestamps. This is a bit more fragile.

This could also make an argument for reintroducing a `master` branch: devs push PRs to `develop` without filling tests, a CI server occasionally packages a release of the `develop` branch by filling tests and pushing to `master` branch.

Thoughts? @axic @pirapira @winsvega @chfast

**Comment by ehildenb** [comment]
Also note that it would be easy to enforce that tests are filled correctly with a CI server using the hashing method.

**Comment by ehildenb** [comment]
One problem with the hashing method as described above: you would have to parse the filled test JSON to find out what hash to look at. Parsing JSON is relatively slow.

Instead, could store a separate file with a list of `filledFileName: fillerHash`. Would be quicker to cycle through, and clients wouldn't have to change testing infrastructure to deal with new `fillerHash` field in filled tests.

**Comment by winsvega** [comment]
Test filling operation is dangerous. if filling went wrong - you loose the test. Thats why it is done manually. 
You have to analyze what has changed after test refill and why it has changed. Usually expect section prevents from critical damage to the test. 

You dont have to rerun the test filling process unless you want to change the test.

**Comment by ehildenb** [comment]
This proposal is just about maintaining a list of which tests have been filled with which fillers. This would make it simple for a tool to report back "these tests need to be refilled", and would also make it easy for the CI server to make sure that if fillers are changed then the tests have been refilled before merging into master.

**Comment by winsvega** [comment]
ok then we already have it.
a filled test has _info section with a path to the filler.json and a hash of that filler. 
if test source is changed then  test tool report that such test is outdated and needs to be regenerated.

**Comment by ehildenb** [comment]
Ah I see. I guess the one benefit of a separate file is it would be much quicker to run than parsing JSON, but I guess that isn't the bottleneck anyway. Closing.

**Comment by ehildenb** [comment]
@winsvega actually, reopening. If this information is already present, I think it would be useful for the CI on this repo to fail if tests need to be refilled, and to print out the list of tests which need to be refilled. What do you think?

**Comment by winsvega** [comment]
hm. usually new tests are added by running the testeth which do the checks.
a condition for the test to be added is that cpp CI run must be green (it runs testeth) but that is in cpp-repo
@jwasinger @pirapira  also suggest that testeth run should somehow be performed in the test repo. 
The CI check of the hashes here could be usefull but it is not needed that much.

**Comment by ehildenb** [comment]
I am integrating it into the (very quick) `./test.py` checks on #461 . That way it doesn't depend on other repos.

**Comment by winsvega** [comment]
One thing i dont like about current model is that one test source filler change require to regenerate all the tests that come from this filler. When you actually just want a Byzantium version to be refilled. you change the filler. and that requires you to regenerate the test for Homestead as well. 
That might lead to some information being lost. (if Homestead regenerated test will be different from the original Homestead regenerated test)

**Comment by winsvega** [comment]
I have sealed all the tests for networks <= Constantinople into LegacyTests  folder. Those tests are no longer need to be refilled. Only to execute (using retesteth -t LegacyTests)

A test must be refilled if the hash of a filler file is changed. That usually means that something in the postCondition section of the test has changed. New fork expectations added or some changes to the pre state. 

I would strictly not recommend to use any scripts to refill the tests as it is basically not needed for the clients that just want to check if they are passing the tests. To check if the client is passing the tests you could now use retesteth tool: https://github.com/ethereum/retesteth

If, however you create your own test, you would need to generate the test for your fork changes. For this automatition is not needed as you have to manually set the post condition and verify that your test (precondition -> transaction -> postCondition check) is passing everything correctly. read retesteth docs on how to write your own state test: https://github.com/ethereum/retesteth/wiki/Creating-a-State-Test-with-retesteth
