### ISSUE TITLE
Test request: CREATE failure due to deployment cost

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#473]
There is an edge case of CREATE failure where the init code finishes with a success and returns the code to be deployed. The CREATE still can fail if there is not enough gas left to deploy the code. We should have some test cases targeting this case, especially together with REVERT and RETURNDATA instructions.

Why this is important? In go-ethereum CREATE implementation returns the runtime code to be deployed and (in other cases) the returndata buffer from REVERT using the same `output` out argument. It the described case it will return the code in the `output` together with the `failure` error. The code must be discarded but might be confused with returndata if not being careful.

**Comment by chfast** [comment]
@winsvega @axic is it possible to write a test in solidity assembly?

**Comment by winsvega** [comment]
here is the test https://github.com/ethereum/tests/pull/475

**Comment by axic** [comment]
So this can be closed now?
