### ISSUE TITLE
Inconsistent behavior of storage on address collision in Constantinople

### ISSUE THREAD

**Issue by dwightguth** [ethereum/tests#492]
I have been looking into the test suite for the purposes of trying to implement the CREATE2 opcode in [KEVM](https://github.com/kframework/evm-semantics), and it seems to me that there is an inconsistency in the behavior of storage with respect to address collisions. In the stCreate2/create2collisionStorage test, it seems to be assumed that when an address collision occurs with an account that has nonempty storage, the storage in the new account is kept around. However, according to stRevertTest/RevertInCreateInInit, the storage is cleared in this case, as perceived by the gas cost in that test of the sstore instruction. I suppose we could say that the intended behavior is one thing prior to Constantinople and another thing after, but I'm hesitant to make that call on my own. Is there some piece of context I'm not understanding here that makes these tests behave this way, or is it simply a bug in one of the tests?

**Comment by winsvega** [comment]
fixed in cpp with  https://github.com/ethereum/aleth/pull/5242,  https://github.com/ethereum/aleth/pull/5237
the test is refilled.
