### ISSUE TITLE
Testcase needed for `CODECOPY` where `code_size=0`

### ISSUE THREAD

**Issue by masonforest** [ethereum/tests#493]
We at [Mana](https://github.com/poanetwork/mana) ran into a consensus breaking bug in our client at [block #116524](https://etherscan.io/block/116524). The issue was that when `code_size` was set to `0` when running the opcode `CODECOPY`  we would push a `0` onto the stack instead of leaving the state unchanged. This was a bug in our implementation and was fixed in commit https://github.com/poanetwork/mana/commit/82798080269cdd36f1714b1d3da6090c0db774d1. It may be helpful to add a test for this case for this so other new clients don’t run into the same issue in the future.

**Comment by holiman** [comment]
Looking at the fix, you mean `CODECOPY`, not `CALLCODE`, right?

**Comment by masonforest** [comment]
Whoops, yep. Updated 👍

**Comment by axic** [comment]
Can the new test case also cover `EXTCODECOPY` please?

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/569

could not really test codecopy of empty code. I've put codecopy into contract init code maybe this count.
