### ISSUE TITLE
push32FillUpInputWithZerosAtTheEnd test doesn't store anywhere

### ISSUE THREAD

**Issue by norhh** [ethereum/tests#498]
I have a query. The code for the test seems to be
`0 PUSH32 0xff10112233445566778899aabbccddeeff00112233445566778899aabbccdd`
which doesn't store anything anywhere, also tests doesn't have any stack to check the current stack(correct me if i am wrong), so in that case the test will pass right whatever happens right?

**Comment by winsvega** [comment]
It is a VM test which is unmaintained test suite. I dont see any 0 at the end. But what it does in VM suite is that it could check execgas value.

**Comment by norhh** [comment]
zeros will be appended to the end as the argument for push is less than 32 bytes in this case.We can't verify this behavior in this test right? It might be good if the stack is also stored in the tests

**Comment by winsvega** [comment]
Looks like noway to verify it. As any instruction after such push will go to the push data instead. I think it is enough to check gas usage. I will add this test to statetests.

**Comment by norhh** [comment]
Awesome, thanks a lot.

**Comment by winsvega** [comment]
The test
https://github.com/ethereum/tests/pull/508/commits/78dbc922a4a2f0e159a20107462dbadb7967f663
