### ISSUE TITLE
Is TransactionNonceCheck state test incorrect?

### ISSUE THREAD

**Issue by germsvel** [ethereum/tests#504]
I was looking through the [transaction nonce check state test](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stTransactionTest/TransactionNonceCheck.json) and its [filler](https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stTransactionTest/TransactionNonceCheckFiller.json). And I can't quite understand why it creates the beneficiary's account `2adc25665018aa1fe0e6bc666dac8fc2697ff9ba ` (before EIP-158).

The `pre` section does not have the account, but the `post` section does. It seems to me that since the sender account's nonce is `10` and the transaction nonce is `0`, the transaction should never get executed because it fails step (3) of the initial tests of intrinsic validity outlined at the beginning of Section 6 of the Yellow Paper. 

![screen shot 2018-09-10 at 11 29 36 am](https://user-images.githubusercontent.com/3245976/45308405-63d6b900-b4ef-11e8-94af-46810ae15567.png)

Someone in gitter mentioned that perhaps state tests should not have tests with invalid transactions, so I'd be happy to open a PR removing the test if that's the case.

**Comment by germsvel** [comment]
After looking at some of [mana's](https://github.com/poanetwork/mana) Frontier state test failures, it seems that all of the following are tests with invalid transactions, 

```
stCallCreateCallCodeTest/createNameRegistratorPerTxsNotEnoughGas
stInitCodeTest/NotEnoughCashContractCreation
stRandom2/201503110226PYTHON_DUP6
stTransactionTest/CreateTransactionReverted
stTransactionTest/EmptyTransaction
stTransactionTest/OverflowGasRequire
stTransactionTest/RefundOverflow
stTransactionTest/RefundOverflow2
stTransactionTest/TransactionNonceCheck
stTransactionTest/TransactionNonceCheck2
stTransactionTest/TransactionToItselfNotEnoughFounds
stTransactionTest/UserTransactionGasLimitIsTooLowWhenZeroCost
```

If the state tests should not have invalid transactions, should all of those be deleted as well?

**Comment by winsvega** [comment]
No. Thanks for the list. 
And yes you could open a PR that removes it. 
I will reimplement those cases in a form of correct blockchain test.

**Comment by germsvel** [comment]
@winsvega thanks for all the guidance with this test removal. I opened a PR removing the test (and filler) for the TransactionNonceCheck. If you want me to remove any other tests on the list above, let me know. I'd be glad to help.

**Comment by winsvega** [comment]
do not remove such tests for now. 
we discussed this issue and decided to leave it as it is for now.

the problem you were having is a fake touch to coinbase that imitate mining reward in state tests. 
that touch was done because state tests could be executed via rpc like a blockhain test.
