### ISSUE TITLE
GeneralStateTests/stZeroKnowledge/pointAdd not taking account of EIP-1283 in Constantinople

### ISSUE THREAD

**Issue by sorpaas** [ethereum/tests#512]
For example, in test index 5, two `SSTORE` are present to set storage `0x0` twice. However, the hash expected for Byzantium and Constantinople are the same.

**Comment by winsvega** [comment]
The tets has recently been updated for Constantinople. Issue should be gone by now. 
Do you still have any tests failing?

**Comment by cheme** [comment]
No the tests are not failing anymore :+1:
