### ISSUE TITLE
VMTests does not really test logs, or does it?

### ISSUE THREAD

**Issue by feliam** [ethereum/tests#515]
Here the logs item is described as a dictionary:
https://github.com/ethereum/tests/blob/develop/docs/test_types/vm_tests.rst#the-logs-section

The ``logs`` sections is a mapping between the blooms and their corresponding logentries.
Each logentry has the format:

* ``address``: The address of the logentry.
* ``data``: The data of the logentry.
* ``topics``: The topics of the logentry, given as an array of values.  

Though the JSON schema defines a hex or empty.
And no actual VMTests tests seem to have anything useful in the  'log' part
```
./VMTests/vmLogTest/log4_nonEmptyMem_logMemSize1_logMemStart31.json:29:        "logs": "0x09928203a19d172f9c404eb76d61e6f4aedc83a2cada1ac2a02ad6aa0e98044b",
```

**Comment by pipermerriam** [comment]
The value is the hex encoded hash of the rlp encoded log entries, reducing the overall size of the test files while still verifying that all of the data is accurate (at the cost of being able to read what the data should be).

- `keccak(rlp.encode(log_entries))`

See: https://github.com/ethereum/py-evm/blob/7a96fa3a2b00af9bea189444d88a3cce6a6be05f/eth/tools/_utils/hashing.py#L8-L16

**Comment by feliam** [comment]
Why not reduce the size all the way and make only test the hash of the rlp of the complete test?
This is making the test loose granularity. With this you can aspire only to "something wrong with the log". Also it is testing rlp encoding (and keckakkk)  in the middle of it. :-1:

**Comment by pipermerriam** [comment]
I don't have an informed opinion on the approach.  If you have a suggestion for a broader change to the test format I'd recommend opening a new issue and speccing it out.

**Comment by feliam** [comment]
Looks a little redundant. But it's done. ^

**Comment by cdetrio** [comment]
Just a heads up, some of us would like to deprecate the VM test format.  Here's an open PR moving in that direction:  https://github.com/ethereum/tests/pull/470

Once deprecated, EVM implementations would just run the subset of StateTests that are the VM tests (e.g. the GeneralStateTests/VMTests folder.  VM tests in the StateTest format).

**Comment by feliam** [comment]
:man_facepalming: thanks for the heads up.

**Comment by feliam** [comment]
Another point in favor of deprecation? https://github.com/ethereum/tests/issues/524.
