### ISSUE TITLE
stCreate2/RevertOpcodeInCreateReturns_d0g0v0 not refilled

### ISSUE THREAD

**Issue by dwightguth** [ethereum/tests#521]
It would seem that the blockchain test stCreate2/RevertOpcodeInCreateReturns_d0g0v0 was not refilled with the new gas price of CREATE2 which includes the cost of the hashing operation.

**Comment by dwightguth** [comment]
Testing reveals the same seems to be true of  stCreate2/RevertInCreateInInit_d0g0v0

**Comment by winsvega** [comment]
those cases could actually be obsolite. need to check

**Comment by winsvega** [comment]
need a confirmation from Hive. 
@holiman 
if those cases are incorrect hive must detect it.

**Comment by winsvega** [comment]
test renamed to `RevertOpcodeInCreateReturnsCreate2` and refilled
