### ISSUE TITLE
VMTests lacks granularity for _LOG_ tests

### ISSUE THREAD

**Issue by feliam** [ethereum/tests#523]
Currently the XML tests in VMTests contain a hex encoded hash of the rlp encoded log entries for testing the logs. Loosing granularity and the ability to read what the data should be.
```
keccak(rlp.encode(log_entries))

See: https://github.com/ethereum/py-evm/blob/7a96fa3a2b00af9bea189444d88a3cce6a6be05f/eth/tools/_utils/hashing.py#L8-L16
```
IMHO follows..
 
The documentation for this is in the right direction though not matching the implementation. https://github.com/ethereum/tests/blob/develop/docs/test_types/vm_tests.rst#the-logs-section
```
The ``logs`` sections is a mapping between the blooms and their corresponding logentries.
Each logentry has the format:

* ``address``: The address of the logentry.
* ``data``: The data of the logentry.
* ``topics``: The topics of the logentry, given as an array of values.  
```
The reduction in the overall size of the test file(whatever that % is) using the hash trick does not overweight the lost in quality of this test. As a mind exercise consider just saving the hash of the rlp of the whole state instead of the actual detailed xml. 
Tests should be in the bussiness of testing not saving space.

See. https://github.com/ethereum/tests/issues/515, https://github.com/ethereum/tests/pull/516

**Comment by winsvega** [comment]
VMTests are converted to StateTests.
@qbzzt  make a new issue if you want vmtrace information check from the expect section
