### ISSUE TITLE
A test that all evm clients must agree with is wrong. Is it? 

### ISSUE THREAD

**Issue by feliam** [ethereum/tests#524]
There are 2 versions of the same account with conflicting balances and code in this "post" test.

https://github.com/ethereum/tests/blob/0c76bf7d18e63bb65e4b8ffdd20e602e97e1c83b/VMTests/vmSystemOperations/suicideNotExistingAccount.json#L33-L47

**Comment by holiman** [comment]
They're not the same account... Look at the first bytes of the address

**Comment by feliam** [comment]
Oh those do count?   lol

**Comment by holiman** [comment]
Btw, in case you have missed it; most discussions about tests happen over at gitter:  https://gitter.im/ethereum/tests

**Comment by feliam** [comment]
So the SELFDESTRUCT here worked.
0x0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6 gets deleted and it does not appear in the post. And the previously not existing beneficiary account (0xaa1722f3947def4cf144679da39c4c32bdc35681) is created.


All this with 1000 gas ?
```        "gas" : "0x03e5",```

**Comment by holgerd77** [comment]
Seems to be solved, will close.
