### ISSUE TITLE
Verify documentation is automatically building via RTD

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/tests#534]
It appears that documentation on ReadTheDocs may not be configured to automatically build the latest `develop`.

- verify that this is desired
- verify this is happening and if not, get the webhook installed.

**Comment by pipermerriam** [comment]
@winsvega I'd be happy to get this done if you aren't opposed.  Kindly add me as a contributor to the readthedocs project.  My username there is `pipermerriam`.

**Comment by holgerd77** [comment]
Short note to be sure: this would be latest ``develop``, since this is the actively used branch.

**Comment by winsvega** [comment]
I don't think that I have the access to add you to readethdocs. In fact it's been a long time since I last login to that page. @chfast

**Comment by pipermerriam** [comment]
@winsvega turns out @holgerd77 got me added.  If you'll send me a username for RTD we can get you added as well.

**Comment by holgerd77** [comment]
@winsvega You actually wanted to verify if "dimitry" is your username on ReadTheDocs, could you verify that and were able to login?

**Comment by winsvega** [comment]
could you please send the link to login page?

**Comment by holgerd77** [comment]
@winsvega https://readthedocs.org

**Comment by winsvega** [comment]
No. Looks like my account is winsvega

**Comment by holgerd77** [comment]
Ok, I'll take this as confirmed, please make sure that you can really log in with this account and this is no one else having registered with the name, otherwise the person has complete administrative control on the docs.

Generally no need to go there very often, especially if @pipermerriam gets the auto-triggered rebuild going.

**Comment by pipermerriam** [comment]
Docs are now building automatically and I've created dedicated tag builds for the `v6` release.

**Comment by holgerd77** [comment]
Ok, great
