### ISSUE TITLE
refill "stRevertTest/RevertInCreateInInit"

### ISSUE THREAD

**Issue by ayrat555** [ethereum/tests#536]
This test does not consider eip1283 (gas cost changes for `sstore` operation). When running this test with pre-Constantinople `sstore` gas cost it passes

**Comment by holgerd77** [comment]
This test is also not passing in latest [CI run](https://circleci.com/gh/ethereumjs/ethereumjs-vm/2507?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) on ``ethereumjs-vm`` for Constantinople tests where ``SSTORE`` implementation has already been merged.

This might still be another bug in our implementation, but somewhat hints to the direction that this can also be a wrong test case.

Eventually ``RevertInCreateInInitCreate2`` has the same problem?

**Comment by ayrat555** [comment]
Yes, the only two Constantinople tests that are not passing in [mana](https://github.com/poanetwork/mana) are `stRevertTest/RevertInCreateInInit` and `stCreate2/RevertInCreateInInitCreate2`

But running `stCreate2/RevertInCreateInInitCreate2` with pre-Constantinople `sstore` gas cost does not make it pass

**Comment by ajsutton** [comment]
I suspect https://gist.github.com/holiman/0154f00d5fcec5f89e85894cbb46fcb2 may be helpful here.  The new contract gets an address that already has storage but a 0 balance and 0 nonce so it's allowed to be created. Prior to executing the contract init code, the storage must be cleared and crucially the original value for the storage is considered to be 0 when calculating SSTORE gas cost.

**Comment by ayrat555** [comment]
We should reset storage for newly created accounts. We were
resetting them in the evm cache but we were reading initial values
from the permanent storage. We should read them from the cache

https://github.com/mana-ethereum/mana/pull/579

**Comment by holgerd77** [comment]
@ayrat555 Ah ok, thanks for clarification!
