### ISSUE TITLE
Test case: EXTCODEHASH of account without code

### ISSUE THREAD

**Issue by jwasinger** [ethereum/tests#540]
From https://eips.ethereum.org/EIPS/eip-1052 :
`The EXTCODEHASH of the account without code is c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 what is the keccack256 hash of empty data.`

**Comment by winsvega** [comment]
please post this issues to: 
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?userstoinvite=hugo@ethereum.org&ts=5be5af56&actionButton=1#gid=1811198384
