### ISSUE TITLE
Test case: EXTCODEHASH of nonexistent account is 0

### ISSUE THREAD

**Issue by jwasinger** [ethereum/tests#541]
From https://eips.ethereum.org/EIPS/eip-1052

**Comment by winsvega** [comment]
please mark it to this page 
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?pli=1#gid=1811198384

**Comment by jwasinger** [comment]
Had originally opened this so that the test case could be bountied but @hugo-dc picked it up.
