### ISSUE TITLE
Move touch simulation, difficulty and gas calculation - affected tests from State to Blockchain

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#553]
With NoProof now supporting Difficulty and BlockGasLimit calculation
some statetests that use difficulty or gaslimit opcodes must be moved into a blockchain tests.

**the issue**
I found out what was the issue with tests. 
retesteth do not overwrite blockheader with difficulty and gaslimit while running the state test. it just set those arguments for genesis block and thats it. we have recently changed noProof to calculate gasLimit and difficulty also. so when retesteth send a transaction it is executed in the next block where those arguments are already calculated / changed from genesis's (because genesis has no transactions the transaction is being executed at block1)

testeth rather overwrite difficulty and gaslimit. thus a blockchain form of any state test is not exactly valid. the first block should change the difficulty and the gasLimit according to noProof. but a block with gasLimit and difficulty that equal to genesis is still valid.

**solution**
 looks like any state test that hash difficulty or gaslimit opcode should be moved to blockchain test. because it is now a blockchain test logic. same as it was with blockhash. and I don't see the reason to set difficulty and gaslimit in state tests env section. 

state tests that operate near the max gasLimit should be reviewed. 

if to keep those tests in state tests it will require a complicated logic similar to the one that simulates coinbase touch. which is not really good. I think coinbase touch simulation should also be desibled in state tests. and those tests that are affected should be moved.

**Comment by ajsutton** [comment]
Pantheon is using option 2 - the 'env' section of general state tests is used to create a `BlockHeader` that provides the context for the transaction to execute in (https://github.com/PegaSysEng/pantheon/blob/5f8059d0559509042944488a611bcf554058d41a/ethereum/core/src/test/java/tech/pegasys/pantheon/ethereum/vm/GeneralStateTestCaseSpec.java#L39)

**Comment by winsvega** [comment]
Misunderstanding. 
Option 2 is about calculating 1st block difficulty and gasLimit from the values provided by env section 
as if env section was a previous block. (genesis)

**Comment by winsvega** [comment]
I found out what was the issue with tests. 
retesteth do not overwrite blockheader with difficulty and gaslimit while running the state test. it just set those arguments for genesis block and thats it. we have recently changed noProof to calculate gasLimit and difficulty also. so when retesteth send a transaction it is executed in the next block where those arguments are already calculated / changed from genesis's (because genesis has no transactions the transaction is being executed at block1)

testeth rather overwrite difficulty and gaslimit. thus a blockchain form of any state test is not exactly valid. the first block should change the difficulty and the gasLimit according to noProof. but a block with gasLimit and difficulty that equal to genesis is still valid.

 looks like any state test that hash difficulty or gaslimit opcode should be moved to blockchain test. because it is now a blockchain test logic. same as it was with blockhash. and I don't see the reason to set difficulty and gaslimit in state tests env section. 

if to keep those tests in state tests it will require a complicated logic similar to the one that simulates coinbase touch. which is not really good. I think coinbase touch simulation should also be desibled in state tests. and those tests that are affected should be moved.

**Comment by winsvega** [comment]
fixed some gasLimit issues in general state tests. it appears to be that all tests has gasLimit change if run as a blockchain. but only a few tests rely on that chagne in a post condition. therefore most tests could be fixed. but some still need to be moved. 
https://github.com/ethereum/tests/pull/590

**Comment by winsvega** [comment]
resolved with 
https://github.com/ethereum/tests/pull/607

apart from touch simulation
