### ISSUE TITLE
add tests for truncated output in EVM subcalls

### ISSUE THREAD

**Issue by ayrat555** [ethereum/tests#558]
[Our client](https://github.com/mana-ethereum/mana) is passing all common tests for all hardforks but it failed consensus because we didn't truncate subcall outputs when actual output size is bigger than out_size parameter

https://github.com/mana-ethereum/mana/pull/497
https://github.com/mana-ethereum/mana/pull/679

**Comment by winsvega** [comment]
this? https://github.com/ethereum/tests/pull/567

**Comment by ayrat555** [comment]
@winsvega  the problem was in `reverted` operation output. does your PR test a reverted subcall's output?

**Comment by winsvega** [comment]
you mean when a subcall revert return more then subcall return expect?

**Comment by winsvega** [comment]
I've updated the test case. could you check that it hits your bug?

**Comment by winsvega** [comment]
@qbzzt check if the issue case is covered

**Comment by qbzzt** [comment]
Yes, covered in https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stReturnDataTest/subcallReturnMoreThenExpectedFiller.yml
