### ISSUE TITLE
ADDMOD - another question 

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#56]
Still missing something: 

https://github.com/ethereum/tests/blob/develop/VMTests/vmArithmeticTest.json#L269

testing for: `addmod(-1, -2, 2)`

according  to this `µ[0] mod µ[1] = sgn(µ[0]) |µ[0]| mod |µ[1]|` the result should be: `-1`
but the expectation is for `1` :confused:

Please advice
Thanks in advance.

**Comment by CJentzsch** [comment]
We do not have signed add mod. So you can not have negative numbers as input.  The real input in your case is 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe . And you can interprete those bytes as -1 (if it should be interpreted as a signed  number, such as the case for SMOD, SDIV, ...) or as 2^256-1. For addmod the meaning of those bytes is 2^256-1. The input are always 32 bytes, and the operator defines how to interprete them. That is the difference between signed operators and unsigned operators.

**Comment by romanman** [comment]
@CJentzsch : sorry still missing something : 
so if you do `addmod(-1, -2, 2)` and pass `0xff...ff`, `0xff...fe`, `0x00...02`
according the encoding , how addmod should interpret
the `0xff..ff` ?

**Comment by CJentzsch** [comment]
((2**256-1)+(2**256-2))%2 = 1

**Comment by romanman** [comment]
@CJentzsch :+1: thanks done with arithmetic
all pass now.
