### ISSUE TITLE
Likely typo in badOpcodesFiller

### ISSUE THREAD

**Issue by veox** [ethereum/tests#565]
The [first opcode under test](https://github.com/ethereum/tests/blob/v6.0.0-beta.2/src/GeneralStateTestsFiller/stBadOpcode/badOpcodesFiller.json#L63) (`PC`) is of different pattern than the rest:

```
                                     vv------ 00 instead of 60
"0x600160016001600160016001600160015800006000f3",
"0x600160016001600160016001600160010c60006000f3",
"0x600160016001600160016001600160010d60006000f3",
"0x600160016001600160016001600160010e60006000f3",
```

(Discovered in [analysis of improper `py-evm` operation](https://github.com/ethereum/py-evm/pull/1181#issuecomment-445290147).)

**Comment by carver** [comment]
I assume @lithp already saw this, but cc'ing just in case...

**Comment by winsvega** [comment]
@jwasinger

**Comment by winsvega** [comment]
status: trying to reach. jwasinger. 
but probably a typo. looks like a push instruction should be there

**Comment by jwasinger** [comment]
hey... my apologies.  Let me get out a fix for this.

**Comment by jwasinger** [comment]
https://github.com/ethereum/tests/pull/592

**Comment by veox** [comment]
Closing, as PR #592 has been merged.
