### ISSUE TITLE
vmEnvironmentalInfoTest.ExtCodeSizeAddressInputTooBigRightMyAddress

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#57]
https://github.com/ethereum/tests/blob/develop/VMTests/vmEnvironmentalInfoTest.json#L80

That test emitates code approach
by a wrong address, the result is
creation of that address, is it the
correct way? 

`572e5295c57f15886f9b263e2f6d2d6c7b5ec6aa`

does cpp do it in the live state run  ?

**Comment by CJentzsch** [comment]
Creation of the address is the wrong word. Every address exists, but has only zero entries. Here in the vm tests in the pre and post state there is no coinbase, sender, ... . They exist, but we do not need them for that test so we ignore them. In state tests we mention every existing (in use) account.
In this particluar test, we ask for the size of the code of an empty address. The size is zero. The address is still empty.

**Comment by romanman** [comment]
I mean you have the pre and post different: 
so you expect repository to keep track that
such an account was approached.

```
 "post" : {
            "0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6" : {
                "balance" : "1000000000000000000",
                "code" : "0x740f572e5295c57f15886f9b263e2f6d2d6c7b5ec6aa3b600055",
                "nonce" : "0",
                "storage" : {
                }
            },
            "572e5295c57f15886f9b263e2f6d2d6c7b5ec6aa" : {
                "balance" : "0",
                "code" : "0x",
                "nonce" : "0",
                "storage" : {
                }
            }
        },
        "pre" : {
            "0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6" : {
                "balance" : "1000000000000000000",
                "code" : "0x740f572e5295c57f15886f9b263e2f6d2d6c7b5ec6aa3b600055",
                "nonce" : "0",
                "storage" : {
                }
            }
        }
```

**Comment by CJentzsch** [comment]
I agree that this is a subtle point. Basically I print the accounts which are in the cache, so accounts which have been used in the execution of the test. All you need to do is to check, that your client has the same values (balance, code, nonce, storage) for every accout in the post state. So if you ask your database for the values of the account 572..., they need to be zero.

**Comment by romanman** [comment]
@CJentzsch : you see my implementation is probably slide
different , if I init the test case I will put in the db only 
pre section addresses.

 So I guess the fix for me is just to add the accounts 
that was approached by `getBalance` or `getNonce` or `getCode`
if they are not exist. 

 + It still stays with 2 questions , is it the same in the State testing ? 
 + is it affects the trie on the live run ?

**Comment by CJentzsch** [comment]
It is not the same in state testing. Thats one of the reason why I didn't like the vm tests and "invented" the  state tests. In state tests pre and post give you the complete state. The root of that state would be part of the block header. In vm tests, only "needed" addresses are put in. Therefore you do need to check if this exactly matches with your state, but check that the accounts mentioned in post state have the same values as the ones you would get asking for in your state. (e.g. all zeros).

**Comment by romanman** [comment]
@CJentzsch : Let's summarized just to see that I 
got all correct: 

1. VMTest each new approached account will be in the post state 
event if it was only `getBalance()` and no set so the all values will 
remain zeroes

2. StateTest only the account that actually do a `setBalance()` or `increaseNonce()`
or any other change are the only one who are going to be in the post in addition to 
pre accounts.

3. The real system behaves the exact way as the state testing. 

Can you say 1,2,3, are all correct ?

**Comment by CJentzsch** [comment]
correct!

**Comment by romanman** [comment]
:+1:
