### ISSUE TITLE
Document expectExceptionALL

### ISSUE THREAD

**Issue by lithp** [ethereum/tests#575]
This key is not documented. Client developers would have an easier time understanding test failures if they knew what this key meant.

**Comment by lithp** [comment]
For example: `ExtraDataIncorrect` means that [this exception](https://github.com/ethereum/aleth/blob/master/libethcore/SealEngine.cpp#L98) occured while processing the block.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/698/files#diff-aef791a7cc39a7e07b1d44a0f17fbd32R73

**Comment by holgerd77** [comment]
We've actually lately integrated the `expectException` field into our test runner: https://github.com/ethereumjs/ethereumjs-vm/pull/752
