### ISSUE TITLE
Make proper test out of stBugs/randomStatetestDEFAULT-Tue_07_58_41-15153-575192.json

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#581]
Hi,

The stBugs/randomStatetestDEFAULT-Tue_07_58_41-15153-575192.json description says

"suicide-created-but-empty account has a non-zero codehash in geth".

It is the only test for this case. It would be good to create a manual state test for the CODEHASH of a "suicide-created-but-empty account".

**Comment by qbzzt** [comment]
It's not just suicide created but empty. If a contract is completely empty (all fields are equal to zero) then `EXTCODEHASH` returns zero. But if there's anything there, such as a balance or a nonce, then `EXTCODEHASH` returns the Keccak-256 of an empty buffer, 
0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 (see https://medium.com/@ConsenSys/are-you-really-using-sha-3-or-old-code-c5df31ad2b0).

I'm going to write a test to prove that this happens whenever a contract has anything in any field.
