### ISSUE TITLE
Possibly incorrect assertion of validity of transaction RightVRSTestF0000000a test

### ISSUE THREAD

**Issue by danjm** [ethereum/tests#584]
In my work on adding full support for spurious-dragon to `ethereumjs-tx`, I have come across a handful of transaction tests that claim to be invalid for spurious dragon and later while the properties of the tested tx seem to be valid.

For instance, https://github.com/ethereum/tests/blob/develop/TransactionTests/ttRSValue/RightVRSTestF0000000a.json + https://github.com/ethereum/tests/blob/develop/src/TransactionTestsFiller/ttRSValue/RightVRSTestF0000000aFiller.json

The tx here does violate the pre https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md conditions for the `v` property. As such we would expect it to be invalid on hard forks prior. However, the current test specified it should be invalid on all hardforks. It is not clear what condition of the tx indicate invalidity for spurious dragon or later.

Meanwhile, the data from the test can be used to create a valid tx on geth.

Does anyone have insight into what might be happening?

**Comment by winsvega** [comment]
you mean geth will accept a transaction with such V - value on a mainnet ?

**Comment by qbzzt** [comment]
We don't have transaction tests, and we don't plan on having them. I think we can close this.

**Comment by winsvega** [comment]
we have transaction tests in ttTransaction.
it is a scheme test. meanin it is up to devs to implement this tests and go throug the jsons. 

however, if we really want to we can forge blocks with transactions having this v values and see what client error code is returned.

**Comment by winsvega** [comment]
hm. the transaction test suite went kind of unsipported. because there is no test protocol we can't really run or generate those tests anymore. I think its about to go to legacy. 

(the ttTransaction test suite tried to test the transaction struct on all kinds of crazy data in transaction fields without the context of State or EVM and blockchain)

**Comment by winsvega** [comment]
now when we have transaction tests with invalid invalid expections we can work towards malformed transaction tests with crazy signatures to be expected rejected

**Comment by norswap** [comment]
> you mean geth will accept a transaction with such V - value on a mainnet ?

It will not accept such values on mainnet (where the chain id has to be 1), but may accept them if the chain ID is different. [Relevant geth code](https://github.com/ethereum/go-ethereum/blob/33ca98ece985f5085ac8ec19a49239d726850004/core/types/transaction.go?plain=1#L203-L227).

Small question: why is the test called `RightVRSTestF0000000a`? I don't see F0000000a being featured anywhere (`v` is 0xf028 = 61480). In the F0000000a it's 0xf029, etc.

What's the point of these tests actually (and why so many of them)?

**Comment by winsvega** [comment]
hm. It was a really long time ago. looks like not even my tests. the idea is to have V value correct but with some garbage prefix I see. 

now with expect exception the validity is clear 

```
	    "expectException" : 
        {
            "<=EIP150": "InvalidVRS",
            ">=EIP158": "InvalidChainID"
        },
```
