### ISSUE TITLE
JSON RPC Tool

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/tests#586]
Since we decided to move from `Aleth` to a generic test generation process, we decided on the
`JSON RPC Testing Tool`.
* Should the development of this tool be in a separate repository or in this repository itself? (Like something similar to `Dopple`).
* Some Consensus algorithm could be deployed on the outputs of the `JSON RPC` results from the different clients we are supporting. So ideally, this `Consensus algorithm` should pass if all the outputs are same, else it should show which clients are faulty. Any ideas for such algorithms (Something similar to Byzantine's General Problem, but not exactly).

**Comment by winsvega** [comment]
I continue on developing this tool.

https://github.com/ethereum/retesteth/
https://github.com/ethereum/retesteth/wiki/RPC-Methods

It basically read json Filler files and run it through RPC using `test_` RPC methods.
Any client could be configured to work with retesteth. 
Retesteth could run / generate tests using the client and test Fillers.

**Comment by pipermerriam** [comment]
cc @wtf
