### ISSUE TITLE
Reason for no post in sstore_load_2 and jumpTo1InstructionafterJump

### ISSUE THREAD

**Issue by norhh** [ethereum/tests#589]
In the tests VMTests/vmIOandFlowOperations/sstore_load_2.json and VMTests/vmIOandFlowOperations/jumpTo1InstructionafterJump.json there is no post state, is there any reason for that?

**Comment by winsvega** [comment]
a vmexception is happening.

**Comment by winsvega** [comment]
the vm tests are updating to state test format

**Comment by holgerd77** [comment]
Totally impressed that one can work down three issues in < 1 minute. 😜

**Comment by winsvega** [comment]
there are bunch of vm tests issues that we are gonna close as the support of VMTests is ending. 
the cases are now covered by state tests.
