### ISSUE TITLE
StateTests: change post hash calculation

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#591]
The ongoing RPC test run development require to run GeneralStateTests as if it was a blockchain test. because this is a correct way to simulate a state change. (setup state in the chain. send transaction to the client with that state. see the result. a transaction result is finalized in the block)

**The issue:** 
All General State Tests has poststate hash field having a hash of state calculated without mining reward. RPC test tool could not calculate post state of transaction execution (otherwise its a client) (but it could take mining reward into account and still check expect section conditions on balance changes)

A client could not calculate the post state of transaction execution without mining reward. otherwise it is a test tool. 

**The solution**
A solution would be to change actual hash of the "hash" field in generated StateTests to be the hash of state including mining rewards.

**Comment by holiman** [comment]
No please don't change the tests again.  You already did once, and gst is NOT a blockchain test, if if made into one it becomes less. Avoid, please

**Comment by winsvega** [comment]
Another option would be to make test tool being able to calculate hash of state itself. (Means it should know how to construct state trees and stuff) which I think is not a good option for the test tool.

Changing the state tests hash filled would not affect hive.

**Comment by winsvega** [comment]
I would actually want to depricate State Tests in a move towards a uniformed test format

**Comment by holiman** [comment]
I know you do. Imo that's like deprecating unit tests and replacing with integration tests. The latter cannot possibly test everything the former can. Both have a place.

**Comment by holiman** [comment]
At least if you want to replace statetests with blockchain tests only

**Comment by winsvega** [comment]
It kind of already replaced. Hive run blockchain tests only. Currently the issue is that via rpc tool I could not generate a state test, because via rpc its being run as a blockchain transaction with mining rewards. I could extend the state tests with additional hash of a state with mining reward, but that I could only generate with testeth.

**Comment by holiman** [comment]
Hive is a end to end integration test. It cannot test everything, that's why other test formats are required, other than blockchain tests.

**Comment by winsvega** [comment]
**The solution 2**
(Filled) State Tests are only supported by testeth and get deprecated as testeth. 
All tests are updated in blockchain format by rpc filling tools.

**Comment by holiman** [comment]
In converting state tests to block tests, some lose their meaning. We've been over this...

**Comment by chfast** [comment]
I'm also not convinced. The state tests are already bad for EVM testing because they require at least Trie and RLP implementations. Please do not add PoW to that list.

**Comment by winsvega** [comment]
what do you mean? I am not speaking about PoW. only the mining reward to the coinbase account (it is neglected in state tests. thus post state hash is different from blockchain analog of a test)

**Comment by winsvega** [comment]
at the current state. retesteth could not generate stateTests. or run stateTests. because such test does not has postHash with rewards. running state tests as blockhain is impossible on the fly (need to convert to blockchain test first)
