### ISSUE TITLE
Coverage of EVM by state tests

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#597]
I have run state tests on [evmone](https://github.com/chfast/evmone).
There is the report: https://codecov.io/gh/chfast/evmone/src/a4c5403f282a32de0fa0cc9ad7923858f21fae76/lib/evmone/execution.cpp
([PR](https://github.com/chfast/evmone/pull/60) for tracking updates).

Tests revision: https://github.com/ethereum/tests/commit/5018b8f30e9e57a0d136ed40bc6ceab51b61e144.

**Comment by axic** [comment]
Relevant #459 and https://github.com/ethereumjs/ethereumjs-vm/pull/270#issuecomment-362871486

**Comment by winsvega** [comment]
GitHub API: Not Found

**Comment by chfast** [comment]
I can produce new report based on evmone + silkworm + blockchain tests.

**Comment by chfast** [comment]
You can start with https://codecov.io/gh/ethereum/evmone/src/74dd26af6c428bf04c38f69783af7c8425e50f1c/lib/evmone/instructions.hpp, just disable "unittests" flag to see only coverage by blockchain tests.

**Comment by winsvega** [comment]
Can help with https://github.com/ethereum/tests/issues/441

**Comment by chfast** [comment]
I report these cases one-by-one and this works.
