### ISSUE TITLE
Transaction; Can the Address field be less than 20?

### ISSUE THREAD

**Issue by wanderer** [ethereum/tests#61]
How can this be valid?  https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L12

I'm pretty sure that the yellow paper defines addresses as 160bits

**Comment by CJentzsch** [comment]
It does. The cpp client fills up the remaining bytes with 0's. But  I am not sure if this is correct behavior according to YP. @gavofyork

**Comment by wanderer** [comment]
even if the cpp fills the remaining bytes after its done parsing the Tx it should produce 
`0x000000000000000000000000000b9331677e6ebf`  
and not `b9331677e6ebf`

**Comment by wanderer** [comment]
and If we are remove the leading zeros from fields with a know length then this one is wrong https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L18 and conflicts with this test https://github.com/ethereum/tests/blob/develop/TransactionTests/ttWrongRLPTransaction.json#L11
