### ISSUE TITLE
Test format check failure in just-cloned repo.

### ISSUE THREAD

**Issue by acoglio** [ethereum/tests#611]
I just cloned the repo and `make RLPTests.format` results in a `git diff` error. The `.json` files under the `RLPTests` directory show up as modified.

Have I missed some steps? I followed the instructions under 'Test Set Sanitation' at https://github.com/ethereum/tests.

Background: I'd like to make a PR with some new RLP tests and I understand that I should ensure that the sanitation tests pass first, but the problem is that I'm getting this failure without my new tests.

**Comment by winsvega** [comment]
Oh. I don't support this scripts. And it is probably way outdated. Also would not recommend using this scripts for the test filling. Consensus test execution is a separate tooling. Currently there is `testeth` from `aleth` to run most of this tests. 

To check RLP tests:
```
./testeth -t RlpTests
```

Another project to run consensus tests against different client implementations: 
https://github.com/ethereum/retesteth

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/631
