### ISSUE TITLE
Balance Overflows

### ISSUE THREAD

**Issue by wanderer** [ethereum/tests#62]
should [this](https://github.com/ethereum/tests/blob/develop/StateTests/stTransactionTest.json#L1289) be `115792089237316195423570985008687907853269984665640564039457584007913129640035` ?
I See that the balance is overflowing but is this correct behavior?

**Comment by CJentzsch** [comment]
It is correct behaviour, but again will never occur in real life. The balance belongs to the set B_256. So it can never be larger than 2^256-1. And therfore have to overflow in that way. But we will never have pre state with a balance like that, or a transaction which could lead to balance (or nonce) overflow.
