### ISSUE TITLE
trietest.json: jeff test permutations?

### ISSUE THREAD

**Issue by swaldman** [ethereum/tests#64]
It looks as though the tests in `tests/TrieTests/trietest.json` are intended to be permuted, with deletions tacked onto the end to ensure that all bindings both added and deleted end up deleted. (Or maybe I'm wrong? I'm trying to follow along from e.g. [here](https://github.com/ethereum/pyethereum/blob/d442c114b694439a85a89bb3b06d5115243d3067/tests/test_trie.py).)

That works fine for most of the tests there, but not, i think for test `jeff` in the [current version](https://github.com/ethereum/tests/blob/4d37c1cea2ca2999e8dd442ee137c942755697f6/TrieTests/trietest.json) , which has two items with identical keys but distinct values, and whose key is not eventually deleted. 

```
      ["0x000000000000000000000000697c7b8c961b56f675d570498424ac8de1a918f6", "0x1234567890"],
      ["0x000000000000000000000000697c7b8c961b56f675d570498424ac8de1a918f6", "0x6f6f6f6820736f2067726561742c207265616c6c6c793f000000000000000000"],
```

So the hash of the trie after permutations of operations are legitimately dependent upon which binding is updated last, I think.

I apologize if I am (not unusually) missing something obvious!

**Comment by wanderer** [comment]
im not exactly sure of your question. But you are suppose to apply each each key/value pair in the `in` array to the trie. Your resulting stateroot should then match `root`

**Comment by swaldman** [comment]
Yes. And that works great! And thanks for the quick response!

I'm trying to crib from you guys carefully, and and the [python](https://github.com/ethereum/pyethereum/blob/d442c114b694439a85a89bb3b06d5115243d3067/tests/test_trie.py) implementation seems to run these tests not just by applying each k/v pair in order, but also by permuting the order of those operations many times and expecting the same hash. So I've tried to reproduce that too.

The [c++](https://github.com/ethereum/cpp-ethereum/blob/0ee53a19357021cfbc76438a9fb1be0521ae0174/test/trie.cpp) implementation seems to permute only the operations from the file [tests/TrieTests/trieanyorder.json](https://github.com/ethereum/tests/blob/4d37c1cea2ca2999e8dd442ee137c942755697f6/TrieTests/trieanyorder.json), which I think will have a similar problem running the test `foo`, as it has two different entries with key 'food', but distinct values, so the hash of the trie will depend on the order in which those insertions are applied.

**Comment by wanderer** [comment]
confirming [this](https://github.com/ethereum/tests/blob/4d37c1cea2ca2999e8dd442ee137c942755697f6/TrieTests/trieanyorder.json#L28-L29) can't be right. @gavofyork can we change these to ordered arrays as well?

**Comment by swaldman** [comment]
Thanks very much again for your quick response!

For now I'll just exclude `foo` in `trieanyorder.json`, and `jeff` in `trietest.json` from permutation testing. But I'd like to follow along with however you guys decide to resolve this. (If you are curious, I'm implementing bits and pieces of ethereum in Scala [here](https://github.com/swaldman/consuela).)

**Comment by CJentzsch** [comment]
tests/TrieTests/trietest.json should not be permuted and  tests/TrieTests/trieanyorder.json should be permuted.

**Comment by swaldman** [comment]
(i guess that permuting the `trietest.json` tests but appending all deletes was a pyethereum innovation. it does work okay, except for test `jeff`.)

**Comment by CJentzsch** [comment]
I also updated `tests/TrieTests/trieanyorder.json` (https://github.com/ethereum/tests/commit/8b79ae6695c9d0a84542df8a02dc45b35fbf560e)

**Comment by swaldman** [comment]
Thanks again for the quick responses and work. I really appreciate it.

**Comment by CJentzsch** [comment]
Thanks for pointing this issue out.
