### ISSUE TITLE
`ByzantiumToConstantinopleFixAt5` transition does not check that it's actually a transition to Petersburg

### ISSUE THREAD

**Issue by veox** [ethereum/tests#644]
Fallout from https://github.com/ethereum/py-evm/pull/1858#pullrequestreview-301910619.

`py-evm` was erroneously transitioning to `Constantinople`, not `Petersburg` (a copy-paste error).

The test that checks the transition [doesn't seem to have anything `Petersburg`-specific](https://github.com/ethereum/tests/blob/v7.0.0-beta.1/src/BlockchainTestsFiller/TransitionTests/bcByzantiumToConstantinopleFix/ConstantinopleFixTransitionFiller.json#L40), so the test was still passing.

Not sure how to address this.

**Comment by winsvega** [comment]
You right. the initial test was done to see the difficulty bomb change from Byzantium to Constantinople
and the mining rewards + uncle rewards. 

the solution is to add more sstore operations to this test

**Comment by qbzzt** [comment]
Added in https://github.com/ethereum/tests/pull/768
