### ISSUE TITLE
CircleCI misconfiguration leads to inaccurate test reporting

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/tests#645]
Github shows that some tests have failed, but digging just a bit, I found that an empty circleCI build is causing it. Maybe it can just be turned off for now? 

Is there any plans to port travis over to circleci? 

Cheers!

https://circleci.com/gh/ethereum/tests/93?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

![image](https://user-images.githubusercontent.com/47108/67234933-11ffa280-f414-11e9-883e-52b0ba33c703.png)

**Comment by winsvega** [comment]
I would love to. I can't figure out how. looks like this issue pops up only from my PRs

**Comment by evertonfraga** [comment]
Correct, it only pops up for your own PRs. CircleCI does not build from external forks by default.

You can disable it by heading to repo settings, `Webhooks and Services`, and delete the CircleCi webhook.

cheers!

**Comment by winsvega** [comment]
Should be fixed now

**Comment by evertonfraga** [comment]
Great! :)
