### ISSUE TITLE
Add more tests for EXTCODEHASH of "empty"

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#652]
Related to https://github.com/ethereum/EIPs/pull/2144.

### Test cases

1. CALL an nonexistent account, then get EXTCODEHASH of it.
2. CREATE empty account, then get EXTCODEHASH of it.
3. CALL an account which will SELFDESTRUCT, then get EXTCODEHASH of it.

**Comment by winsvega** [comment]
@chfast check the tests
https://github.com/ethereum/tests/pull/654/commits/429716a4f9e35181fad91a3a2e9288c3a0805296
