### ISSUE TITLE
Change Call50000bytesContract tests

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#657]
From some HF, the contract size limit is 0x6000 (24576). It is impractical to have tests for a contracts of size 50000 being over 2x larger than the limit.
Please modify the tests to use the limit 0x6000 instead of 50000.

**Comment by winsvega** [comment]
ah so the contract still could be 50k bytes theoretically if it was deployed before, but not anymore? 
the quadratic complexity tests were done by Vitalik to test the execution speed. if it is still possible that a network has such a code could be worth keeping it the way it is. 

are this tests cause a problem in evm ?

**Comment by chfast** [comment]
> are this tests cause a problem in evm ?

Yes, because evmone expects the max code size to be smaller.

**Comment by winsvega** [comment]
what if a contract been deployed with a bigger code size before the HF and evm needs to parse it? 

anyway since we have the legacy tests this could be updated to a smaller codesize

**Comment by chfast** [comment]
> what if a contract been deployed with a bigger code size before the HF and evm needs to parse it?

At least it did not happen on mainnet.

**Comment by winsvega** [comment]
check this fix: https://github.com/ethereum/tests/pull/658
if its good I shrink the other tests the same way

**Comment by winsvega** [comment]
@chfast
