### ISSUE TITLE
Storage Duplicate Create2OOGafterInitCodeReturndata2Filler

### ISSUE THREAD

**Issue by jafri** [ethereum/tests#675]
https://github.com/ethereum/tests/blob/de158eea2198217cb2132eabddd7470d4a022c40/src/GeneralStateTestsFiller/stCreate2/Create2OOGafterInitCodeReturndata2Filler.json#L69-L70

Still browsing around tests,  it seems that this filler has two storage slots in pre with the same key 0x01, is this expected?

**Comment by winsvega** [comment]
probably left from when before '//' sections been implemented. the json file read will treat the last read value if the key is same. to avoid confusion the first one should be removed.
