### ISSUE TITLE
Berlin HF Release Planning

### ISSUE THREAD

**Issue by holgerd77** [ethereum/tests#686]
Hi guys,
this issue is for release planning around the Berlin HF. I would like to do at most two releases here, one final `v7.0.0` release finishing up on [v7.0.0-beta.1](https://github.com/ethereum/tests/releases/tag/v7.0.0-beta.1) and providing some stable ground to update the test runners to on a pre-Berlin state.

We have re-started to run the tests from the current `develop` state against EthereumJS VM, see https://github.com/ethereumjs/ethereumjs-vm/pull/743. We are running into some issues there (some `BlockChain` tests are failing), I would use the occasion to work on some `v7.0.0` release notes along our work there and open here as a PR so that others can profit.

I would then prepare one or more `v8.0.0-beta.x` releases for Berlin-integrating releases once first PRs are merged here.

@winsvega how do you plan to proceed with the [LegacyTests](https://github.com/ethereum/tests/blob/develop/LegacyTests/) folder separation. Will there be a dedicated switch with a move of the `Istanbul` tests over there at some PIT? Or will the `Berlin` tests reside in the main test folders for now?

**Comment by holgerd77** [comment]
Update: have written some release notes together for a `v7.0.0` pre-`Berlin` HF release here https://github.com/ethereum/tests/pull/687/files. This can already be used by client devs to update their tests and eventually adopt to test format changes.

**Comment by holgerd77** [comment]
Update: preparatory pre-Berlin HF has been released as a final [v7.0.0](https://github.com/ethereum/tests/releases/tag/v7.0.0) version.

PR for a first Berlin HF `v8.0.0-beta.1` release with EVM subroutine tests (not merged yet): https://github.com/ethereum/tests/pull/692

**Comment by winsvega** [comment]
switched to github release system now
