### ISSUE TITLE
Balance overflowing in sha3_memSizeNoQuadraticCost31

### ISSUE THREAD

**Issue by adria0** [ethereum/tests#690]
In the https://github.com/ethereum/tests/blob/v7.0.0/BlockchainTests/ValidBlocks/VMTests/vmSha3Test/sha3_memSizeNoQuadraticCost31.json test

the initial balance is

https://github.com/ethereum/tests/blob/5e4539b1b50747e699a5990b3f8696c9267e6c31/BlockchainTests/ValidBlocks/VMTests/vmSha3Test/sha3_memSizeNoQuadraticCost31.json#L15

and after sending `0x7c`, the final balance is 

https://github.com/ethereum/tests/blob/5e4539b1b50747e699a5990b3f8696c9267e6c31/BlockchainTests/ValidBlocks/VMTests/vmSha3Test/sha3_memSizeNoQuadraticCost31.json#L106

Is this the expected way to manage overflows? I think that will have more sense to do saturating overflow or just reject the tx.

(since is filled by geth, cc/@karalabe)

**Comment by karalabe** [comment]
Weeell, I think that's undefined behavior which we should not test. A gazillion things can go wrong all over the place if balances start overflowing, something which cannot ever happen in a live network. It would be a pointless can of worms to start speccing what clients should do in these cases.

**Comment by adria0** [comment]
related https://github.com/ethereum/tests/pull/688

**Comment by winsvega** [comment]
Fixed
https://github.com/ethereum/tests/pull/695
