### ISSUE TITLE
Incorrect test case

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/tests#694]
I believe the following test is incorrect:

https://github.com/ethereum/tests/blob/develop/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestamp5.json

Py-EVM doesn't recognize anything wrong here and the comment suggests geth doesn't either.

https://github.com/ethereum/tests/blob/66b1043d0dd011f541d41331e9bd81b4ae66705a/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestamp5.json#L4

Maybe I'm misunderstanding the test. The following RLP...

https://github.com/ethereum/tests/blob/66b1043d0dd011f541d41331e9bd81b4ae66705a/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestamp5.json#L122

...gives us a block with the following properties:

hash: `0xe8b851aa1188b4e535fa7d98fd7af0cbbddd62003bb35661794602e1118eabc6`
block_number: `3`
timestamp: `3001`
parent_hash: `0x2ef08e73a777e3268ede60afb30303d28a5c3ece3d19ad88e413b313aa56595a`

And the parent header  `0x2ef08e73a777e3268ede60afb30303d28a5c3ece3d19ad88e413b313aa56595a` has a timestamp of `2001`.

The timestamp does not seem to violate anything. Or am I reading the test wrong?

**Comment by holiman** [comment]
This is the uncle from that rlp
```
    [
      65dd48cd78b5281cafd6395c9cd5ef2767ee4226706cbc122895abb98655a2d8,
      1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347,
      b94f5374fce5ed0000000097c15331677e6ebf0b,
      fe87abb0d3ab38d4eb64405de03db5245b0d40c4b85d8a1b5028ada8643de2db,
      56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421,
      56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421,
      00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
      020000,
      02,
      3007cf,
      "",
      03e9,
      "B",
      0000000000000000000000000000000000000000000000000000000000000000,
      0000000000000000,
    ],

```
So I think the uncle timstamp is `0x03e9` == `1001`. So the uncle timestamp is earlier than the parent.

**Comment by cburgdorf** [comment]
Oh I see. But is that even relevant? Aren't we only supposed to check that the timestamp of the header is greater than the timestamp of the parent?

**Comment by holiman** [comment]
Right.. Yeah I think you're correct, it isn't relevant.
