### ISSUE TITLE
EIP 2537 tests

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereum/tests#705]
EIP 2537 state tests are missing. Please add (complete) tests in the official ethereum state test suite. Some test vectors can be imported from [the linked test vector directory in the EIP](https://github.com/matter-labs/eip1962/tree/master/src/test/test_vectors/eip2537), although these have to be converted to official state tests instead of csv input/output files.

**Comment by jochem-brouwer** [comment]
Hey, after a reply from @shamatar on the above linked repository where I opened a similar issue, I found out that return values are actually not part of the `receiptsTrie` and that this is an argument why it is hard to do state tests. But if I check some VM tests it seem that these work just fine (i.e. check `DUP` opcodes, where result is dumped in a storage slot) with a few "tricks" (create a contract). I strongly suggest we create state tests this way.

**Comment by winsvega** [comment]
The storage trick we use a lot in state tests.

The vmtests allowed to see the actual vm output, but that only supported by old testeth which is discontinued.

**Comment by shamatar** [comment]
It would not be a problem for my particular case as I can just abuse SSTORE and hashing, but larger problem is how to check the gas schedule. If just use gasleft() before and after staticcall() it will be a mix of STATICCALL, memory size, stack manipulations, etc

**Comment by jochem-brouwer** [comment]
We could use `CALL` here, set `out` / `outsize` both to 0 (so we do not create any more memory), then `CALL` should have constant (?) gas cost and we do not get in problems if these `STATICCALL` repricing gets in the Berlin fork. I get that the idea here is that we use `gasleft()` before/after the call and store the difference as well? I actually like this idea.

**Comment by holiman** [comment]
Gas paid for is reflected on the state root

**Comment by jochem-brouwer** [comment]
@holiman I think @shamatar refers to that we want to know how much was paid on the call itself, not the entire transaction. So we don't care about the gas cost of any stack manipulations, only about the gas cost of the `CALL` itself.

**Comment by winsvega** [comment]
Here is asm lll to measure gas of chainid into storage cell 1:
""//codeLLL"": ""(asm GAS CHAINID GAS SWAP1 POP SWAP1 SUB 5 SWAP1 SUB 0x01 SSTORE)"","

**Comment by holiman** [comment]
What does that matter? The total gas will include the call-gas, the stateroot will reflect if it's correct or notOn Jun 29, 2020 2:52 PM, Jochem Brouwer <notifications@github.com> wrote:
@holiman I think @shamatar refers to that we want to know how much was paid on the call itself, not the entire transaction. So we don't care about the gas cost of any stack manipulations, only about the gas cost of the CALL itself.

**Comment by jochem-brouwer** [comment]
It doesn't matter that much. I don't really care if we check against gas costs of the entire transaction or if we use this `gasLeft()` thing. I am super keen on getting official tests of this EIP in this test repository, so clients are actually testing against the same vectors.

**Comment by shamatar** [comment]
It does not even look possible to specify modern forks for `retesteth` to run the precompiles without monkey patching

**Comment by winsvega** [comment]
There is .retesteth config folder. You can set any new fork name and its translation for the client.

**Comment by shamatar** [comment]
At the moment Geth’s “retesteth” startup option and “test_” RPC do not accept MuirGlacier and YoloV1 block numbers from RPC requests, so I had to patch it to start making tests.

**Comment by winsvega** [comment]
geth retesteth support discontinued on geth side. 

Test's Berlin is configured as YoloV1 for geth evm t8n (retesteth -- --clients "t8ntool") 

If you need support with configs please ping me on https://gitter.im/ethereum/tests
We can make this better with your feedback

retesteth branch develop

**Comment by winsvega** [comment]
close? https://github.com/ethereum/tests/tree/develop/src/GeneralStateTestsFiller/stEIP2537

**Comment by jochem-brouwer** [comment]
Yep 👍
