### ISSUE TITLE
refund_CallA

### ISSUE THREAD

**Issue by faizkhan00** [ethereum/tests#72]
In the trace for this test, it seems there is no output relating to how the ending balances ended up in that state:

Java
```
 06:02:27.126 [VM]  
 Spent Gas: [830]/[1500]
   Left Gas:  [670]
```

Cpp
```
EVM [ 07:03:08 | main | 0 | 095e7baea6a6c7c4c2dfeb977efac326af552d87 | #10 |
 0026 : STOP | 670 | -0 | 0x32 ]
```

And yet, even with the spent gas at 830, the testcase says:

Post:
```
  "2adc25665018aa1fe0e6bc666dac8fc2697ff9ba" : {
  "balance" : "730",
     "code" : "0x",
     "nonce" : "0",
     "storage" : {
    }
```

Is this right?

**Comment by CJentzsch** [comment]
This test is outdated (new gasprices). If you still have an issue with the updated tests, reopen the issue.
