### ISSUE TITLE
TestOpcode failures

### ISSUE THREAD

**Issue by holiman** [ethereum/tests#754]
It seems that both geth (https://hivetests.ethdevops.io/?page=v-pills-results-tab&suite=1604297886-a25d6be8ebadf09c45c7b6b9f9db18a2.json) and besu (https://hivetests.ethdevops.io/?page=v-pills-results-tab&suite=1604262811-5fefe26d48ca5648989132f32b1bc576.json) are failing the `Test_Opcode_xx_Berlin` tests. Since geth and besu appears in agreement, I think the tests are wrong.

**Comment by winsvega** [comment]
Yes it was filled with yolov1 version

An update for bc tests is coming

**Comment by winsvega** [comment]
merged fix. check now
