### ISSUE TITLE
last block hash is not present in any of blocks

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#76]
https://github.com/ethereum/tests/blob/develop/BlockchainTests/basicBlockChain.json

` "lastBlock": "9d0a03fd264306a8ccf624bbd52430c18016dd734f982f8e15a94e27c6a252d5",`

that hash isn't any of existing blocks, am I missing anything ?

**Comment by wanderer** [comment]
hey @romanman that is my fault, Will update soon

**Comment by romanman** [comment]
@wanderer : in this set of tests the `hash` is not part of the header
as it is in the second set of block chain tests: 
https://github.com/ethereum/tests/blob/develop/BlockTests/bcBlockChainTest.json#L48

do you want to make it one type data structure ?

**Comment by wanderer** [comment]
yes that is a good idea we should do that

**Comment by romanman** [comment]
:+1:

**Comment by romanman** [comment]
@CJentzsch : I guess we need your approve here.

**Comment by romanman** [comment]
@wanderer : can you pull that one ?
https://github.com/ethereum/tests/pull/79
