### ISSUE TITLE
More frequent Releases

### ISSUE THREAD

**Issue by holgerd77** [ethereum/tests#762]
Apparently this HF-centric release process from e.g here #686 doesn't work any more (maybe never was a good idea, not sure) with a potential Berlin release at  #692 now being open for months.

I would therefore suggest that we reconsider the approach and just switch to a normal [semver](https://semver.org/) release model where we simply do breaking releases if some changes are anticipated to break anything in test runners (directly changes, test field additions/renamings, HF tests moved to legacy,...), minor or patch releases in other cases and move away from a HF-centric approach.

As a starter I can help a bit with this by bringing #692 up-to-date and re-label (so mainly remove the "Berlin"-centric view on this) so that we can have some basis here. This would then also be just a "normal" major release and no beta release or something. Maybe I can also further help a bit along the way with release notes when we plan to do an `ethereum/tests` update on the VM.

Than it would be great if we can switch back to a more frequent release cycle with releases every 2-4 weeks, from a client perspective this is otherwise not helpful.

WDYGT? 🤔

//cc @qbzzt @winsvega @holiman

**Comment by winsvega** [comment]
I think its a good idea to make test repo release in case of a breaking format change. 

But such changes are rare. (For the filled tests). Filler format is updated rather often.
New tests contributions are coming all the time so doesn't make sense to close them in bundle because its important to be on the recent commit.

**Comment by holgerd77** [comment]
For people reading along, see also this comment here https://github.com/ethereum/tests/pull/692#issuecomment-770715855.

**Comment by winsvega** [comment]
can be found in release section. post frequent updates as pre-releases.
