### ISSUE TITLE
`allotment` is not described on the wiki 

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#77]
https://github.com/ethereum/tests/wiki/Blockchain-Tests

`allotment` data is not described on the wiki , 
is it `pre` or `post` values ?

**Comment by wanderer** [comment]
this is the initial genesis allotment. But it needs to be changed to the Canonical format

**Comment by romanman** [comment]
@wanderer : thanks man,

**Comment by wanderer** [comment]
this is now post and pre and is described in the wiki
