### ISSUE TITLE
some client other then geth support t8ntool protocol for test generation / vmtracing

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#816]
Total 4208 (100%)
```
geth 3432 (81.56%)
openethereum 478 (11.36%)
parity-ethereum 156 (3.71%)
nethermind 61 (1.45%)
turbo-geth 39 (0.93%)
besu 22 (0.52%)
coregeth 13 (0.31%)
```
https://www.ethernodes.org/

**Comment by qbzzt** [comment]
Asked openethereum at https://github.com/openethereum/openethereum/issues/340

**Comment by qbzzt** [comment]
We decided to do the emulation at the t8ntool layer so we'll be able to use the openethereum also to generate tests and do whatever features we add in the future.

**Comment by qbzzt** [comment]
Just a note to myself, to create a Docker with openethereum, use:

```
FROM ubuntu:18.04 as retesteth

# Configure the OS
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone  \
    && apt-get update
RUN apt-get install --yes git curl apt-utils cmake make perl psmisc clang pkg-config yasm \
     && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl https://sh.rustup.rs -sSf > /rustup.sh \
    && chmod +x /rustup.sh \
    && /rustup.sh -y

# Install OpenEthereum
RUN cd /     \
    && git clone https://github.com/openethereum/openethereum
    
RUN cd /openethereum \
    && ~/.cargo/bin/cargo build --release -p evmbin

RUN ls -l /openethereum/target/release

ENTRYPOINT ["/bin/sh"]
```

**Comment by qbzzt** [comment]
Another note to self.

Naturally, `t8ntool` doesn't get the expected output. A json state test, OTOH, **must** have that output.

The solution is to have synthetic output:

```
        "post" : {
            "Berlin" : [ {
                  "indexes": { "data":0, "gas":0, "value":0},
                  "hash": "0x0000000000000000000000000000000000000000000000000000000000000000"
            } ]
        },
```

However, the transaction is supposed to have the private key, and that isn't in txs.json.

**Comment by qbzzt** [comment]
Almost working

[package.json.txt](https://github.com/ethereum/tests/files/6300648/package.json.txt)
[t8n_oe.js.txt](https://github.com/ethereum/tests/files/6300649/t8n_oe.js.txt)

**Comment by winsvega** [comment]
hm. not really http://retesteth.ethdevops.io/results/log//2021-05-03-1620016370-oewrap.txt
well we gave it a try. Lets focus on tests and besu client support. as its essential for proper eip1559 testing. 
besu has implemented rpc so we can test blockchain rules directly on the client

**Comment by qbzzt** [comment]
OE is deprecated, so that work is no longer relevant, but besu works great with retesteth these days. So I don't think we need this issue anymore.

**Comment by winsvega** [comment]
Yes. Just that they wont fix the errors in test execution I report
