### ISSUE TITLE
can't parse odd number of characters as byte representation

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#83]
[2 issues]
https://github.com/ethereum/tests/blob/develop/StateTests/stCallCreateCallCodeTest.json#L229
https://github.com/ethereum/tests/blob/develop/StateTests/stCallCreateCallCodeTest.json#L392

`0xfffffffffffffffffffffffffffffff (31)` => `0xffffffffffffffffffffffffffffffff (32)`

**Comment by wanderer** [comment]
i would just add a check for this in my test runner

**Comment by winsvega** [comment]
outdated
