### ISSUE TITLE
Missing memory copy out-of-gas cases

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#831]
Hi there,

I'd like to report some missing test cases for instructions which copy memory and the out-of-gas failure is directly result of the additional memory copy cost:
- `KECCAK256`,
- `CODECOPY`,
- `EXTCODECOPY`,
- `RETURNDATACOPY`.

---
![image](https://user-images.githubusercontent.com/573380/116072321-35518080-a68f-11eb-853f-da0cce9a6393.png)
---
![image](https://user-images.githubusercontent.com/573380/116072387-4ac6aa80-a68f-11eb-881c-31a1cf82f259.png)
---
![image](https://user-images.githubusercontent.com/573380/116072778-d5a7a500-a68f-11eb-867e-86f35d9a876c.png)

The coverage is from https://github.com/ethereum/evmone. 
https://codecov.io/gh/ethereum/evmone/src/eeea491ed8d8cb29c895131a97feabc8a125c542/lib/evmone/instructions.hpp.

**Comment by chfast** [comment]
The case for `RETURNDATACOPY` is still not covered. The rest is, thanks.

**Comment by qbzzt** [comment]
> The case for `RETURNDATACOPY` is still not covered. The rest is, thanks.

The test is in https://github.com/ethereum/tests/blob/a92affb177712ebb9b45cf54aee6aa72d25fdf45/src/GeneralStateTestsFiller/stMemoryTest/oogFiller.yml#L66. The call for it is in https://github.com/ethereum/tests/blob/a92affb177712ebb9b45cf54aee6aa72d25fdf45/src/GeneralStateTestsFiller/stMemoryTest/oogFiller.yml#L306.

**Comment by chfast** [comment]
Maybe it fails for some other reason than the cost of memory copy inside `RETURNDATACOPY`. Do you have a trace?

**Comment by qbzzt** [comment]
You're right, my bad. I forgot to account for the fact that in Berlin calls are more expensive than they were in Istanbul. I'll fix it.
