### ISSUE TITLE
Some ideas for more tests with invalid bytes

### ISSUE THREAD

**Issue by gumb0** [ethereum/tests#845]
1. Creation transactions deploying a contracts with all possible values in a first byte, similar to tests for `CREATE` in https://github.com/ethereum/tests/pull/843 (probably will require a blockchain test for this)

2. Init codes starting with a byte with all possible values
2.1. In creation transaction (one invalid byte value is checked in https://github.com/ethereum/tests/pull/842)
2.2. in the code passed to CREATE 
2.3 in the code passed to CREATE2

**Comment by qbzzt** [comment]
3. In contracts that are called by other contracts (might behave differently from contracts that are called directly)
     3.1. CALL
     3.2. CALLCODE
     3.3. DELEGATECALL
     3.4. STATICCALL

This is starting to be a lot of cases. Maybe we need a generator that creates the test file for us (similar to https://github.com/ethereum/tests/blob/develop/src/BlockchainTestsFiller/ValidBlocks/bcStateTests/testOpcodesGen.js).

**Comment by qbzzt** [comment]
#851 now includes these tests, which check for the reaction to an invalid opcode in a bunch of contexts: https://github.com/ethereum/tests/blob/84d42b6f6b757b6f0cde4d812db0569c76245c8a/src/GeneralStateTestsFiller/stBadOpcode/manyContextsFiller.yml

The next version of solidity (0.8.5) will have in Yul a `verbatim` function that lets us specify arbitrary machine language code. I think we should leave this issue open until that's the official version, and then I'll add invalid opcodes to Yul other than as `invalid()`, which translates to 0xFE.
