### ISSUE TITLE
consistent formating

### ISSUE THREAD

**Issue by wanderer** [ethereum/tests#85]
https://github.com/ethereum/tests/blob/develop/BlockchainTests/bcForkBlockTest.json#L9-L24
i give you hex strings! decimal strings! hex strings prefixed with `0x`! hex strings with out prefixes! welcome to the format zoo!

**Comment by wanderer** [comment]
issue #6 is related

**Comment by CJentzsch** [comment]
@winsvega this is your test :-) , please fix formatting!

**Comment by wanderer** [comment]
also this file https://github.com/ethereum/tests/blob/develop/BlockchainTests/bcInvalidRLPTest.json#L11-L25

**Comment by winsvega** [comment]
those were created before all test fields to hex implementation. and as they are not in test Fillers, fields in those tests were not replaced. 
The current filed format options are:

"hexstrng" - for hashes and addresses.
"0xhexstring" - for variables

**Comment by CJentzsch** [comment]
still needs updating

**Comment by winsvega** [comment]
updated

**Comment by wanderer** [comment]
thanks @winsvega !
