### ISSUE TITLE
invalid padding on transactions

### ISSUE THREAD

**Issue by wanderer** [ethereum/tests#86]
In this test https://github.com/ethereum/tests/blob/develop/TransactionTests/ttTransactionTest.json#L422
There is padding on the end of R value. I believe that you are not suppose to produce padding on TX fields.

**Comment by winsvega** [comment]
what does "padding" means in this context?

**Comment by wanderer** [comment]
this `00` at the being of the R value

**Comment by wanderer** [comment]
@winsvega does this make sense to you?

**Comment by wanderer** [comment]
@winsvega ping :P

**Comment by wanderer** [comment]
i think this good now
