### ISSUE TITLE
coinbaseT01 shouldn't contain baseFee for Berlin

### ISSUE THREAD

**Issue by yperbasis** [ethereum/tests#869]
After https://github.com/ethereum/tests/commit/52ff7015f7c8cf43d4a50765d4117542a89b9e5e `BlockchainTests/GeneralStateTests/stEIP2930/coinbaseT01.json` has `baseFee` in block's RLP even for Berlin (e.g. `coinbaseT01_d0g0v0_Berlin`). Valid blocks shouldn't contain `baseFee` prior to London.

**Comment by winsvega** [comment]
Isn't it fixed?

Should add more checks

**Comment by yperbasis** [comment]
Not fixed yet in the latest develop (https://github.com/ethereum/tests/commit/c34cab0b8279671a337c9cd2938f41269b1adc89)

**Comment by holiman** [comment]
Can confirm, the basefee is present both in json and rlp on Berlin

**Comment by holiman** [comment]
We don't catch it in geth, because we don't run the `BlockchainTests/GeneralStateTests/*`, as blockchain tests, since we run them as state tests instead.

**Comment by yperbasis** [comment]
Fixed by https://github.com/ethereum/tests/commit/b39fa441a3d655d32fa87c561a3e3658cc843f06
