### ISSUE TITLE
Invalid Total difficultly test

### ISSUE THREAD

**Issue by wanderer** [ethereum/tests#87]
https://github.com/ethereum/tests/blob/develop/BlockchainTests/bcTotalDifficultyTest.json#L2836-L2926

The last two block have the same difficulty but the first one according to the test should be head at the end. I believe the Yellow Paper doesn't specify which should head when blocks have the same TD.

**Comment by romanman** [comment]
@wanderer : the last one has one uncle so the cumulative difficulty is higher


@CJentzsch : I think that one should be fixed: 

`[testcase: uncleBlockAtBlock3AfterBlock3]`


I get that result : 

```
hash: 773d9b : parent: 4f341f : diff: 131072 ::: IMPORTED_BEST
hash: d23d2d : parent: 773d9b : diff: 131136 ::: IMPORTED_BEST
hash: 34de11 : parent: d23d2d : diff: 131200 ::: IMPORTED_BEST
hash: 8e6260 : parent: d23d2d : diff: 262336 ::: IMPORTED_BEST
```

last block `8e6260` that is importated as best 
cause it has higher TD but the test looking for
the `34de11` to be there, any advise

**Comment by romanman** [comment]
@winsvega : can you take a look please, on that topic

**Comment by romanman** [comment]
@CJentzsch : glad you are back , 
can you please take a slight look 
over that subject :+1:

**Comment by CJentzsch** [comment]
Uncles do not contribute to the TD (see YP eq. 136, this was changed since PoC9). Therefore the TD is the same for both blocks. In that case you take the first block that you receive, and do not reorganise you blockchain because of a block with the same TD.
