### ISSUE TITLE
vm-ref.rst is outdated, lacks definition of post results

### ISSUE THREAD

**Issue by mzabaluev** [ethereum/tests#889]
The virtual machine test reference in the RST documents does not cover recent schema changes, even those that are already described in `internals-tutorial.rst`. Specifically, the `post` section of a generated test is still described as is if were a state map like the one in `pre`. The reference should be updated to describe the current structure of fork-specific results.

It would also help to explain how the field values in `post` results are meant to be checked by an implementation. Quoting the documentation, "the VM tests aim is to test the basic workings of the VM in isolation", so the reference documentation of the test format ought to provide details on how the hashes can be computed from the post-execution state in absence of a full blockchain protocol implementation.

**Comment by qbzzt** [comment]
The VM tests are out of date and therefore deprecated. I forgot to add that to the documentation, thank you for reminding me (see #891).

If you need the VM tests, they are now under `GeneralStateTests/VMTests`.
