### ISSUE TITLE
pre-compiled contract doesn't get endowment

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#89]
`0000..0004` is called with `tx.value = 19` but no such account with +19 in post 
https://github.com/ethereum/tests/blob/develop/StateTests/stPreCompiledContracts.json#L1083

@CJentzsch

**Comment by CJentzsch** [comment]
It does not get called. CALLCODE is used, so only the code gets executed, but the value transfer is going to the sender.

**Comment by romanman** [comment]
@CJentzsch : ok guess my bug : 

so what is the rule : if I call CALLCODE to `00..002` from 

```
owner:   95e7baea6a6c7c4c2dfeb977efac326af552d87
origin:  a94f5374fce5edbc8e2a8697c15331677e6ebf0b
caller:  a94f5374fce5edbc8e2a8697c15331677e6ebf0b
```

who is get paid ?

**Comment by CJentzsch** [comment]
the caller, so he needs to have the balance on the account for the CALLCODE to succeed, but his balance does not change.
