### ISSUE TITLE
Add test for CREATE2 init code hashing OOG

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#909]
Add a test with CREATE2 where OOG happens directly because of the cost of hashing the init code.

![image](https://user-images.githubusercontent.com/573380/128020942-d751a7fe-14b0-4210-962d-daf65c274428.png)

**Comment by qbzzt** [comment]
I'll try to have it done by the weekend.

**Comment by qbzzt** [comment]
Look at PR #913 . It runs CREATE2 (as well as a few other operations) with 0 gas, 100 gas, 200 gas, etc. until it finally works out. Hopefully, this means it catches all the different places where those operations can run out of gas.

If there are any other opcodes with multiple OOG failure points, please tell me and I'll add them.

**Comment by winsvega** [comment]
Basically create/create2 and call opcodes.

**Comment by qbzzt** [comment]
> Basically create/create2 and call opcodes.

Then we're covered, because I check all those opcodes, and a few others. https://github.com/ethereum/tests/pull/913/files#diff-a103df4405faf19e07ec21f5b5815ad292df63b52481d1f695a9e7422ccf903eR11-R21
