### ISSUE TITLE
Add more tests for SSTORE at Constantinople

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#910]
The case where SSTORE in Constantinople cost 200 is not covered by state tests.

![image](https://user-images.githubusercontent.com/573380/128021611-803f3eba-bae5-4f9c-9aef-b30232e76040.png)

**Comment by qbzzt** [comment]
Is there any point in writing tests for Constantinople? It's over a year and a half in the past at this point.

**Comment by chfast** [comment]
Just for completeness. This is my last uncovered line.
