### ISSUE TITLE
Mantis using ETS library

### ISSUE THREAD

**Issue by drospa** [ethereum/tests#928]
Hello,

I am from IOHK Mantis team https://mantisclient.io/. We support ETC network and we have added compatibility with ETS 

Mantis (Scala): https://github.com/input-output-hk/mantis
Docshttps://docs.mantisclient.io/
Test location:  mantis/tree/develop/ets in https://github.com/input-output-hk/mantis/tree/develop/ets

Can you add it to the list of clients using the library? Thanks!

**Comment by winsvega** [comment]
did you implement RPC/t8ntool test protocol?

**Comment by qbzzt** [comment]
> did you implement RPC/t8ntool test protocol?

It looks like they run their client and then wait for the RPC interface (https://github.com/input-output-hk/mantis/blob/develop/ets/run#L9-L14), so they are using RPC.

**Comment by qbzzt** [comment]
> Hello,
> 
> I am from IOHK Mantis team https://mantisclient.io/. We support ETC network and we have added compatibility with ETS
> 
> Mantis (Scala): https://github.com/input-output-hk/mantis Docshttps://docs.mantisclient.io/ Test location: mantis/tree/develop/ets in https://github.com/input-output-hk/mantis/tree/develop/ets
> 
> Can you add it to the list of clients using the library? Thanks!

You mean to add a `config` file for it? Sure, we can do that. It will probably be similar to the [besu one](https://github.com/ethereum/retesteth/blob/master/retesteth/configs/clientconfigs/besu.cpp#L5-L43). The main configuration is the URL to access the client.

But if you want to also fill tests with Mantis, it would help if we knew [the responses to various exception conditions](https://github.com/ethereum/retesteth/blob/master/retesteth/configs/clientconfigs/t8ntool.cpp#L30-L167). [You can read more about it here](https://ethereum-tests.readthedocs.io/en/latest/config-dir.html)

**Comment by drospa** [comment]
Hello, I will close this request. Mantis client repo will no longer be continued. Thanks for the comments, we will consider them if we use ETS in the future.

**Comment by drospa** [comment]
Hello @qbzzt , I will close this request. Mantis client repo will no longer be continued. Thanks for the comments, we will consider them if we use ETS in the future.
