### ISSUE TITLE
Test wanted: modexp(0,0, >1)

### ISSUE THREAD

**Issue by holiman** [ethereum/tests#939]
Looking at https://github.com/ethereum/tests/tree/develop/GeneralStateTests/stPreCompiledContracts, we don't seem to have a modexp-test for `modexp(0,0, nonzero)`.

This is an issue found in py-evm, by @guidovranken

> base = 0
> exponent = 0
> modulo = 36565857650062845505118984243340780147025291371401019
> 
> Geth returns 1, but py-evm returns 0.
> 
> This happens because py-evm returns 0 as soon as it detects that base is 0: https://github.com/ethereum/py-evm/blob/efa07f743db4437a2762dfcd05535177046507e7/eth/precompiles/modexp.py#L96
> which is not correct for any (zero, zero, > 1) tuple for (base, exp, mod).
>

**Comment by holiman** [comment]
cc @pipermerriam

**Comment by qbzzt** [comment]
The modulo here is 0x61bb60057f00000000000000000001000015fd60cf3b, I don't think there's anything special about it. Should I just run a bunch of tests with different modulos, or is there something special in this modulo that I'm missing?

I'll see what's already tested and add some more, probably later today.

**Comment by guidovranken** [comment]
Correct, there is nothing special about it. This is the raw fuzzer finding.

Op ma 6 sep. 2021 om 16:17 schreef Ori Pomerantz ***@***.***>

> The modulo here is 0x61bb60057f00000000000000000001000015fd60cf3b, I don't
> think there's anything special about it. Should I just run a bunch of tests
> with different modulos, or is there something special in this modulo that
> I'm missing?
>
> I'll see what's already tested and add some more, probably later today.
>
> —

>
>

**Comment by qbzzt** [comment]
BTW, `modexp(0,0,0) = modexp(0,0,1) = 0`. It's only `n>1, modexp(0,0,n) = 1`

At least in geth.

**Comment by holiman** [comment]
If I interpret the naming right, we have these
![Screenshot 2021-09-06 at 19-38-25 tests GeneralStateTests stPreCompiledContracts at develop · ethereum tests](https://user-images.githubusercontent.com/142290/132249676-491f4db7-8d0e-4fd8-b6a3-3fb4553a7def.png)

So tests for `0,0,0`, `0,1,0`, but not `0,0,1`, `0,0,2`. In general, we should have all permutations of `0`, `1`, `2` in all three positions, I think. 

So all 27 combinations, probably. Though not necessarily with gas permutations too, just to sanity-check the result.

**Comment by qbzzt** [comment]
I don't see the point in gas permutations. My test runs the precomp once per triad of values, and checks the gas cost.

I didn't think about adding specifically permutations with two, thank you. I'll add them.

BTW, I'm removing the old tests and folding them all into one test.
