### ISSUE TITLE
hexEncoded flag in `hex_encoded_securetrie_test.json` is redundant

### ISSUE THREAD

**Issue by norswap** [ethereum/tests#944]
(This is a very minor nitpick.)

The trie test file `hex_encoded_securetrie_test.json` has this `hexEncoded: true` flag, which means we should interpret the `"0x1234"` style strings as hex strings describing a sequence of bytes. Fair enough.

The issue is that many other trie test also has such strings which have to be treated in the same way for the tests to pass. These tests do not have the `hexEncoded` flag set.

Therefore, the flag is useless, and the "right" way to hex-encode strings or not is to check for the `"0x"` prefix at the start of a key or value string.

I would suggest removing this confusing flag altogether. Another option is to generalize the use of the flag to every test that uses hex strings. However, to do that requires change the `trietest_secureTrie.json/branchingTests` test case, which mixed hex string keys with ascii-encoded string.

**Comment by winsvega** [comment]
this test folder is not supported. feel free to open a PR with a fix.
