### ISSUE TITLE
Add test cases for Arrow Glacier Network Upgrade including EIP-4345

### ISSUE THREAD

**Issue by marioevz** [ethereum/tests#965]
This issue tracks implementation of test cases for the Arrow Glacier Network Upgrade:
https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md

Includes test cases for EIP-4345: https://eips.ethereum.org/EIPS/eip-4345

**Comment by winsvega** [comment]
but think about more test vectors
we now have the whole new filler class just for that
