### ISSUE TITLE
Strange "0x:bigint 0x1000...0001"

### ISSUE THREAD

**Issue by rakita** [ethereum/tests#971]
Found this as JSON value in:
https://github.com/ethereum/tests/blob/fbff6fee061ade2358280a8d6f98f67b4ae2b60e/GeneralStateTests/stTransactionTest/ValueOverflow.json#L181

**Comment by marioevz** [comment]
This prefix ("0x:bigint ") is used by retesteth for it to be able to properly parse and then format the RLP transaction, which then will be sent via RPC to the client.

**Comment by rakita** [comment]
It does have usage but I feel that `value` field is misused here for some custom solution.

For me, i will just ignore this test.

Maybe a better way is to have an additional optional JSON field "big_value", but either way if this is intentional then this 'issue' can be closed
