### ISSUE TITLE
[documentation] Broken link in test/README.md documentation

### ISSUE THREAD

**Issue by silkPK** [ethereum/tests#974]
In the README.md in the paragraph https://github.com/ethereum/tests/blob/develop/README.md#contribute-to-the-test-suite

shall be update the link "[section](https://ethereum-tests.readthedocs.io/en/latest/generating-tests.html)"

should be this
https://ethereum-tests.readthedocs.io/en/latest/how2contribute.html

**Comment by qbzzt** [comment]
Thank you, I'm about to submit a PR to fix it.
