### ISSUE TITLE
make sure there are transaction tests for nonce

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#978]
https://github.com/ethereum/tests/pull/934

check if there are transaction tests for nonce: 

- [ ] maxAllowedNonce         must fail
- [ ] maxAllowedNonce + 1  must fail
- [ ] maxAllowedNonce - 1   must pass
- [ ] pow(2,256)-1                 must fail 
- [ ] > pow(2,256)                 must fail
- [ ] 00 before the nonce value  must fail
 empty rlp string  80 or 00 in transaction rlp  (one of this must fail)  it is 0x:bigint 
- [ ] "0x:bigint 0x"
- [ ] "0x:bigint 0x00" 

this can actually be a template for all transaction field values. 
(should think about it more see if we can invent more cases)

**Comment by wow6699** [comment]
S

**Comment by marioevz** [comment]
The following tests are covered:
- maxAllowedNonce: TransactionTests/ttNonce/TransactionWithHighNonce64
- maxAllowedNonce + 1: TransactionTests/ttNonce/TransactionWithHighNonce64Plus1
- maxAllowedNonce - 1: TransactionTests/ttNonce/TransactionWithHighNonce64Minus1
- pow(2,256)-1: TransactionTests/ttNonce/TransactionWithHighNonce256
- \> pow(2,256): TransactionTests/ttNonce/TransactionWithNonceOverflow
- 00 before the nonce value: TransactionTests/ttNonce/TransactionWithLeadingZerosNonce

Missing tests:
- "0x:bigint 0x": Passes
- "0x:bigint 0x00": Fails with "rlp: non-canonical integer"

I think the two state test cases implemented in #934 are very important for the coverage of the nonce.

I will submit a PR for the two missing TransactionTests test cases.
