### ISSUE TITLE
PoS tests

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#983]
figure out the test system for PoS chain validation methods

**Comment by marioevz** [comment]
I have added several test cases that we could use as a starting point here:
https://github.com/marioevz/kintsugi_testing/tree/main/tests

They execute using a Python script, but ideally we could port them to something retesteth or hive can execute.

Basically we need retesteth support for engine_* calls:
https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md

**Comment by winsvega** [comment]
engine calls are out of the scope of this repo
