### ISSUE TITLE
Add "origin" field to "transaction" in State tests

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#995]
Hi there,

I have a State test format extension request. Currently there is no direct information about the transaction origin address in the State test format. There is however, `"secretKey"` field which represents EC private key and the origin address can be recovered from the private key.

### Specification
In the State test format provide `"origin"` field with an address matching the EC private key in `"secretKey"`.

### Motivation

I'm developing a state test runner for my EVM implementation. I don't care about transaction verification and signing. It would be much easier to process transactions if information about the origin address is directly provided. Otherwise I need to depend on a secp256k1 implementation just to recover `secretKey` -> `origin`. Or I can try to guess the origin address from the "pre" state.

### Backward compatibility

I believe this change is backward compatible because none of the existing JSON fields is modified.

**Comment by winsvega** [comment]
ok. that would touch all existing files though
and 99% of tests has the same sender. 

https://github.com/ethereum/retesteth/pull/157/commits/ee2b9e8cdf6f24095c554d5273f08c281a4bae51

**Comment by rakita** [comment]
If needed here are hardcoded mapping of `key->address` found in `GeneralStateTest`:
https://github.com/bluealloy/revm/blob/00d3b05e58dcd80204980fece5cfcdac419d0561/bins/revme/src/statetest/runner.rs#L80-L108

having origin field would simplify it.

**Comment by chfast** [comment]
> If needed here are hardcoded mapping of `key->address` found in `GeneralStateTest`: https://github.com/bluealloy/revm/blob/00d3b05e58dcd80204980fece5cfcdac419d0561/bins/revme/src/statetest/runner.rs#L80-L108
> 
> having origin field would simplify it.

Thanks, this is helpful.

**Comment by winsvega** [comment]
updated the tests with sender field having the origin address for the transaction

**Comment by chfast** [comment]
Thank you.

**Comment by chfast** [comment]
can you make a retesteth release with these changes?
