### ISSUE TITLE
Why is ":label" included in label names?

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#997]
I'm not sure what the original idea, but look labels can be only used for data indexes although you can also have multiple values and gas prices.

Anyway, I'd like to use these for better logging, and it would be better if the `:label` is omitted in the final test file:
https://github.com/ethereum/tests/blob/38d5c93203e84da1611739b4736ca816cb193407/GeneralStateTests/stCodeSizeLimit/createCodeSizeLimit.json#L8-L11

**Comment by qbzzt** [comment]
The reason we don't have labels on `gas` and `value` is that we rarely create huge lists there. OTOH, many of my tests have dozens of data values, each triggering a slightly different variant of the test. 

I agree that it makes sense to modify `retesteth` not to have `:label` in the filled tests, because it is there in all cases. Dimitry, do you agree?

**Comment by chfast** [comment]
Thanks for the response. The labels are going to be very handy for my use case - I'm porting EVM benchmarks to State test format and I have named input cases.

However, I wander, why didn't you just use YAML dictionary:
```yaml
    data:
      valid: ':yul { return(0, 0x6000) }'
      invalid: ':yul { return(0, 0x6001) }'
```

**Comment by qbzzt** [comment]
> Thanks for the response. The labels are going to be very handy for my use case - I'm porting EVM benchmarks to State test format and I have named input cases.
> 
> However, I wander, why didn't you just use YAML dictionary:
> 
> ```yaml
>     data:
>       valid: ':yul { return(0, 0x6000) }'
>       invalid: ':yul { return(0, 0x6001) }'
> ```

Mostly because we didn't want to change the format that much when we added them.

**Comment by winsvega** [comment]
also you can assign one label to mutliple data elements. 
labels was ori's idea which came up to be very handy. 

the end result you see is not as optimal as it is the result of test format evolution. indeed we didn't want to introduce new fields or format change.

**Comment by winsvega** [comment]
I agree in filled test in _info section the word label can be omited to save disk space.

**Comment by winsvega** [comment]
will remove from filled test files. 
also -d selector will not require :label prefix in a string.

**Comment by chfast** [comment]
Thank you.

**Comment by chfast** [comment]
Will you release retesteth with these changes?
