### ISSUE TITLE
Add "output" to State test "post" sections

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#998]
For single-call state tests (like obsolete VM tests) it is worth to check EVM output on depth 0. This output is discarded by blockchain but should be worth-checking in this case.

I propose to add `"output"` field in `"post"` entries with hex-encoded bytes.
```json
 {
          "indexes": {
            "data": 0,
            "gas": 0,
            "value": 0
          },
          "output": "0x0267044364fafcc4179b3d9841976c5f9751085391a8d62ea2d85f3add49df212fd05e78e4d6069841dca813b82c477c70ff014564c72add2f3258355ae3900e1b237dbf02109b56a5d2e9bd7ac6d5613b4b685f39689ba531cc4383128a151f",
          "hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "logs": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"
        },
```

**Comment by chfast** [comment]
Anything? Can we at least add it as optional to the spec?

**Comment by gumb0** [comment]
I think tests usually wrap such calls in another contract doing a CALL and saving result into storage.
